### ISSUE TITLE
Remove render_one/many inflections

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1087]

**Comment by paulcsmith** [comment]
Ah gotcha. I thought this was saying it's final. Could you (or someone else familiar with this issue) explain a bit more about why it might be good to remove the inflections and what problems people are having?

My only issues so far have been

* The `Eco.Association.NotLoaded` #1085 
* Not inflecting the base I think it will. If I call `render_one(comment, "show.json")` from `MyApp.Api.UserView` I'd expect it to call `MyApp.*Api*.CommentView` but instead it calls `MyApp.CommentView`). I suppose this could be trouble because there is no obviously correct way to do this

I really like the inflection though. For the most part it works as I want it to. If those changes were made it would work as I expect it to 90% of the time

**Comment by chrismccord** [comment]
You outlined the issues well. The biggest issue is the `MyApp.Api.UserView` case, which is very common. The moment you namespace any view, the inflections stop working. They have been a big source of issues if you search the history. The easiest and most clear solution is to make the view explicit. We can also add this feature later, perhaps will better inflection rules, but remove it after 1.0 is much harder.

**Comment by chrismccord** [comment]
I'm 95% certain I'll kill the inflections with fire today
