### ISSUE TITLE
Handle disconnect in Phoenix.Socket?

### ISSUE THREAD

**Issue by keichan34** [phoenixframework/phoenix#1110]
The `Phoenix.Socket` behaviour has `connect/2`, but is missing a disconnect callback. I'd be happy to put together a PR, but I just wanted to check if there was any work on this already?

**Comment by chrismccord** [comment]
I'm not sure about this one because disconnect is not guaranteed to be called. The proper way to track would be to have another process monitor the transport process, which you could register in connect/2. The only use-case I can see if for presence tracking, which is something we have planned for 1.1, but you'll most likely want to use it the channel level. Do you have a different use-case in mind?

**Comment by josevalim** [comment]
Yes, `disconnect` doesn't make much sense in Elixir. If you want to track when things go down, monitoring is the way to go.

**Comment by keichan34** [comment]
I was actually planning on using it for concurrent connection count statistics. I'll monitor the transport process in `connect/2`, thanks.
