### ISSUE TITLE
phoenix.gen.htmt (json) should warn (or downcase) if the second arg starts with uppercase

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1191]
The command `mix phoenix.gen.json Entry Entries` generates code that does not compile.

Keep in mind that some databases may use uppercase table names, so we could also downcase everything, except the table name. I think though raising or downcase everything are likely the best actions.

**Comment by Gazler** [comment]
I'd be :+1: for raising. It seems too magical to automatically downcase.

**Comment by josevalim** [comment]
@Gazler i think we can avoid configurations until we are certain we need one. :)

**Comment by jadercorrea** [comment]
I took a look at this and it seems Ecto works fine with uppercase entity names, including querying their name with double quotes like ISO2008 say all databases should. But generators are taking the second arg to give name to variables and atoms, and it is braking the code.

Can't see no harm in downcasing those and let Ecto do it's job with the uppercased entities.

**Comment by Tica2** [comment]
Some MSSQL databases are enforces names to be sensitive.
If I create table: Users
this SQL
select * from users; *do not work*, 
same problem is for column names

See also: Ecto topic
https://groups.google.com/forum/#!topic/elixir-ecto/uJtrWNRXLXE

In this migrations table is atom
```elixir
  def up do
      create table(:users) do
        add :username,    :string
        add :email,       :string
        add :password,    :string
        timestamps
      end
```

Is important to know how to generate:
1) table for migration need to accept atom() | String.t
2) add in table need to accept atom() | String.t
3) Ecto model need to store also String.t name for the field
    if is not to determined by "names schema"
if is String.t generators DDL/SQL will use always this string for generation.

This info "names schema" 
Lower Camel Case: thisIsAnExample
Upper Camel Case: ThisIsAnExample
all lower with separator `_`

GenSchemaInfo
    case_sensitive: false    (Default is false)
    name_conventions:      _lower_  or camelCase (Default is _lower_)
    default_fk_sufix: "_id" or "Id" or what user want "_fkey"   (This last option always can be overwrited by local/function option)
    timestamps ["CreatedDate", "ModifiedDate"]
*Schema info is only for Generators*
*Generators need to put all info in code*
*NEVER use this info at runtime*

## CASE 1 and 2
%GenSchemaInfo{case_sensitive: false, name_conventions: _lower_, default_fk_sufix: "_id"}
%GenSchemaInfo{case_sensitive: true,  name_conventions: _lower_, default_fk_sufix: "_id"}

Generate all lower_case use atoms

mix phoenix.gen.json Entry Entries  
generate
```elixir
  def up do
      create table(:entries) do
      end
```
transform all to lower case generator and model 

## CASE 3
%SchemaInfo{case_sensitive: false, name_conventions: camelCase, default_fk_sufix: "_id"}
mix phoenix.gen.json MyEntry MyEntries CreatedBy:integer ModifiedBy:integer ModifiedDate:date
generate atoms with first later small, use explicit name provided

```elixir
  def up do
      create table("MyEntries") do
          add "CreatedBy", :integer
          add "ModifiedBy", :integer
          add "ModifiedDate", :integer
          // internaly generate or next version
          add :createdBy, db_column: "CreatedBy", :integer
          add :modifiedBy, db_column: "ModifiedBy", :integer
          add :modifiedDate, db_column: "ModifiedDate", :date
      end
```
Because is still insensitve model is generated with firstLetterSmall

```elixir
schema "books" do
    field :createdBy, :integer
    field :modifiedBy, :integer
    field :createdBy, :date
  end
```



## CASE 4
%SchemaInfo{case_sensitive: true, name_conventions: camelCase, default_fk_sufix: "_id"}
mix phoenix.gen.json MyEntry MyEntries CreatedBy:integer ModifiedBy:integer ModifiedDate:date
generate atoms with first later small, use explicit name provided (migration and models)

```elixir
  def up do
      create table("MyEntries") do
          add "CreatedBy", :integer
          add "ModifiedBy", :integer
          add "ModifiedDate", :integer
          // internaly generate or next version
          add :createdBy, db_column: "CreatedBy", :integer
          add :modifiedBy, db_column: "ModifiedBy", :integer
          add :modifiedDate, db_column: "ModifiedDate", :date
      end
```
Because is sensitve model will provide explicit db name 

```elixir
schema "books" do
    field :createdBy, :integer, db_column: "CreatedBy"
    field :modifiedBy, :integer, db_column: "ModifiedBy"
    field :createdBy, :date, db_column: "ModifiedDate"
  end
```

Case 4 need a lot of changes also for SQL runtime generators.

Thanks,
@Tica2

**Comment by josevalim** [comment]
This is a valid atom: `:CreatedBy`. No need to use strings. :) PG names are also case insensitive.

We have two options here:

1. Assume that any uppercase name is invalid. Folks can easily fix it later in their migration

2. Assume that any uppercase name is invalid but we allow an option specific for the table name. I would like to skip the option though until necessary.

So I would go with 1. If people complain a lot, we can add 2.

**Comment by Tica2** [comment]
See again my first example in e-mail:

 schema "Partners" do      
      field :Name, :string
 end
With this maping:
iex(4)>Erp.Repo.all(Partners |> select([t], t.Name)) 
**do not work**
I think t.Name is problema ...

iex(2)> m = %{a: 1, B: 2}
%{B: 2, a: 1}
iex(3)> m.a
1
iex(4)> m.B
iex:1: warning: an alias must expand to an atom at compilation time but got m
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_conca
t/2
    (elixir) src/elixir_aliases.erl:115: :elixir_aliases.do_concat([%{B: 2, a: 1
}, :B], "Elixir")
    (elixir) src/elixir_aliases.erl:103: :elixir_aliases.concat/1

iex(5)> m[:B]
2

**Comment by josevalim** [comment]
@Tica2 that is not related to the second argument though. That is another issue altogether that should be discussed in Ecto (it is currently being discussed in the mailing list).

**Comment by Tica2** [comment]
If Ecto fix to work next:
Erp.Repo.all(Partners |> select([t], {t.Name, t.CreateDate})) 

Is perfect! is all we need.

I will mark this.

**Comment by gjaldon** [comment]
I'd like to take this on, if available. I'm for auto-downcasing for the conveniece it provides. Just mentioning it in the docs, I think is enough.

**Comment by josevalim** [comment]
Please go ahead but I think we should raise. The error message should say something like: "expected the second argument to be all lowercase, using snake_case convention"

**Comment by gjaldon** [comment]
Copy that! I'l implement raising when it's uppercase.

**Comment by josevalim** [comment]
Ping?

**Comment by gjaldon** [comment]
Sorry for the delay! A PR is on the way.
