### ISSUE TITLE
Glob pattern in `Phoenix.Channel.intercept`

### ISSUE THREAD

**Issue by jesenko** [phoenixframework/phoenix#1262]
I have an use case where _all_ messages broadcasted to channel must be intercepted by `handle_out` method to provide some auth-based filtering of messages.

Currently (according to my understanding), I have to list _every_ possible message in the `intercept` macro, e.g.

```elixir
defmodule MyApp.SomeChannel do
  use Phoenix.Channel
  # some long list of messages
  intercept ["message_a", "message_b"]
  # this can already by generic due to pattern matching
  def handle_out(message, payload, socket) do
    if some_auth_logic do
       push socket, message, payload
       {:noreply, socket}
    end
  end
end
```

It would be neat if I could set intercept on all messages, e.g. `intercept ["*"]`.

**Comment by chrismccord** [comment]
> Currently (according to my understanding), I have to list every possible message in the intercept

This is correct. May I ask how many events you are using per channel to get a sense of how cumbersome this would be? We require explicit intercepting because we are able to optimize broadcasts considerably by dispatching directly to the transport and encoding a single time. It's a worthy tradeoff having to list a handful of intercept events to make what would otherwise be 1000 json encodings become 1 json encoding

**Comment by jesenko** [comment]
To be honest, I do not have so many events that listening them would be _very_ cumbersome (~10 events per channel). It just seemed like unnecessary duplication as _pattern_ on `handle_out` method already specifies which messages should be intercepted. 

I assumed it could be due to some perf optimization, which you just confirmed - I must agree that it is a worthy tradeoff.

If I have to intercept all events, I probably already have to make 1000 json encodings anyways so this perf optimization does not apply? 

Maybe instead of adding glob pattern to `intercept`, it would be simpler to just have `intercept_all` macro, with big warning in docs related to perf consequences? However, as I said, it is not a big issue, so it might not be worth exposing additional api...

**Comment by chrismccord** [comment]
I'm not convinced `intercept_all` is needed, and I fear it would become a bad, defacto default when only a couple events need to be intercepted. I will definitely keep this in mind as we go. Thanks for the idea!

**Comment by jesenko** [comment]
I agree, it would likely get overused / abused, probably better to stay with performant defaults. Thanks for the info on performance reasons!

**Comment by niahoo** [comment]
It could also be cool to give a handler function instead of handle_out.

I'm building a multiplayer game and I broadcast the board state after every event. But for each player, I need to delete other players private data. So in multiple events (game:player_turn, game:player_dead, etc.) I need to do the same action. 

A common handler could be useful. Of course it is easy to write `handle_out` such as 

```
  def handle_out("game:begin", msg = %{game: game}, socket) do
    cleanup_game_output("game:begin", msg, socket)
  end
```

**Comment by MaxPleaner** [comment]
If room names are completely dynamic, how else can we do authentication than passing a glob to `intercept`?  Let me give an example, I have a channel `direct_msg-1-2` (a message between users with ids 1 and 2). "authenticate" in this case means that the socket belongs to either user. I can authenticate the incoming messages in `handle_in`, but this is only half the story as I understand it. What if a third party subscribed to this channel? Wouldn't it be up to the `intercept`/`handle_out` to prevent them from eavesdropping?

**Comment by MaxPleaner** [comment]
oh, never mind, i guess you do the authentication in a channel `join` handler. See http://stackoverflow.com/a/34676818/2981429
