### ISSUE TITLE
Create npm package for phoenix client js file

### ISSUE THREAD

**Issue by VladShcherbin** [phoenixframework/phoenix#1383]
More and more people are using Phoenix + client js library (like React).

We need to have an official npm package with at least client file, clear semver in this file and a tag. Currently, there are some packages, but none on them are updated. Copy-paste is not an option.

**Comment by chrismccord** [comment]
Please see the other discussions on the issues history. There is work going on in this area, but no hard extraction date. Thanks!

**Comment by josevalim** [comment]
There is a discussion about this with some conclusions. The Phoenix team is not going to maintain the package in multiple repositories, we are relying on the community to do that. This would be equivalent for me being responsible to update Elixir on homebrew, macport, fedora, debian, etc. So please ping the package owners to update it accordingly.  :)

**Comment by jerel** [comment]
@VladShcherbin I've been working on a package [over here](https://github.com/jerel/phoenix_js) if you want to see if it fits your needs. #1376 and #1295 are the only things not backported yet that I know of.

**Comment by VladShcherbin** [comment]
@josevalim , @jerel I really don't get it.

Why can't there be an official phoenix js npm repository, from which brunch will take this file? What is the point of having compiled file and then split it in a separate community repository?

It should work the opposite way, no?

**Comment by josevalim** [comment]
@VladShcherbin this is a source code repository. How the source code and compiled artifacts are packaged can happen in N different ways. Since the JavaScript environment is fragmented and brunch.io still does not support npm packages, we decided we are not going to responsible for publishing the source code to N different places. We already have enough on our plate, we hope the community can take care of the distribution.

**Comment by VladShcherbin** [comment]
@josevalim oh, I didn't know brunch doesn't support npm packages, now I understand.

The reason why I am asking - we are promoting Phoenix in js community, I've already been asked like 5 times, how can this client file be used from npm (we use webpack). I also saw this question in chat.

**Comment by josevalim** [comment]
@VladShcherbin I see and I understand the concern. :) My perspective is a bit different in the sense, not being from the JS community, there are just too many ways to distribute packages so it is really hard for me to pick one. That's why it is easier for us to ask people to publish it to whatever they think it is best.

**Comment by VladShcherbin** [comment]
@josevalim oh, we have similar problem in Meteor. The build system doesn't have an easy npm support and has its own package system. So, we need to clone npm package, push to this package system and watch for changes. If author does not update version, new clones are created..

Thank you for explanation ;)
