### ISSUE TITLE
improve generated path helpers for glob routes

### ISSUE THREAD

**Issue by manukall** [phoenixframework/phoenix#1396]
For routes like `get "/app*jsroute", AppController, :index` the path helper has to be called with a list as argument: `app_path(@conn, :index, ["appsomething"])`. This is not very intuitive. As @chrismccord adviced on slack, I'm creating this ticket to discuss this.

**Comment by josevalim** [comment]
@manukall yes, it expects the path segments. We could allow the whole path to be given but folks need to be keep in mind we won't be able to escape it. For example, if you write: "/users/:username" and pass a username of "foo/bar", we will escape "/". We do the same for "*jsroute" but only because you are giving a list. If we support strings, it would be appended as is.

**Comment by manukall** [comment]
@josevalim would it make sense to add a short note about that to the router docs?

**Comment by josevalim** [comment]
Sure, better docs are always welcome!

On Wednesday, December 9, 2015, Manuel Kallenbach <notifications@github.com>
wrote:

> @josevalim <https://github.com/josevalim> would it make sense to add a
> short note about that to the router docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1396#issuecomment-163207668>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
