### ISSUE TITLE
Need a way to retrieve request headers in socket

### ISSUE THREAD

**Issue by lvvvvv** [phoenixframework/phoenix#1405]
It is a common scenario for a websocket application retrieving request headers info, such as a remote address behind a proxy by accessing "X-Forwarded-For", etc.
But looking around the source code, i can't find a way to achieving that.
if we could get headers info during socket connect, ie:
```ruby
defcallback connect(params :: map, headers::map, Socket.t) :: {:ok, Socket.t} | :error
```
that would be really nice.

**Comment by chrismccord** [comment]
Please reserve feature requests to the mailing list. We have so far avoided exposing this kind of information because it couples the transport to the channel. Channels are transport agnostic, and not all transports will have http headers. Your best option is to pass up such information as a param from the client, signed by Phoenix.Token, then you can grab this info in UserSocket.connect/2 and assign it to the %Socket{}
