### ISSUE TITLE
Phoenix channel quick reconnect

### ISSUE THREAD

**Issue by jfrolich** [phoenixframework/phoenix#1483]
I found an issue with the phoenix-js code for websockets in the current scenario.

```elixir
chan = socket.channel('test:test')
chan.join()
chan.leave()
chan2 = socket.channel('test:test')
chan2.join()
```

`chan2` will stay in the `joining` state, `chan` will receive a close callback. After execution the socket will contain zero channels (for some reason). And the elixir app will report this continuously:

```elixir
[info] MyApp.TestChannel received join event with topic "test:test" but channel already joined
```

While this is not the intended use, this can come up in edge cases.

**Comment by chrismccord** [comment]
I can't recreate the continuous `logging` (I only get a few). There are a couple issues with the code:

1. `join` accepts an optional argument, which is the timeout, not a string topic, so in your case `'test:test'` is being provided as the timeout of the join operation, which ultimate sets a setTimeout, passing the string `test:test` as the timeout. I'm not sure what JS does with this, but there's a good chance it's a zero timeout

2. Even if you called `join()` correctly, you have a race condition on the client and server. Since `chan` and `chan2` are for the same topic, the server won't finish processing the `leave` event before it see your duplicate join to `'test:test`, causing the server to tell you

    MyApp.TestChannel received join event with topic "test:test" but channel already joined

Since `leave()` hasn't been processed yet, you still have a process on the server for `test:test`. If you provided a differnet tpic to `chan2`, this would not happen. If for some reason you have this exactly usecase, you need to make it a "synchronous" operation, like this:

```javascript
chan = socket.channel('test:test')
chan.join()
chan.leave().receive("ok", () => {
  // the server has now acknowledged our leave, rejoin with same topic
  chan2 = socket.channel('test:test')
  chan2.join()
})
```

The only potential change I see is throwing on the client if you try to join a topic that you haven't fully "left", but I'm not sure if it's necessary. Thoughts?

**Comment by JFrolich** [comment]
1. Sorry that was a mistake creating my example use case. Was not in the original code.

I think the behaviour should be like this:
1. Channel 1 is opened
2. Channel 1 is closed
3. Channel 2 opened while channel 1 didn't close server side
4. Channel join is rejected on the server because the previous channel didn't close
5. Channel 2 retries to connect

Until here it all goes well. This is exactly what happens. The only problem is that when channel 1 closes, channel 2 does not join. (And both channels disappear from the socket).

Correct beheavior after 5 should be in my opinion:
6. Channel 1 is closed on the server
7. Channel 2 successfully connects

The edge case I have is that I handle subscription to a channel in a component. In one case it can be that a component leaves the channel while another component (or the same) joins the same channel. So the handover is not controlled, so in this case waiting for the callback is not really a solution.

I tried to create a fix, but I couldn't find why both channels leave the socket channels list. (Ok I understand why the first is removed from the list while it closes). And I couldn't understand why channel 2 would not successfully join server side after channel 1 closes.

**Comment by chrismccord** [comment]
We need to resolve this race condition by uniquely identifying subscriptions on the server. YOu can follow along #1485

**Comment by JFrolich** [comment]
Thanks. Will follow and look if I can contribute!

**Comment by chrismccord** [comment]
Cleaning up some issues. This will be handled in #1485
