### ISSUE TITLE
Add version to js file

### ISSUE THREAD

**Issue by VladShcherbin** [phoenixframework/phoenix#1484]
It would be awesome to have a version under the title in js file. It will help us to easily distinguish files and add correct tags to npm repos.

```md
// Phoenix Channels JavaScript client
// v 1.2.1
//
// ## Socket Connection
```

**Comment by VladShcherbin** [comment]
Since 1.2 will be soon released, maybe you can add a version line with 1.2.0 ?

@chrismccord

**Comment by chrismccord** [comment]
Now that the phoenix.js client is an npm package, the npm package can serve as our single source of truth. Thanks!

**Comment by VladShcherbin** [comment]
What is the name of the official npm repository?

**Comment by chrismccord** [comment]
we host the npm package inside the elixir dep https://github.com/phoenixframework/phoenix/blob/master/package.json

**Comment by VladShcherbin** [comment]
With all respect, this is a bad option for js users. Most of us will open [npm](https://www.npmjs.com/) first of all & will try to find it there. There are already a lot of repos with the same purpose and choosing, which one is the latest and 'official' is very frustrating.

Second, many users divide phoenix projects into two folders:
- client (js stuff, compiled to backend folder)
- backend (phoenix stuff)

Importing a file from another directory is bad.

There are already a lot of closed gh issues about this. Please, treat js users as first-class citizen. It should be easy as:

```
npm install --save phoenix
```

It would also be great to have a separate gh repository for this, smth like `https://github.com/phoenixframework/phoenix-js`. Since brunch finally supports npm, can we make this changes?

**Comment by VladShcherbin** [comment]
Creating a separate repository will also make it possible to write a `readme` with some examples / instructions, which is much easier than reading the source file comments. Especially for newcomers, who are used to gh readme as docs in js world.

**Comment by josevalim** [comment]
We will revisit the NPM stuff given we already have a package.json and we basically need to ensure it works with NPM anyway. However I want to be a 100% clear that default Phoenix application will still use the package from `deps/phoenix` as we don't want users to worry about versioning Phoenix from two different places. The scenario you have described is definitely not the most common way folks are using Phoenix. So our defaults won't change.

And we are certainly not going to move it to another repository. Doing so would make our lives much harder without any benefit. If the issue is documentation, there are a bunch of different ways we can solve it.

**Comment by VladShcherbin** [comment]
It's okay if we won't have a separate repo.

But can you at least publish the package to npm so that we can easily install it from single place?
