### ISSUE TITLE
Store clients join ref and relay it from the transport when pushing messages

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1485]
reference: https://github.com/phoenixframework/phoenix/issues/1483

**Comment by jfrolich** [comment]
Any ETA on this bug? (would call it a bug because it leads to an unrecoverable state in trivial situations in more complex apps)
Would love to help out on this, but while improving, my phoenix knowhow is not enough at this point to understand the intricacies involved. Can help out with more basic stuff around this issue like documentation :).

**Comment by jfrolich** [comment]
Maybe a simpler solution would be to know when I can rejoin a channel.
```
channel.join('channel:general')

... do something ...

channel.leave()

... wait until we can rejoin ...

channel.join('channel:general')
```

I already tried to
- Wait until the channel is not present in the `socket.channels` array anymore
- Wait until the channel state is CHANNEL_STATES.closed

For some reason I did not figure out yet, it ends up in a broken state with the new channel trying to join but getting a message 'already joined' from the server everytime it tries to rejoin (but the old channel already removed, so the client decided the connection was closed).

**Comment by jfrolich** [comment]
Maybe a pointer is, is that I see this message:
```
receive:  content_item:72 phx_close  Object {}
```
much later (100s of microseconds later) in the log than: 
```
push: content_item:72 phx_leave (6) Object {}
connection.js:12 channel: leave content_item:72 undefined
connection.js:12 channel: close content_item:72 undefined
```

While they both should fire when the close message is received. When I join before that log entry it ends up badly. But I do not know how to detect that (because the channel is already in the close state and removed from the array)

**Comment by jfrolich** [comment]
Ah I think I found the thing that's creating the confusion:

- Client leaves channel
- Client closes and removes channel
- Client joins channel again
- Server reports that the prior channel has been left
- Client closes newly created channel (because it does not have the channel ref)

**Comment by chrismccord** [comment]
@jfrolich have you had a chance to try out the PR here https://github.com/phoenixframework/phoenix/pull/1615 ?

**Comment by wizza-smile** [comment]
in my app i have to use a setTimeout in the JavaScript client on immediate reconnect, even though I am waiting for the :ok from the phoenix server.
`channel.leave()
     .receive("ok", () => {

                setTimeout(() => {
                  dispatch(ActionCreators.rejoinChannel());
                }, 0);

  });`

If I don't use setTimeout(), the channel.join will timeout. Not sure if this is related.
