### ISSUE TITLE
Make brunch easier to replace

### ISSUE THREAD

**Issue by rstacruz** [phoenixframework/phoenix#1540]
Brunch is currently hooked onto Phoenix apps by way of `dev.exs`, where:

```ex
config :app, App.Endpoint,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin"]]
```

As well as `brunch build` as part of [many deploy scripts](https://github.com/gjaldon/heroku-buildpack-phoenix-static).

IMHO, a saner default is to outsource these commands to `npm` hooks, where:

```js
// package.json
{
  "scripts": {
    "build": "brunch b",
    "watch": "brunch w --stdin"
  }
}
```

They can be ran via:

```ex
config :app, App.Endpoint,
  watchers: [node: ["npm", "run", "watch"]]
```

This way, it can easily be swapped for grunt/gulp/webpack/browserify/anything else. These can be easily hooked onto any Phoenix app at the moment, but I'm proposing they be done by default in the `mix phoenix.new` generator and promoted in the docs. I'd be happy to help issue PR's for this.

**Comment by Gazler** [comment]
I like this idea. Small correction in your description, it should be:

    config :app, App.Endpoint,
      watchers: [npm: ["run", "watch"]]

The would certainly prevent the need for overriding the `compile` script in the phoenix static buildpack if using something other than brunch.

**Comment by josevalim** [comment]
Hey @rstacruz! Wasn't it you that designed the exception page we use in Phoenix? :)

I believe we tried this in the past in regards to the watch command but, iirc, we ran into issues with Windows. It would be worth to find the previous issue and investigate once again.

In any case, :+1: to at least add a deploy command to the package.json file so we can at least make sure deployment scripts are not brunch dependent. The watch command is a minor issue because it is just a development local option anyway.

**Comment by rstacruz** [comment]
> Hey @rstacruz! Wasn't it you that designed the exception page we use in Phoenix? :)

i was surprised first first time i saw that then I got all giddy, haha. what was the issue with Windows? `npm` not being executable?

**Comment by josevalim** [comment]
See https://github.com/phoenixframework/phoenix/issues/1322. We don't say exactly which issues they were. So we would need to try it out.

**Comment by josevalim** [comment]
@rstacruz I have added both scripts but we can't change the config/dev.exs file until some kind soul battle test these things on Windows. We hope this at least solves the deploy issues.
