### ISSUE TITLE
Publish official package to NPM

### ISSUE THREAD

**Issue by JackSt** [phoenixframework/phoenix#1586]
@chrismccord I am opening this issue again because for js community this IS an issue and it is directly related to Phoenix.

As you [said](https://github.com/phoenixframework/phoenix/issues/1585#issuecomment-195435858), you can find a dozen of requests in github, forum and chat. Maybe you forgot, but one of the [oldest ones](https://github.com/phoenixframework/phoenix/issues/827) was opened in April 2015. The same question was posted on forum, 1 May 2015. In this issues, you [keep telling people](https://github.com/phoenixframework/phoenix/issues/990#issuecomment-116093076), that you'll do it.

A **year** has passed since you told this. Is it that hard to publish the official package to npm? Or at least leave a reminder issue that there are people, waiting for this package for a long time (same as [this reminder](https://github.com/phoenixframework/phoenix/issues/1460) to update the website).

Here are npm duplicates:

1. https://www.npmjs.com/package/phoenix-socket - 2 months old
2. https://www.npmjs.com/package/phoenix-elixir - 2 months old
3. https://www.npmjs.com/package/phoenix-js - 5 months old
4. https://www.npmjs.com/package/phoenix-js-derp - 6 months old
5. https://www.npmjs.com/package/phoenixjs - 4 weeks old
6. https://www.npmjs.com/package/phoenix_js - 2 months old

Try to guess, which one has the latest version and which one to use?

Why do you keep closing this issues? How many issues, forum posts, chat questions do you need to understand, that it IS a real issue for JS community?

By closing issues, _you are not solving the problem_ that JS community has and has been asking for a year now.

**Comment by josevalim** [comment]
Hi @JackSt!

You are right that we said in the past we would release an NPM package but that was before Phoenix 1.0 even came out. To understand our perspective on this, back then people were not asking to release a NPM package but also a Bower one. Furthermore, people were reporting different requirements were necessary depending on the build tool (Brunch, Webpack, etc) which are too much for us to handle.

So it is not that we don't care about this but, as you said quite well, it is an issue for the JS community. Again, to help put things in perspective, if someone tell me Elixir is not being properly packaged for Debian, there is not much I can do because I am not part of that community. I obviously care about a good experience on Debian as much as with any other package manager but the best I can do is to list to the most recently updated and well taken care packages in our website and expect folks are maintain them appropriately.

So the best way for you to help is to make sure the JS community can keep those packages up and running, be them for Bower, NPM or whatever people pick. Please ping the maintainer from the other threads. If someone is keeping those packages up to date, please let us know so we can list it officially.

We have a lot in our hands and we need help to solve issues that belong to other communities. Nothing I say here is new, we have already asked such in the previous threads.
