### ISSUE TITLE
make directory structure fully consistent with the MVC pattern

### ISSUE THREAD

**Issue by batwicket** [phoenixframework/phoenix#164]
This is an enhancement request.

I am told that Phoenix, like RoR, is based on convention over configuration. The MVC pattern is a convention underlying many frameworks including, i believe, Phoenix. I would like the directory structure to reflect this convention closely so that it is more intuitive to new users.

Some of the contents from the top-level directory structure of an app created with Phoenix 0.3.0 :
- creating ../app
- creating ../app/lib
- creating ../app/lib/app
- creating ../app/lib/app/config
- creating ../app/lib/app/controllers
- creating ../app/lib/app/router.ex
- creating ../app/lib/app/supervisor.ex
- creating ../app/lib/app/templates
- creating ../app/lib/app/views
- creating ../app/priv

The issues i have with this :

1) a ../app/lib/app/models directory would be consistent with MVC. I notice that Akash has added one in his mogo-chat application but it isn't generated by default when a new Phoenix application is created. <N.B. Chris, after a quick discussion, has added this>

2) a ../app/lib/app/views directory is already present, but it does not contain all of the files used to generate the www pages presented to the user. Perhaps the following organization would be consistent with the MVC convention : 

../app/lib/app/views
../app/lib/app/views/priv
../app/lib/app/views/templates
../app/lib/app/views/layouts.ex
../app/lib/app/views/pages.ex

These issues likely stem from a lack of understanding of some of the reasoning behind the current directory structure. In particular the priv directory seems a bit puzzling.. can contents be dynamic? If it's for private files (in which case a three letter suffix isn't that expensive), where do public files go? Is priv just for client-side assets? Can the names of the subdirectories be made more intuitive? I feel like a Philistine for not knowing these things :(.

IMHO it might help new users to get into the framework if the directory structure/names are intuitive and consistent with MVC.

**Comment by likethesky** [comment]
Reading through http://www.phoenixframework.org/docs/adding-pages and - sorry to be excavating this old thread - but I still had to google around and come here to lookup `priv/` (I'll try to make a PR against the Phoenix docs to try to fix that).

However, along these lines - since Phoenix clearly has roots in Rails - any reason you didn't at least choose `public/` instead of `web/` so there would be some correspondence between `priv` and `public` ? Like I said, particularly given the Rails roots (and Django's usage of the same name), etc.? Just a preference of yours, @chrismccord ? `web/` feels so PHP-ish to me... or maybe there's another (more semantic) reason why web was chosen?

**Comment by chrismccord** [comment]
> However, along these lines - since Phoenix clearly has roots in Rails - any reason you didn't at least choose public/ instead of web/ so there would be some correspondence between priv and public ?

Coming from a background in Rails does not mean we have based all our decisions on Rails. `public/` is not the right metaphor. It is typically used to expose things as static files, which doesn't fit. 

> web/ feels so PHP-ish to me

I'm 10 years removed from php, so I have no idea where this comes from or why it's applicable. `web/` was chosen because Phoenix is an OTP app like any other elixir application. Web is for the web facing components of the application, like routers, controllers, etc. It is also the place we can do code reloading since code in web is not process based.

**Comment by likethesky** [comment]
Great. Thanks for the explanation Chris!

Of course we don't have to base all on Rails, just wondering why the diff, if there was one. I generally think of `public/` as making it quite clear that *anything* in there can be snagged by anyone, in full form, across HTTP, which is why I've always preferred that over `www` (from LAMP stack fame) or `web`... which is less explicit I think.

If, in Phoenix, since we put routing & other code (not publicly able to be seen) in `web` then it's definitely not (all) public, so then I agree `web/` is a better location name. So perhaps my beef is with `static/` under `web/` ... perhaps that could have been `public/` instead. With all kinds of transpiling, etc. going on, I generally don't think of `web/static/js` as being too *static* per se, but it's definitely still `public/`! Anyway, no biggie, I guess we'll just need to doc it well. Thanks again.
