### ISSUE TITLE
Sharing data between controller and view

### ISSUE THREAD

**Issue by namxam** [phoenixframework/phoenix#168]
I guess this is again a very stupid question, but how would I pass data from the controller to the view for all requests?

I am trying to build some kind of user authentication. For that purpose, I would like to be able to access the current user in my controllers as well as in my views.

Coming from rails, I would expect to create a method in the ApplicationController which fetches the data and stores it somewhere. I guess here I would create such a method in Phoenix.Controller and persist the data somewhere. But again I have no idea where. In the connection? But then again I wouldn't know how to access it from my base view.

Any ideas / pointers how to implement it?

**Comment by sintro** [comment]
Am I right, that all this assigns, passed to render function, are needed only because "render" can not assume, which ones from params are needed in view in "@var" notation? But for me, all this things violates the DRY principle, because in most cases we firstly have to pattern match some variables in second argument of action function, then we pass the same variable with the same name (often) as assign to render. Obviously, we can not reduce the step of pattern matching in params, because we can use some of variables in controller without passing it to render, but is not it possible to reduce this duplicating in "render" call? I am new to Elixir and Phoenix, but it seems there are many possibilities in metaprogramming, may be it is possible to do something like additional variables notation in params pattern matching, so the controller will pass some of variables to "render" automatically, based on this notation?
Something like:
```
def show(conn, %{"messenger" => @messenger, "user" => user}) do
  render conn, "show.html"
end
```
in this case `messenger` (as it has special `@` (or whatever) symbol in pattern matching) will be automatically passed to render, like `messenger: messenger`, and the `messenger` variable will be also created in 'show' scope, but `user`, which does not have `@`, will be only available as local variable in `show` scope, and it will be also possible to pass it to `render` as **additional** assignment.

What do you think about this, is it possible to implement in Elixir?
