### ISSUE TITLE
RFC: Controller Testing DSL

### ISSUE THREAD

**Issue by koudelka** [phoenixframework/phoenix#172]
It'd be great to have an easy DSL to test controllers.

I was thinking it might be neat to write tests like:

```elixir
defmodule YourApp.Tests.Controller.Pages do
  use Phoenix.Test.Controller

  test "get :index should succeed" do
    conn = get :index
    assert conn.status == 200
  end

  test "get / should succeed" do
    conn = get "/"
    assert conn.status == 200
  end

  # Testing with cookies and session data
  test "get / with a builder should succeed" do
    conn = get "/", fn(c) ->
      c |> put_req_cookie("some_cookie", "a value")
        |> fetch_session
        |> put_session("some_session_key", "another value")
    end
    assert conn.status == 200
  end
end
```

`Phoenix.Test.Controller` would automatically determine that it's meant to test the `Pages` controller. The first test would call the `index` action directly, while the second would go through the router.

The various http method functions in the snippet above would have method signatures as follows, attempting to be a light wrapper around `Plug.Adapters.Test.Conn`:
```
get(action_or_url, params, opts, builder)
post(action_or_url, body, opts, builder)
etc...
```
where `builder` is a function for any advanced modifications to the `conn` before the request is sent off. `params`, `body`, `opts` and `builder` would be optional, hopefully using pattern matching to determine the user's intent.

**Comment by pspeter3** [comment]
Is this still actively happening?

**Comment by koudelka** [comment]
I'm still quite willing to work on it, I don't know how it fits into the development plan, though.

**Comment by josevalim** [comment]
Thanks @koudelka. I have a counter proposal to make, I will see if I'll write it today.

**Comment by josevalim** [comment]
Sorry for the delay. My biggest issue with the current proposal is that it does not compose well. For example, if I want to make a JSON request, I would probably need to write:

    get "/", fn(c) -> set_json_header(c) end

or:

    get "/", &set_json_header/1

Then, if I want an authenticated request:

    get "/", &set_auth_session/1

Then if I want both, i need to manually wire them up:

    get "/", & &1 |> set_auth_session |> set_json_header

Or create a third function and still always pass it explicitly.

So my counter proposal basically consists of always explicitly passing the connection around. For example:

    conn = conn()
    get conn, "/"

or:

    get conn(), "/"

Then if I wanted an authenticated connection:

    get authenticated_conn(), "/"

Or:

    get conn |> authenticate, "/"

The advantage is that, because we have the connection outside of a callback function, we can manipulate it in any way we wish before doing a request. There are a couple issues though to this approach.

The first one is that can't use stuff like fetch_session because no session was set up. Basically, by doing full stack tests, we are unable to inject data into the session unless we build a precise cookie header before the request.

The second issue is what happens when we do multiple requests with the same connection:

    conn = conn()
    conn = assign(conn, :current_user, %User{})
    conn = get conn, "/"
    conn = get conn, "/"

We obviously need to clean up some data from the connection from the first to the second request. For example, the assignments set in the first request MUST NOT be forwarded to the second request. However, the assignment set in the initial connection should be forwarded to the first request. We would need to store some data in the connection telling if it should be recycled or not and document exactly what composes the recycling process (what is copied, like req headers and assigns, and what is dropped, i.e. everything else).

I feel this is an improvement but still flawed. I am also unsure if locking the users out of modifying the session is a good thing or not (it would be a good thing as it forces more behavioural/black box tests). Maybe, for those cases, we could support your approach of using a callback function.

**Comment by jeregrine** [comment]
Just to keep this sort of alive.

I am wondering if we should run through the endpoint? And how this will work with pipelines? 

If we can just use Plug's testing utilities then maybe we just need to update the documentation.

**Comment by jeregrine** [comment]
So to update this

https://gist.github.com/drewolson/c90c5df332605f010ff7
and
https://github.com/elixir-lang/plug#testing-plugs
Are all you need to get testing. I'm going to be running this tonight and hopefully I can get a simple guide setup on the website for the interim.
