### ISSUE TITLE
Improve warning or error when single quotes are used on routes

### ISSUE THREAD

**Issue by katgironpe** [phoenixframework/phoenix#1831]
### Environment

* Elixir version (elixir -v): `Elixir 1.3.2`
* Phoenix version (mix deps): `1.2.0-rc`
* NodeJS version (node -v):  `v6.0.0`
* NPM version (npm -v):  `3.8.6`
* Operating system: `OS X 10.11.5`

### Expected behavior

I get a useful message if single quotes are used for routes. 

```elixir
resources "/messages", MessageController, except: [:new, :edit] do
  post  '/reply', MessageController, :reply
end
```

### Actual behavior

I get this error and a warning which shouldn't be there. My routes have a forward slash. 

```elixir
warning: router paths should begin with a forward slash.
    web/router.ex:70: (module)
    (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
    (elixir) src/elixir_module.erl:192: :elixir_module.eval_form/6
    (elixir) src/elixir_module.erl:82: :elixir_module.do_compile/5


== Compilation error on file web/router.ex ==
** (ArgumentError) argument error
    :erlang.byte_size('/reply')
    (phoenix) lib/phoenix/router/scope.ex:36: Phoenix.Router.Scope.route/7
    web/router.ex:70: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by ybur-yug** [comment]
If one peeks at the source in `lib/phoenix/router/scope.ex` we see:

```elixir
  ...
     if path && String.at(path, 0) != "/" do
       IO.write :stderr, """
       warning: router paths should begin with a forward slash.
        #{Exception.format_stacktrace}
        """
    end
  ...
```

**Comment by ybur-yug** [comment]
If one peeks at the source in `lib/phoenix/router/scope.ex` we see:

```elixir
  ...
     if path && String.at(path, 0) != "/" do
       IO.write :stderr, """
       warning: router paths should begin with a forward slash.
        #{Exception.format_stacktrace}
        """
    end
  ...
```

It appears that this could be improved by just altering the guard clause.

Instead of:

`if path && String.at(path, 0) != "/" do`

Something like

`if path && String.at(path, 0) != "/" && is_binary(path) do`, then have an else clause handle the improved messaging.

Or, since thats a bit verbose, maybe make a `valid_route?/1` function:

```elixir
# this is messy but expresses the idea
def valid_route?(path) do
  if path && String.at(path, 0) != "/" && is_binary(path)
    IO.write :stderr, """
    warning: router paths should begin with a forward slash.
    #{Exception.format_stacktrace}
  else
    if is_list(path) do
      IO.write :stderr, """
      warning: router paths must be binary strings and begin with a forward slash
      #{Exception.format_stacktrace}
      """"
    end
  end
end
```

And then just pipe it, and it can become something like this for that portion:

```
  def push(module, opts) when is_list(opts) do
    path = Keyword.get(opts, :path)
    path |> valid_path? # this calls an error exception
    ...
```

That is of course if this is a desired improvement overall. I personally think that it would be, especially for newcomers with how rampant charlist/binary string issues are when first diving in and understanding the nuances of the two. 

Thoughts, anyone?

**Comment by chrismccord** [comment]
Thanks for the report! The error message has been improved.

**Comment by katgironpe** [comment]
Thank you! You're awesome @chrismccord
