### ISSUE TITLE
Remove force_ssl option

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1906]
Instead of a configuration option, we can tell users to plug the SSL plug directly AND pass the force_ssl option to sockets. This removes unnecessary lines of code from Phoenix while making it more apparent for users how to customize their app to their needs. We should generate 3 LOC commented out on the endpoint with relevant examples.

The only downside that comes to mind from this approach is that we lose the per environment configuration. So users will need to rely on checks such as `if Mix.env == :prod` in their endpoint module body.

Thoughts?

**Comment by jeregrine** [comment]
I think its a good idea, I've been burned by this before :P.


I don't love the Mix.env checks. Not sure of a way around that though.

**Comment by chrismccord** [comment]
why not this; We *keep* the `force_ssl` configuration option generated in prod.exs, but it stays only as user-land config and nothing else. Then in the generated endpoint lines, we reference it:

```elixir
if Application.get_env(:my_app, MyApp.Endpoint)[:force_ssl] do
  plug ...
end
```

This way we can also teach application configuration in general, and we also avoid pushing folks towards leaning on `Mix.env`, which I think sends the wrong message. Thoughts?

**Comment by josevalim** [comment]
@chrismccord that sounds an OK compromise but it makes deprecating it quite hard (unless we give it another name such as `:ssl`).

It is also worth noting that we would need to duplicate the configuration here on every transport inside the socket:

    transport :websocket, Phoenix.Transports.WebSocket, force_ssl: Application.get_env(:my_app, MyApp.Endpoint)[:force_ssl]

That sounds a bit too much?

**Comment by novaugust** [comment]
I had an issue with `force_ssl` that I was coming here to file, but if it's being removed that won't matter. On the chance that this would influence the discussion though:

We're using exrm releases with `RELX_REPLACE_OS_VARS=true` to replace `${HOSTNAME}` with the value from the production environment. 

However, Phoenix's current implementation of `force_ssl` pulls that value [at build time](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L576), circumventing our OS environment variable substitution.

So the following happens for us

```sh
$ curl http://<host> -v
....
< HTTP/1.1 301 Moved Permanently
< server: Cowboy
< location: https://${HOSTNAME}/  #<-------
```

That means that to force SSL with the appropriate hostname per environment we have to circumvent phoenix's implementation and just plug `Plug.SSL` ourselves. (I think. Just now figured out the problem here, haven't tested my solution)

**Comment by dropfen** [comment]
Guys, when planning to improve some configurations, there are some more points which could be applied, for example *force_host* option, to force a given host, like a rewrite_url rule. A lot of apps are supporting www.app.com and app.com domains. They are supporting it for convenience, if someone types www in front.. but the server should be able to rewrites the url. I did't found an option for this yet, so if you are going to improve the endpoint settings, it eventually makes sense to take it in count, if possible, thanx guys

**Comment by josevalim** [comment]
This is also related to #2015 since force_ssl has dynamic configuration.

**Comment by josevalim** [comment]
With the support of dynamic configuration, most of the downsides of automatically including in force_ssl will be removed, so we will continue supporting the option to make it as easy as possible to use it. Therefore I am closing this issue.
