### ISSUE TITLE
Improve Ecto Model Relationship Guide

### ISSUE THREAD

**Issue by rasmus1610** [phoenixframework/phoenix#1981]
I had a huge problem finding a proper example of how to build associations for models in the controller (build_assoc/3 and stuff). Defining the relationships in the model wasn't the problem but how to build the changeset with the associations was actually pretty hard for me as a newbie. 

An improved guide on this topic would be awesome. It doesn't really cover it right now. 

I'm happy to contribute to it, but I'd like some help, cause I'm not really sure I understand Phoenix good enough to write Guides for it.

**Comment by michalmuskala** [comment]
I believe this would be a very welcome addition. I think it could even go to ecto itself instead of phoenix. It could be made in the style of the [Getting Started guide](https://hexdocs.pm/ecto/getting-started.html) (and in a similar form).

Should we move this to the ecto repo?

As to help, I'll be happy to help you. Either through an issue or on IRC/slack. A good first step would probably be listing the use cases we'd like to cover in the guide.

**Comment by josevalim** [comment]
I think guides issues should be filled on github.com/phoenixframework/phoenix_guides, no?

**Comment by rasmus1610** [comment]
@josevalim You are totally right, but I saw it after opening this issue. Is it possible to transfer the Issue to another repo or should I open it there again?

**Comment by josevalim** [comment]
Afaik you need to open it there again. :)

**Comment by eriksays** [comment]
I would second this request -- I've just started with phoenix / elixir and
the ecto relationships are tough for me to figure out.

For instance, building a "have and belongs to many through" relationship is
still something I'm working through.

**Comment by rasmus1610** [comment]
@eriksays I opened it again in the guides repo: https://github.com/phoenixframework/phoenix_guides/issues/607

So maybe the discussion should be over there now

**Comment by willykaram** [comment]
@eriksays could you perhaps add some details on the issue that you ran into on the issues that @rasmus1610 re-opened, and then we can pick-up the discussion there in order to ideally create that guide. I'm going to add my thoughts there as too, so that we don't revive this issue which should stay closed.

**Comment by josevalim** [comment]
Btw, it is worth pointing out that Ecto includes association guides now: https://github.com/elixir-ecto/ecto/blob/master/guides/Associations.md
