### ISSUE TITLE
Phoenix should return 405 if a route (method+path) is unmatched even though the path is in the router

### ISSUE THREAD

**Issue by palm86** [phoenixframework/phoenix#2007]
### Expected behavior

With only this route declared:

`post "/api/endpoint", MyApp.SomeController, :create`

A call to `GET /api/endpoint` should return 405.

### Actual behavior

A call to `GET /api/endpoint` returns 404 instead.

I realize that Phoenix matches on both the HTTP method and the path, but once no match is found it could go and see if the path is defined somewhere in the router. If yes, return a 405, otherwise a 404.

**Comment by sikanhe** [comment]
How is this useful to the client ? All client wants to know is that the resource doesn't exist at the route they specify.

**Comment by christopheradams** [comment]
I happen to think it's useful (if less common), and, more important, it's in the HTTP spec. Telling the client that the resource doesn't exist is not the same thing as saying they used the wrong method.

One underlying issue is that a Phoenix route (verb + path) is not equivalent to a "resource" as it's understood in REST and HTTP semantics. This makes a few parts of the HTTP spec a bit harder to adhere to. A 405 response is even more useful if you implement the `OPTIONS` method too.

@palm86 if you need an immediate solution to this, you can try the [PhoenixRest](https://github.com/christopheradams/phoenix_rest) library I have under development. It's not a 1-line solution but it can solve your issue. Reach out there if you need any help.

**Comment by josevalim** [comment]
> One underlying issue is that a Phoenix route (verb + path) is not equivalent to a "resource" 

That's my main concern. It is a generic router so we cannot generally assume that any non-matching verb means it it is a non-support action on a resource. Like your GET / or GET /resource/new.

I am also worried about returning 405 errors for GET requests, which are not rendered nicely by the error view currently, and it would be a breaking/confusing change for existing applications.

I believe a proper compromise would be to return 405 for any non-GET request on any endpoint that has at least one non-GET verb.

We could support OPTIONS in the current router as well I believe?

**Comment by palm86** [comment]
> I believe a proper compromise would be to return 405 for any non-GET request on any endpoint that has at least one non-GET verb.

That sounds good. Could you elaborate a bit on why the same solution would be a problem for GET requests?

**Comment by josevalim** [comment]
@palm86 imagine you have POST /posts but not a GET /posts. If the users accidentally request GET /posts, they will get a weird 405 page, which was likely not customized to show as nicely as their 404 page one. I would consider that to be a breaking change.

**Comment by palm86** [comment]
@josevalim I agree that 405 is a bit weird for HTML pages, but for API's 404 is confusing if used incorrectly. Could this be made configurable?

**Comment by chrismccord** [comment]
I'm not sure how I feel about this one. I'll admit I have ignored 405's existence for my entire career so far, so I'm likely biased against handling this. My concern with introducing this is this will add a bit of complexity to the router and I'm not sure if future maintenance warrants it given this is the first time (I think?) it has come up.

> We could support OPTIONS in the current router as well I believe?

We already provide the `options` macro on the router: https://github.com/phoenixframework/phoenix/blob/0fb82304a3613f7df9ee2ecfed511be2abee7d4a/lib/phoenix/router.ex#L194

Perhaps a better approach would be to write your own `resources` macro that defines the routes with a catch-all  verb that returns 405 for the resource?

**Comment by christopheradams** [comment]
> Perhaps a better approach would be to write your own `resources` macro that defines the routes with a catch-all verb that returns 405 for the resource?

What is a "catch-all" verb in this context? Can you pass something to the `match` macro that will match any HTTP method?

**Comment by palm86** [comment]
A catch-all verb sounds like it could work. It is not great, because you'd have to define a catch-all route for each path, I guess?

**Comment by chrismccord** [comment]
> What is a "catch-all" verb in this context? Can you pass something to the match macro that will match any HTTP method?

something like this:

```elixir
defmodule Resource405 do

  @verbs [:get, :post, :put, :patch, :delete, :options, :connect, :trace, :head]

  def init(opts), do: opts

  def call(conn, _), do: Plug.Conn.send_resp(conn, 405, "405 yo")


  defmacro match_all_but(verbs, path, plug, plug_opts, options \\ []) do
    for verb <- @verbs -- verbs do
      quote bind_quoted: binding() do
        match(verb, path, plug, plug_opts, options)
      end
    end
  end

  defmacro my_resource(path, controller, opts \\ []) do
    defaults = quote bind_quoted: binding() do
      resources path, controller, opts
    end

    catch_alls = quote bind_quoted: binding() do
      match_all_but([:get, :post], path, Resource405, [])
      match_all_but([:get, :put, :patch, :delete], path <> "/:id", Resource405, [])
      match_all_but([:get], path <> "/:id/edit", Resource405, [])
    end

    quote do
      unquote(defaults)
      unquote(catch_alls)
    end
  end
end
```

Then in your router:

```elixir
my_resource "/users", UserController
```

The negatives of this approach as written would be you'd need to extend it to respect the `param` options to `resources` and changed the catch-alls accordingly, so a bit more code than I provided. It will also add noise to your `mix phoenix.routes` output., i.e.:

```
☁🚀 ☁ › mix phoenix.routes
       user_path  GET      /users           UserController :index
       user_path  GET      /users/:id/edit  UserController :edit
       user_path  GET      /users/new       UserController :new
       user_path  GET      /users/:id       UserController :show
       user_path  POST     /users           UserController :create
       user_path  PATCH    /users/:id       UserController :update
                  PUT      /users/:id       UserController :update
       user_path  DELETE   /users/:id       UserController :delete
       user_path  GET      /users           UserController :index
       user_path  GET      /users/:id/edit  UserController :edit
       user_path  GET      /users/new       UserController :new
       user_path  GET      /users/:id       UserController :show
       user_path  POST     /users           UserController :create
       user_path  PATCH    /users/:id       UserController :update
                  PUT      /users/:id       UserController :update
       user_path  DELETE   /users/:id       UserController :delete
resource405_path  PUT      /users           Resource405 []
resource405_path  PATCH    /users           Resource405 []
resource405_path  DELETE   /users           Resource405 []
resource405_path  OPTIONS  /users           Resource405 []
resource405_path  CONNECT  /users           Resource405 []
resource405_path  TRACE    /users           Resource405 []
resource405_path  HEAD     /users           Resource405 []
resource405_path  POST     /users/:id       Resource405 []
resource405_path  OPTIONS  /users/:id       Resource405 []
resource405_path  CONNECT  /users/:id       Resource405 []
resource405_path  TRACE    /users/:id       Resource405 []
resource405_path  HEAD     /users/:id       Resource405 []
resource405_path  POST     /users/:id/edit  Resource405 []
resource405_path  PUT      /users/:id/edit  Resource405 []
resource405_path  PATCH    /users/:id/edit  Resource405 []
resource405_path  DELETE   /users/:id/edit  Resource405 []
resource405_path  OPTIONS  /users/:id/edit  Resource405 []
resource405_path  CONNECT  /users/:id/edit  Resource405 []
resource405_path  TRACE    /users/:id/edit  Resource405 []
resource405_path  HEAD     /users/:id/edit  Resource405 []
```

Maybe a solution like this is something we should aim for? It's not entirely beautiful as is, but it should just work today. So perhaps we can frame the discussion around what it would take to allow you to extend the router to support this maybe a little more cleanly, without us providing it?

**Comment by josevalim** [comment]
Maybe an option to mark a route as hidden so it at least does not show up on phoenix.routes?

**Comment by christopheradams** [comment]
> something like this:

Ah, this brought a smile to my face @chrismccord. :) I had worked out this same kind of solution in the past when I wanted a Webmachine-like Resource module where the Plug connected to the route would handle all the verbs ([see here](https://github.com/christopheradams/phoenix_rest/blob/master/lib/phoenix_rest/router.ex#L53)). In the absence of a generic any-method `match` macro, it's a fine workaround.

Having all those extra paths does seem ungainly though. Would it be feasible for the Router, after accumulating the routes, to generate an additional `match_route` that matches just the `path_info` and *any* method, and raise an error? Something like this is already done just once for `match_404`.

**Comment by chrismccord** [comment]
After thinking more about this, I don't think this feature is something phoenix needs to implement. Phoenix takes care of the most common resource patterns, but gives you the tools to build what you need, such as my example above of how you can accomplish this today. If this is something you deeply care about, this would be a great little library to release for others in the community needing such a feature. Thanks for the idea and discussion!

**Comment by lucacorti** [comment]
First of all, thanks for all the hard work you put in Phoenix.

Returning 404 instead of 405 for a resource that exists but does not implement the requested verb it's simply broken HTTP/REST wise. The flowcharts in the [Cowboy 2.0 User Guide](https://ninenines.eu/docs/en/cowboy/2.0/guide/rest_flowcharts/) illustrate this clearly.

405 has a precise meaning and getting 404 is always really puzzling and unexpected when debugging routing, especially if I have a `resource` in my router, which is a clear REST reference.

I think this is a mistake and you should reconsider it, even more because server-side rendering is fading away and Phoenix use case will be more and more about REST APIs and Channels and less about rendering HTML pages.

Thanks again for taking the time to read this. I don't want to annoy anyone, I just feel this is not bikeshedding but something which should be default behavior rather than in an external library.

**Comment by jueberschlag** [comment]
For those of you who still want to return a 405 status, here is how I did it:
```
defmodule MyApp.MethodNotAllowedController do
	use MyApp.Web, :controller

	def match(%Plug.Conn{path_info: path_info} = conn, _params) do
		routes = MyApp.MyRouter.__routes__() 
			|> Enum.map(&(&1.path)) 
			|> Enum.uniq() 
			|> Enum.map(&(&1 |> String.split("/") |> Enum.drop(1)))
		
		if path_info in routes do
			send_resp(conn, 405, "")
		else
			send_resp(conn, 404, "")
		end
	end
end
```
And on the router I added wildcard paths:
```
# Method not allowed
[&get/3, &post/3, &put/3, &patch/3, &delete/3, &options/3, &connect/3, &trace/3, &head/3]
	|> Enum.each(fn(verb) -> verb.("/*path", MyApp.MethodNotAllowedController, :match) end)
```

I do not use the `path` attribute from the params because it does not contain the complete path (with the scope prefix).


Instead of returning directly the 404 status you could also raise an error like Phoenix does for 404:
```
raise Phoenix.Router.NoRouteError, conn: conn, router: MyApp.MyRouter
```
When raising this error, in my case I needed to add an error rendering method for JSON format in the `ErrorView` file:
```
def render("404.json", _assigns) do
	%{}
end
```

**Comment by stevegraham** [comment]
Hey folks 👋🏻. Late to the party here.

IMO the correct behaviour is to return a 405 Method Not Allowed for a matching path with an unmatched HTTP method. It doesn't make a lot of sense for the server to say there is no resource at this URI, when there actually is, and the server understood the request but declined to process it because of the semantics of the method used.

> @palm86 imagine you have POST /posts but not a GET /posts. If the users accidentally request GET /posts, they will get a weird 405 page, which was likely not customized to show as nicely as their 404 page one. I would consider that to be a breaking change.

GET and HEAD are [mandatory HTTP methods](https://tools.ietf.org/html/rfc7231#section-4.1), a server must not ever respond to a GET or HEAD request with a 405. 

If an application violates HTTP then I don't think it's reasonable to expect dependencies to support its use case. 

Not implementing this is essentially favouring supporting a scenario that is not valid HTTP (and for which I cannot think of a potential use case) over one that is valid HTTP and does have obvious use cases in APIs.

My 2 cents.

**Comment by stevegraham** [comment]
> Thanks again for taking the time to read this. I don't want to annoy anyone, I just feel this is not bikeshedding but something which should be default behavior rather than in an external library.

P.S. I feel the same. I personally hate religious REST wars 🤢.
