### ISSUE TITLE
µWS Transport Adapter

### ISSUE THREAD

**Issue by joshua1** [phoenixframework/phoenix#2021]
@chrismccord Is it possible to have a uWebsockets (https://github.com/uWebSockets/uWebSockets)  Transport Adapter. As this has been said to significantly outperform websockets (ws) With usage in products like deepstream.io

**Comment by chrismccord** [comment]
We have shown that cowboy's websocket handler can support 2+ million connections on a single server, with 10k conn/s arrival rate. Also, the raw cowboy websocket handler would exceed these numbers since the 2M- 10k/s numbers include Phoenix channel overhead. I see no compelling reason to explore uWebSockects, which is a solution outside of beam. In the future, please send feature requests to the mailing phoenix-core mailing list. Thanks!
