### ISSUE TITLE
escript over archive

### ISSUE THREAD

**Issue by LTheGreats** [phoenixframework/phoenix#2055]
I believe that instead of installing a archive to make a new phoenix project
(mix phoenix.new)
people running on elixir 1.4.0 and above should install a escript to make
a new phoenix project.
It would look something like this:
  phoenix new foo --database bar
There are two reasons why to do this.
1. It looks better
2. If you install it as an archive you cannot make a mix project that has
a module name that is the same as one in the phoenix_new archive
because mix always loads the modules in the phoenix_new archive

**Comment by josevalim** [comment]
We plan to do this eventually but, because the escript is specific to Elixir v1.4.0, we will wait until Phoenix is 1.4.0 only. For now, we will need to write code that supports earlier Elixir versions.

**Comment by LTheGreats** [comment]
:+1:

**Comment by bamorim** [comment]
@josevalim sorry for bringing this question up again, but after reading more about archives and escripts I started wondering why `phx_new` was a archive instead of a escript and I found this issue.

Right now Phoenix requires 1.9, but it is still using an archive instead of an escript.

Is moving to an escript something you still think makes sense?

Thanks.

**Comment by josevalim** [comment]
Honestly, I am not sure if it is worth it. They are mostly equivalent to our use case, given that the `phx_new` package only has Mix tasks in it and installing escripts have one additional step in that they require the escripts folder added to the path, so it would be something else for newcomers to do when getting started.
