### ISSUE TITLE
conn.private values are nil when response is 500

### ISSUE THREAD

**Issue by johnkelly** [phoenixframework/phoenix#2056]
I'm logging the `conn.private.phoenix_controller` and `conn.private.phoenix_action` values in a custom Plug Logger (useful for easily distinguishing where the error occurred vs. looking at HTTP methods and paths) and I've noticed that for most responses both values are non-nil which makes tracking things on a controller#action basis very easy.

However, for 404 and 500 response statuses, these values are nil. A 404 makes sense to be nil, but I'm thinking for a 500 it might be useful to have these values if they are available be non-nil in the connection for error debugging and logging purposes.

https://github.com/phoenixframework/phoenix/blob/9e7f8bd0c16e3ecee1d5c893125d4ba3a890e715/lib/phoenix/controller/pipeline.ex#L23-L25

### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: Mac 10.11 / Ubuntu 14.04

**Comment by josevalim** [comment]
When there is an exception, we lose all the information stored in the
connection, because that information was set downstream and not in the copy
of the connection we have where we are doing the exception handling.

Although that's a consequence of immutability, it is also a good design
rule. What if the error is being caused exactly due to a bogus value in
private? Wouldn't Passing this value to the exception handling code
possibly make it fail too?

So while there is no way to change this behavior, I would argue we
shouldn't not even if we could.
