### ISSUE TITLE
place phoenix_new archive on hex

### ISSUE THREAD

**Issue by LTheGreats** [phoenixframework/phoenix#2058]
After phoenix supports only elixir v1.4 and above the phoenix archive should be pushed to hex.

I have two reasons why.
1. The archived version of phoenix_new would be on hex, so there would be more space on the repo.
2. The install command would look nicer.

**Comment by josevalim** [comment]
Again, we will focus on those workflows once Elixir v1.4 is out for a longer period of time and Phoenix requires it. It doesn't make sense to focus on such now because we won't able to update the guides, learning resources, etc. It will only help a handful of users that know such is possible. Therefore we will focus on more important issues for now.
