### ISSUE TITLE
Not right structure for static assets

### ISSUE THREAD

**Issue by loguntsov** [phoenixframework/phoenix#2130]
I made standard project from "mix phoenix.new".
The wizard placed static assets there: web/static
but code of Plug.Static requires assets as: {app_build_folder}/priv/static
So it means wizard should make simlink for this direction.
And also when i asked /robots.txt, it finds this file in /priv/static/robots.txt
But wizard placed root files in /assets folder.

By the way: I uses phoneix app as sub_app of umbrella project.

**Comment by josevalim** [comment]
@loguntsov which Phoenix version are you using? Did you use `mix phoenix.new` or `mix phx.new`? If you have used `mix phoenix.new`, you need to use `mix phoenix.gen.*` and so on for the remaining tasks.

Other than that, we put files on `web/static` and invoke the Brunch tooling that will effectively copy it to "priv/static". So it is expected for them to be on `web/static` rather than `priv/static`.

**Comment by loguntsov** [comment]
I have:
 {:phoenix, 'Productive. Reliable. Fast. A productive web framework that\ndoes not compromise speed and maintainability.\n', '1.2.1'},

And yes i used "mix phoenix.new" as says in guide:
http://www.phoenixframework.org/docs/up-and-running

And i have this message for runtime:
[error] Could not start node watcher because script "/home/begemot/erl/dofus_repo/apps/dofus_web/node_modules/brunch/bin/brunch" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "npm install".

but your guides says:

> 
> Node is an optional dependency. Phoenix will use brunch.io to compile static assets (javascript, css, etc), by default. Brunch.io uses the node package manager (npm) to install its dependencies, and npm requires node.js.
> 
> If we don't have any static assets, or we want to use another build tool, we can pass the --no-brunch flag when creating a new application and node won't be required at all.

I didn't pass --no-brunch first time.
And i have some mistakes with my system (Ubuntu 14.04) to install brunch.io
so have no installed brunch.io.
But expects, if system knows that brunch.io is not installed, it should work right any way.

Where am i not right ?

**Comment by loguntsov** [comment]
By the way, you took can determine is Brunch.io installed or not, so don't need pass --no-brunch parameter.

And how i can fix something to don't use brunch.io in my existed project ?

**Comment by josevalim** [comment]
If you don't want to use brunch, you need to put your asset files directly inside `priv/static` and then remove `priv/static` from `.gitignore` if it is listed there by any chance.

I would recommend you do run `mix phoenix.new your_app --no-brunch` and copy the files it puts in priv/static to your project.

> By the way, you tool can determine is Brunch.io installed or not, so don't need pass --no-brunch parameter.

I don't think we want to do that because, even if Brunch is not available, we want to push users towards using it as it will lead to a better user experience.

I will close this issue as it doesn't seem to be a bug in Phoenix but feel free to ask questions and we will be glad to answer!

**Comment by loguntsov** [comment]
Thanks. But i prefer to get information on my question:
how i can switch procject using of brunch.io manually ? because i don't like use Phoenix as black box. I want to know all aspects of this software. I  think it can be helpful for you too.

Anyway thanks for your time and help.

**Comment by loguntsov** [comment]
You can point me to some code. I understands of Elixir code and have much experience with Erlang.

**Comment by josevalim** [comment]
If you don't want to use brunch, all you need to do is to remove
web/static, remove the mention to brunch in your config/dev.exs and put
files you want to serve directly in priv/static.

Is that what you want?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by loguntsov** [comment]
Seems yes, but why i have 

> [error] Could not start node watcher because script "/home/begemot/erl/dofus_repo/apps/dofus_web/node_modules/brunch/bin/brunch" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "npm install".

how i can disable it for my project ? seems these is some flag for this feature.

**Comment by josevalim** [comment]
I have answered in my previous comment. :) you have a configuration
mentioning brunch in your config/dev.exs. Just remove it and you should be
good to go.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by loguntsov** [comment]
I'm sorry, yes. :)

**Comment by loguntsov** [comment]
Thank you.
