### ISSUE TITLE
mix phx.new.web generated mix.exs config references itself

### ISSUE THREAD

**Issue by moomerman** [phoenixframework/phoenix#2143]
Elixir 1.4.2
Phoenix 1.3.0-rc0

### Expected behavior

```
$ mix phx.new /tmp/hello --umbrella --no-ecto --no-brunch --no-html
# Y to install dependencies
$ mix phx.new.web /tmp/hello_umbrella/apps/hello_api --no-ecto --no-brunch --no-html
# Y to install dependencies
```

should work

### Actual behavior

After choosing to install the dependencies for the web-only app above:

```
Fetch and install dependencies? [Yn] Y
* running mix deps.get
* error command failed to execute, please run the following command again after installation:

    mix deps.get
* running mix deps.compile
* error command failed to execute, please run the following command again after installation:

    mix deps.compile

We are all set! Run your Phoenix application:

    $ cd hello_api
    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server
```

following the instructions:

```
$ cd /tmp/hello/hello_umbrella/apps/hello_api
$ mix deps.get
warning: redefining module HelloApi.Mixfile (current version defined in memory)
  /private/tmp/hello_umbrella/apps/hello_api/mix.exs:1

Error while loading project :hello_api at /private/tmp/hello_umbrella/apps/hello_api
** (Mix) Trying to load HelloApi.Mixfile from "/private/tmp/hello_umbrella/apps/hello_api/mix.exs" but another project with the same name was already defined at "/private/tmp/hello_umbrella/apps/hello_api/mix.exs"
```

This is because the generated mix.exs file for the new web-only `hello_api` app references itself as a dependent in_umbrella app, instead of `hello` in this example:

```
  defp deps do
    [{:phoenix, "~> 1.3.0-rc"},
     {:phoenix_pubsub, "~> 1.0"},
     {:gettext, "~> 0.11"},
     {:hello_api, in_umbrella: true},
     {:cowboy, "~> 1.0"}]
  end
```

I had a quick look and couldn't see an obvious fix, happy to have a go if you can provide guidance.

**Comment by chrismccord** [comment]
Thanks for the report! I'll take a look this evening.

**Comment by dweinand** [comment]
The issue is that when `phx.new.web` is run on it's own `web_app_name` and `app_name` are identical, which causes the [template mixfile](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_umbrella/apps/app_name_web/mix.exs#L42) to add a dependency to itself.

Conceptually, there's a problem here. When creating a new web app on it's own, we have no way of knowing what the app name should be as we do in the umbrella.

I see two ways of handling this:

1) Don't try to create the dependency when running outside of the umbrella generator, and leave it as an exercise for the user.

2) Assume that the one main app, and multiple web apps is common enough pattern to support by default (web, api, admin, etc.) and provide a way to specify both the main app name and the web name.

You could do that by either allowing both the web and app names to be specified separately, or always specifying the app name and allowing a configurable suffix to be used to generate the web app name.

If you did go down one of those routes, you could potentially make use of it in the umbrella as well to allow users to override the default `_web` namespacing.

**Comment by moomerman** [comment]
Also looks like a related issue with the generated test support helpers (`channel_case.ex`, `conn_case.ex`) referencing `HelloAdmin.Repo` instead of `Hello.Repo` (this is when the --no-ecto flag isn't used)
