### ISSUE TITLE
mix phx.gen.* not compatible with --no-ecto option

### ISSUE THREAD

**Issue by fertapric** [phoenixframework/phoenix#2145]
First off, congratulations on the great job you are doing, keep pushing! 🙇 

After reading ["Phoenix 1.3.0-rc.0 released"](https://groups.google.com/forum/#!topic/phoenix-core/CFMQvcR5t6M) on the phoenix-core mailing list, I was eager to test the new generators. Also, the new "bounded context" philosophy is great, and I think your are doing an amazing job teaching newcomers (like me) how to organize (and think!) about their code.

However, I had quite a few doubts about the use of `Ecto.Changeset` for error responses (i.e. `iex> create_user(user, %{field: bad_value}) # => {:error, %Ecto.Changeset{}}`) because it felt like a [leaky abstraction](https://en.wikipedia.org/wiki/Leaky_abstraction). To back up my argument:

* at some point, part of the application could be rewritten in other language or extracted to an external service. In that case, ideally, the _context_ interface should remain unchanged but the implementation would replace Ecto with HTTP requests to the new service. Unfortunately, the new generators use `Ecto` as part of the contract provided by the interface of each _context_.
* as for as I know, Ecto is the default mechanism to talk to the database but it's not a hard requirement. That's why you can run `mix phoenix.new` (or the new `mix phx.new`) with the `--no-ecto` flag. However, as this issue explains, the code generated is not valid as it contains references to Ecto.

### Environment

* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps): 1.3.0-rc.0
* NodeJS version (node -v): v4.5.0
* NPM version (npm -v): 4.0.3
* Operating system: macOS Sierra 10.12.3

### Expected behavior

I'm not sure what should be the expected behavior, sorry.

### Actual behavior

After creating a new project with `--no-ecto` option, the new generators still contain references to `Ecto.Changeset`, `Ecto.Query` and `MyApp.Repo`.

Steps to reproduce:

```
mix phx.new my_app --no-ecto
cd my_app
mix phx.gen.html Accounts User users email:string:unique
```

For example, `MyApp.Accounts` looks like:

```elixir
defmodule MyApp.Accounts do
  @moduledoc """
  The boundary for the Accounts system.
  """

  import Ecto.{Query, Changeset}, warn: false
  alias MyApp.Repo
  
  ...

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  ...

end
```

**Comment by bryannaegele** [comment]
@fertapric Somebody may wish to correct me, but the generators are only meant to be a learning aid, not for scaffolding. Chris and others have spoken on this quite a bit in the past year, most recently at [Lonestar ElixirConf](http://confreaks.tv/events/lonestarelixir2017)

The files generated are built from templates and the idea is to be able to learn a way (not *the* way). It's reasonable to assume then that the generators would therefore only handle the use case of aiding learning in the common context of using Ecto. Perhaps if you approach Phoenix and generators from the standpoint of a learning aid and not scaffolding for production usage (in which case you'd have a fair point) then the concerns are negated.

If you think there's something confusing in the docs or some new material that could help clarify this aspect to newcomers, I'm sure the PR would be welcomed. I supposed it would also be possible to add a check for Ecto being installed to the generator tasks and print a warning.

Hope that helps.

**Comment by josevalim** [comment]
> However, I had quite a few doubts about the use of Ecto.Changeset for error responses (i.e. iex> create_user(user, %{field: bad_value}) # => {:error, %Ecto.Changeset{}}) because it felt like a leaky abstraction. 

I don't agree that's the case. The context is returning data structures and it is ok to depend on data structures from external libraries that are shared across contexts. For example, if a context return a `%URI{}` struct, would see any problem in it? Or a Joken struct from elsewhere?

The only reason people may think it is a leaky abstraction is because Ecto can also be used for database access. However, `Ecto.Changeset` is not related to a repository. You can use changesets to validate, cast and manipulate any Elixir struct (you can read more about schamaless changesets). It should be seen as an auxiliar data structure.

> as for as I know, Ecto is the default mechanism to talk to the database but it's not a hard requirement.

If you use the `--no-ecto` flag, then you are going out of the learning path, and it is no longer guaranteed the generators will work. We are going to introduce a `--no-context` flag to generators that will allow you to still move forward but then you are expected to fill in the blanks.

We will make sure those notes are included in the documentation. Thank you!

**Comment by fertapric** [comment]
> I don't agree that's the case. The context is returning data structures and it is ok to depend on data structures from external libraries that are shared across contexts. For example, if a context return a %URI{} struct, would see any problem in it? Or a Joken struct from elsewhere?

You are right :)

> The only reason people may think it is a leaky abstraction is because Ecto can also be used for database access. However, Ecto.Changeset is not related to a repository. You can use changesets to validate, cast and manipulate any Elixir struct (you can read more about schamaless changesets). It should be seen as an auxiliar data structure.

Exactly. That was my case.

I see the Ecto project could be seen now as data-casting + validation library and a query + persistence library, do you have plans to split it (in a Active Model / Active Record fashion, relatively speaking)?

**Comment by thepeoplesbourgeois** [comment]
Hmm... Well, that complicates my use-case, but I think I have a workaround.

I'm working on porting an experimental app using Python, Flask, and MongoDB into a more stable product. I'm a Rails developer by trade, and it's been straightforward (albeit some-assembly-required) to spin up a new `Rails 5.0.0.0` app without a default database, and then to hook it up to Mongo through the `mongoid` gem. I really took this for granted, but Rails' middlework stack detects the gems I'm using (`mongoid`, `sass-rails`, `coffee-rails`, and `slim-rails`), and invokes those gems to inject the Mongo document schema into my model file, as well as to generate corresponding .scss, .coffee, and .html.slim files

I've also been using the opportunity to see how to get a parallel app up and running in Phoenix, and guess I'd assumed that the highly-touted Plug framework would be similarly leveraged to ensure that `mix` always does the right thing. But, trying to connect to Mongo in a `mix phx.new foo` project **without** the `--no-ecto` flag generated configuration files and flags for Postgres, which meant that I'd need a running Postgres instance to start my server, even though all the data is stored in Mongo. Conversely, I had a lot more success connecting to a Mongo instance in a `mix phx.new foo --no-ecto` project. Alas, trying to start a server in this scenario also fails, this time because my application isn't aware of what an `Ecto.Changeset` is... 

I think I'm going to need to create two projects to create my project: One that will let me download the appropriate dependencies for `Ecto.Changeset`, `Ect.al` (pardon the pun), and then one that will let me connect the application to MongoDB.

Glad I found this thread! 😅
