### ISSUE TITLE
Inject context tests

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#2158]
### Environment

* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps):1.3.0-rc.0
* Operating system: OSX Sierra

### Expected behavior

Each new resource does get corresponding context tests generated.

### Actual behavior

When generating a new schema (phx.gen.html) as part of an already existing context the context.ex module does get new functions injected, but the corresponding context_test.exs is not extended.

**Comment by josevalim** [comment]
@chrismccord we should also use the opportunity to wrap each generated resource in `context_test.exs` in a `describe` block.

**Comment by chrismccord** [comment]
I intentionally left this out as a detail left to the user, since they would have already had a context test generated with examples of best practices. It will be more complicated for us to inject additional tests, especially since we have the `fixture` defs, which would generate warnings if we simply appended the new contents at the bottom of the module. I am -1 on this unless @josevalim thinks it's worth supporting.

**Comment by josevalim** [comment]
@chrismccord I believe we should keep parity and inject the tests here too. However it is also unclear to me how to tackle the fixtures issue. We may need to resort to `post()` instead of `fixture(:post)` or generate the fixture function with a header, such as `def fixture(name, attrs \\ %{})` and try to match on the header for injection.
