### ISSUE TITLE
Duplicate Ecto tasks run in umbrella project

### ISSUE THREAD

**Issue by martinmalloy** [phoenixframework/phoenix#2234]
When I run tasks such a mix ecto.create then the task is being run for both the app and the web app resulting in the operation being run twice

### Environment

Phoenix 1.3 rc1

### Expected behavior

`mix ecto.create`

`==> app`
`The database for App.Repo has been created`

### Actual behavior

`==> app`
`The database for App.Repo has been created`

`==> web`
`The database for App.Repo has already been created`

**Comment by josevalim** [comment]
Yes, both are configured to run tasks because sometimes you want to run those tests in isolation and you still want each of them to run migrations, create the database, etc. This is an intended side-effect. For example, if they used different databases, different databases would be migrated, which is what we want. If it is the same, then you just get a minor inconvenience. :)
