### ISSUE TITLE
`mix phx.new project_name` gets stuck at asset build and compilation step

### ISSUE THREAD

**Issue by egeersoz** [phoenixframework/phoenix#2264]
### Environment

* Elixir version (elixir -v): 1.4.1
* Phoenix version (mix deps): 1.3.0-rc.0
* NodeJS version (node -v): 7.9.0
* NPM version (npm -v): 4.2.0
* Operating system: Ubuntu 16.04 (fresh install)

### Expected behavior

Running `mix phx.new project_name` should create all files, download and compile dependencies, install and compile node modules, then return to the command line.

### Actual behavior

Running `mix phx.new project_name` gets stuck. Output

```
...
* creating project_name/assets/static/images/phoenix.png
* creating project_name/assets/static/favicon.ico

Fetch and install dependencies? [Yn] Y
* running mix deps.get
* running mix deps.compile
* cd assets && npm install && node node_modules/brunch/bin/brunch build
## stuck here, nothing happens, no console output
```

I waited for about an hour, then quit using ctrl-c. Then I followed the steps manually.

* `mix deps.get` said all dependencies were already up to date
* did `mix deps.compile`
* went into the assets folder and did `npm install`, everything was already installed
* ran  `node node_modules/brunch/bin/brunch build` and got the output: `info: compiled 6 files into 2 files, copied 3 in 944 ms`

So if there was some sort of error that was thrown when I ran `mix phx.new project_name`, I didn't run into it. The command just failed silently, it seems.

Sorry if this has already been reported.

**Comment by chrismccord** [comment]
No worries, but this appears to be an obscure `npm install` issue that we won't be able to diagnose. You did the right next step by running the commands manually again and it sounds like things are now working so glad you're up to speed! Thanks for reporting!

**Comment by francocatena** [comment]
I just run into the same issue, the manual steps work as expected.

## Environment

Elixir version (elixir -v): 1.4.5
Phoenix version (mix deps): 1.3.0-rc.2
NodeJS version (node -v): 8.1.2
NPM version (npm -v): 4.6.1
Operating system: ArchLinux

**Comment by Zafira** [comment]
@chrismccord, I don't think this is an npm error? I think it's getting hung up on deps.compile because when I un-quieted the commands, I saw a prompt from mix asking to install rebar. As this can never be responded to, this Task will never return.

Running `mix local.rebar` allowed the project creation to complete normally.

**Comment by josevalim** [comment]
Great point @Zafira. We need to think about a solution for this.

**Comment by shankardevy** [comment]
@josevalim, I can also confirm that this issue is due to missing `rebar`.


![image](https://user-images.githubusercontent.com/2011812/28097882-8ffb54fa-66d0-11e7-95f4-bdf5d1ec511b.png)

This line in the installer https://github.com/phoenixframework/phoenix/blob/master/installer/lib/mix/tasks/phx.new.ex#L137 is compiling the downloaded dependencies during `mix phx.new`. 
Since `rebar` is required during the compilation time, we have two options:

1. Force install `rebar` during `mix phx.new`
2. Skip compiling during `mix phx.new` (since `mix phx.server` compiles the code if it's not already compiled, this can still be an option).

**Comment by nathanhornby** [comment]
I seem to be coming across a similar issue, after running `mix phx.new projectName --no-ecto` I get to the installing dependencies step and then the process just gets stuck on `* running mix deps.compile`.

Looking at the original report I did the same but:

- mix deps.compile - things compiled
- npm install - things started to install but then immediately after installing the babel preset (something I remember being an issue the last time I went through this process) an an error threw:

```
events.js:165░░░░░░⸩ ⠙ extract:querystring-es3: sill extract indexof@0.0.1
      throw er; // Unhandled 'error' event
      ^
```

I'm guessing that's what tripped it. Any ideas?

**Comment by kiatng** [comment]
I'm following the official guide trying to install the _hello_ sample in Windows Subsystem for Linux (WSL) - Ubuntu 18.04. The install stucks at `running mix deps.get`:

```
kiatng@win10:~/phoenix$ mix phx.new hello
* creating hello/config/config.exs
* creating hello/config/dev.exs
* ...
* creating hello/assets/static/images/phoenix.png
* creating hello/assets/static/favicon.ico

Fetch and install dependencies? [Yn] Y
* running mix deps.get
^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Ckiatng@win10:~/phoenix$ mix deps.get
** (Mix) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
```

Is that a file path issue? I'm a total noob.
