### ISSUE TITLE
Context refers to Web Namespace when created from umbrella app

### ISSUE THREAD

**Issue by lauraannwilliams** [phoenixframework/phoenix#2270]
### Environment

* Elixir version (elixir -v): Elixir 1.4.2
* Phoenix version (mix deps): phoenix 1.3.0-rc.1
* NodeJS version (node -v): v7.6.0
* NPM version (npm -v): 4.1.2
* Operating system: MacOS Sierra 10.12.4

### Expected behavior
When creating a new context in an umbrella app, the generated files should have no errors. 

### Actual behavior

When creating a new context, the repo is aliased as `alias AppName.Web.Repo`. However, in an umbrella app, the default repo is not under the Web namespace, but so the correct code would be
`alias EctoAppName.Repo`.  

Alternatively a repo in the Web Namespace could be set up if one doesn't exisit, but that feels like it would go against separation of concerns. 

### To Reproduce

1. Create standard umbrella app
`mix phx.new test --umbrella --no-html`

2. cd to apps/test_web folder 

3. Run context generator, then mix compile

```
$ mix phx.gen.context Blog Post posts title:string content:text
* creating lib/test_web/blog/post.ex
* creating priv/repo/migrations/20170428191015_create_web_blog_post.exs
* creating lib/test_web/blog/blog.ex
* creating test/blog_test.exs

Remember to update your repository by running migrations:

    $ mix ecto.migrate

$ mix compile
Compiling 10 files (.ex)
warning: function Test.Web.Repo.all/1 is undefined (module Test.Web.Repo is not available)
  lib/test_web/blog/blog.ex:21

warning: function Test.Web.Repo.get!/2 is undefined (module Test.Web.Repo is not available)
  lib/test_web/blog/blog.ex:38

warning: function Test.Web.Repo.insert/1 is undefined (module Test.Web.Repo is not available)
  lib/test_web/blog/blog.ex:55

warning: function Test.Web.Repo.update/1 is undefined (module Test.Web.Repo is not available)
  lib/test_web/blog/blog.ex:73

warning: function Test.Web.Repo.delete/1 is undefined (module Test.Web.Repo is not available)
  lib/test_web/blog/blog.ex:89

Generated test_web app
```

4. Changing `Test.Web.Repo` to `Test.Repo` manually removes this error.

### Other Notes

The generated directory structure is also unexpected to me. I'd thought the models & context would go into ecto app folder ( apps/test ) and not the web ( apps/test_web ) folder to encourage people to use the apps/test directory for database logic.

**Comment by chrismccord** [comment]
Can you try phoenix master? This should be already supported in master

**Comment by chrismccord** [comment]
You can point your phoenix dep at GitHub `{:phoenix, github: "phoenixframework/phoenix", override: true}`, then run `mix deps.update` and try out the latest context generators

**Comment by lauraannwilliams** [comment]
I thought I was on master tbh. I followed these instructions https://github.com/phoenixframework/phoenix/blob/master/installer/README.md

However, I retried this in the installer folder as per the readme here: https://github.com/phoenixframework/phoenix

AND added the --dev flag

And the issue does not exist. 

I'm guess that --dev flag is the key :)

**Comment by chrismccord** [comment]
ah yes, without the dev flag the generators point to the latest stable release. Glad you got things sorted out!

**Comment by lauraannwilliams** [comment]
Note on this: you can't use the --dev flag outside the installer directory, so the 

"To create projects outside of the installer/ directory, add the latest archive to your machine by following the instructions in installer/README.md"  won't allow you to use master.

**Comment by liz-mars** [comment]
@lauraannwilliams and I were looking for a way of organizing git repos where we use the latest possible version of Phoenix.  This is what I came up with:

*Method for creating a project using master and using phx.new rc1 (as of this writing).*
 
`#set up our environment
mkdir foo #where foo is project name
cd foo 
git init
#add phoenix as a dependency (needed for node)
git submodule init
git submodule add https://github.com/phoenixframework/phoenix
cd phoenix/installer
#uninstall old user-wide phx
mix archive.uninstall <current phoenix version> #you can get a list of installed packages with 'mix archive.uninstall blahblahblah' where 'blah...' doesn't exist on your system
mix run
mix phx.new --dev --umbrella foo #create app 
#install phx (1.3.0rc1)
MIX_ENV=prod mix archive.build
mix archive.install
#move foo_umbrella to its own part of your repo 
mv foo_umbrella ../..
#We have to do two edits to deps. The first is what Chris recommends, above
cd ../../foo_umbrella/apps/foo_web
cp mix.exs /tmp/mix.exs.old
sed 's/{:phoenix, path: "\(.*\)", override: true}/{:phoenix, github: "phoenixframework\/phoenix", override: true}/' /tmp/mix.exs.old > mix.exs
#Now fix the JS deps, following the same pattern
cd assets
cp package.json /tmp/package.json.old
sed 's/"phoenix": "file:\(.*\)"/"phoenix": "file:..\/..\/..\/..\/phoenix\/"/' /tmp/package.json.old > package.json
#save our work!
git add ../../../
git commit -am "initial commit"
npm install #I prefer 'yarn' but wevs
cd ../../../  #go to foo_umbrella
mix deps.get #get ready
#now, do the thing that was problematic before
mix phx.gen.context Blog Post posts title:string content:text && mix ecto.migrate`

When I run the above, I get an environment where 'phx.*' commands work everywhere, and I can no longer reproduce the reported errors. :) Note: the phoenix repo remains a git submodule dependency because node requires its package.json. 

Hope this helps. Can make into a gist if this is helpful.
