### ISSUE TITLE
Better use of the generated FallbackController.

### ISSUE THREAD

**Issue by r3oath** [phoenixframework/phoenix#2271]
When using the mix task `phx.gen.json` for example, the FallbackController is generated along with functions such as `call(conn, {:error, :not_found})`. However, if you try to visit a generated resource with a non-existent `id` the current behaviour simply throws an exception because of the use of `Repo.get!/2`. 

Would it perhaps make more sense to generate the respective code such that the API edge uses `def get_post(id), do: Repo.get(Post, id)` for example, and inside of the controller do:

```elixir
def show(conn, %{"id" => id}) do
  case Posts.get_post(id) do
    nil -> {:error, :not_found}
    post -> render(conn, "show.json", post: post)
  end
end
```

If this seems like a good idea I'm happy to create a pull request that alters the respective templates. Naturally you would also expect similar behaviour from other functions such as `update` if you're trying to update a record which does not exist.

### Environment

* Phoenix version (mix deps): 1.3.0-rc

**Comment by josevalim** [comment]
@r3oath the current mechanism is by design. There are many errors that can appear in a request and we want to focus on flow control on those that appear through regular using of the application, say sending invalid data through an API. It is common for a request to maybe miss some information or poorly format some data.

On the other, record not founds usually mean errors, either in the client of the API or maybe by you sending invalid references. Those are not supposed to happen on regular workflows, so they are a kept as exceptions, because they are meant to be exceptional. It is the same discussion between `File.read` and `File.read!`.

Thank you for the proposal and the interest in sending a PR though! :heart:

**Comment by r3oath** [comment]
Hi @josevalim, appreciate the prompt follow-up 👍 

I still don't feel entirely convinced however, and forgive me if that's just my misunderstanding of Phoenix's approach. 

If I was using an application and requested `example.com/api/books/12390123` and a book with the ID `12390123` did not exist, under normal circumstances I would expect to see a 404/not-found? However, with Phoenix it seems we're getting an exception crashing the process handling the request.

I fully understand the nature of everyones applications will differ, but for functionality out-of-the-box, the current behaviour seems a bit bizarre to me.

Additional reference: http://jsonapi.org/format/#fetching-resources-responses-404

**Comment by josevalim** [comment]
> If I was using an application and requested example.com/api/books/12390123 and a book with the ID 12390123 did not exist, under normal circumstances I would expect to see a 404/not-found? 

Yes, you should be seeing a 404 in production. In development it raises an error, exactly to make those situations easier to debug and understand, because they should be exceptional.

**Comment by r3oath** [comment]
> Yes, you should be seeing a 404 in production.

Ah, apologies then, as I mentioned perhaps it was my understanding of Phoenix. 

Where exactly does the magic happen that when in production those `Ecto.NoResultsError` exceptions are handled and returned as 404's?

**Comment by josevalim** [comment]
There is a Plug.Exception protocol that converts exceptions into the proper http status. The customization can be done by using the ErrorView in your app.
