### ISSUE TITLE
Sockets in forwarded applications

### ISSUE THREAD

**Issue by mgwidmann** [phoenixframework/phoenix#2276]
@chrismccord As we spoke about at elixirconf eu, wanted to submit this issue since it seems you may be bumping up against this in the future.

### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.2.3
* NodeJS version (node -v): 7.4.0
* NPM version (npm -v): 4.0.5
* Operating system: OSX

When it comes to forwarded modules, all works fine for http requests, but since it seems its not possible to forward to endpoints (only routers or other plugs) and so therefore real time functionality does not work in forwarded endpoints since there is no endpoint module.

To work around, the host application must add the socket to their endpoint.

### Use Case

I have a hex library [flames](https://github.com/mgwidmann/flames), which is added to the router via  `forward "/errors", Flames.Web`. As you can see in the last step of the readme, it requires adding `socket "/errors/socket", Flames.UserSocket` to the endpoint.

### Testing

The flames application has a `dummy` Phoenix app in which Flames is available. Since Flames is a dependency in this situation however, code reloading will not work.

**Comment by OvermindDL1** [comment]
In my opinion another application should not necessarily be adding a new socket, though they could for the general case, but such as at my job we can only use one websocket per page max, so there should always be the option of adding a 'channel' from the other library (say, flames) instead of an entire socket.

**Comment by mgwidmann** [comment]
Well in the case of this package, or the metrics package @chrismccord spoke about at elixirconf, they'd be taken to an entirely new page with a completely different layout. Therefore, whatever other sockets you have for other pages of the site wouldn't be in use anymore. Besides, I disagree that you should never have two `socket` calls in your endpoint as I've done many times to have one `UserSocket` and one `AdminSocket`, since they have different join semantics they naturally need each their own endpoints to join to.

**Comment by OvermindDL1** [comment]
> Well in the case of this package, or the metrics package @chrismccord spoke about at elixirconf, they'd be taken to an entirely new page with a completely different layout. Therefore, whatever other sockets you have for other pages of the site wouldn't be in use anymore. Besides, I disagree that you should never have two socket calls in your endpoint as I've done many times to have one UserSocket and one AdminSocket, since they have different join semantics they naturally need each their own endpoints to join to.

That should entirely remain an option yes, however some corporate networks (like the one I deal with at work) only allows one websocket per page, so there needs to be a pattern to have many projects channels share a single socket.

**Comment by mgwidmann** [comment]
Just to bring up another use case, I see that the https://github.com/shinyscorpion/wobserver package also does the same thing. I agree though, something cleaner should be allowed. 

It would be nice (though not sure how practical) if forwarding to an Endpoint worked as well as a plug. I feel like that would be the most obvious solution and would allow the host application to do things like apply their own plugs for authentication ect prior to reaching the third party forwarded endpoint.

**Comment by josevalim** [comment]
It is definitely not practical because plugs and websockets are handled at very different levels. It would only be possible if we implemented the whole websockets upgrade directly from plug. But it is a lot of work and there is a lot of more important work ahead of it. Until then, I can't see a better solution besides declaring both socket and plug forwarding.

**Comment by michalmuskala** [comment]
Using something like wobserver still preserves a single websoket connection, though - you are either at the application page using the application socket or at the wobserver page using the wobserver socket - you don't use both at the same time.

I would imagine this to be the case with most "pluggable" things out there.

**Comment by OvermindDL1** [comment]
> I would imagine this to be the case with most "pluggable" things out there.

Except there are things like [Drab](https://hex.pm/packages/drab), which does use a socket on each user page.

**Comment by chrismccord** [comment]
Thanks for opening the issue @mgwidmann . I agree the best way forward in the immediate future is for libraries like the upcoming phoenix_metrics and Flames to support separate socket mounts in the endpoint, in addition to their route definitions. As mentioned, a restriction of a single ws connection isn't a concern for these usecases since they are separate pages outside the main app. For cases where socket mounts need to integrate w/ existing apps and abide by single connection restrictions, a channel definition in an existing UserSocket is the way to go and libraries will need to handle this on a case by case basis for what they support. Longer term we can evaluate adding websocket upgrades to plug itself, but as José said, this is a long ways off and we have other priorities in the meantime. Having one extra step for the user to add a socket mount is a good tradeoff.

**Comment by mgwidmann** [comment]
I agree. Just wanted you to be aware of the issue with your upcoming phoenix_metrics package as likely people will ask about it. Long term it is best if plug did handle it but I understand as this isn't a big deal at the moment.
