### ISSUE TITLE
native webpack2 support in elixirphoenix

### ISSUE THREAD

**Issue by radosch** [phoenixframework/phoenix#2287]
Hi Firebirds,

after making some experiments with webpack, I would purpose to replace brunch with webpack2.
as the standard pipeline.
What do you think about this?

**Comment by ryanwinchester** [comment]
I think webpack is a better solution than brunch because it's use is pretty ubiquitous

That being said, I don't think it matters, because it's [so easy to switch out brunch for webpack](https://ryanwinchester.ca/posts/replacing-brunch-with-webpack-1-in-phoenix), or whatever js build tool you want that it's a very minor issue. And even though it feels like (to me, at least) that most of the js community is using webpack, there are many other tools people are using, and because the community is so large, that is a lot of people with their own preferences.

**Comment by OvermindDL1** [comment]
Honestly I'd push for no brunch/webpack/etc and just use npm as the build system straight (there is no purpose in things like webpack considering npm can already do it all natively) since npm 'is' a build system after all.  But for now as @ryanwinchester said it is so so very easy to swap it out as it is that there is no reason to break all the old tutorials and documentation and all.

**Comment by josevalim** [comment]
The issues tracker is not the place to propose features. Also, we should expect the Phoenix team to take decisions based on a wide-array of information. So if you want to argue for webpack2, feel free to send a proposal to the mailing list and include examples, assess the quality of webpack2 documentation, and the getting started experience. When we did this a couple years back, webpack seemed the best technically but the poorer documentation wise.
