### ISSUE TITLE
mix phoenix.new -> package.json: javascript-brunch is deprecated

### ISSUE THREAD

**Issue by steakknife** [phoenixframework/phoenix#2305]
Phoenix 1.2.4

https://github.com/brunch/javascript-brunch

Also, the included brunch is over a year old.

**Comment by webdeb** [comment]
Seams like you are using an outdated phoenix installer, since this was already fixed here: https://github.com/phoenixframework/phoenix/commit/6a7392ee7245e8266e67f3365ee8eab1050da8c0

**Comment by steakknife** [comment]
"Seems?" Phoenix 1.2.4, which is from yesterday.

**Comment by webdeb** [comment]
Well, sorry for the gramma mistake.. Seems you are (like me) just starting with phoenix, I suggest to use the newer 1.3.0-rc installer 
`mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez`

**Comment by steakknife** [comment]
Look at the release. It contains the old file. https://github.com/phoenixframework/phoenix/blob/fbb8f6004615b1c71e03caf68871d056d3cc94e9/installer/templates/static/brunch/package.json

**Comment by webdeb** [comment]
However, should be a simple PR for non-starter 👍

**Comment by steakknife** [comment]
css-brunch is also deprecated.

**Comment by chrismccord** [comment]
@steakknife to be fair, @webdeb was just trying to be helpful and point your towards the new 1.3-rc installer which includes the latest brunch and would have fixed your issues. I know you're on an older stable version which is just fine. The v1.1/2 branches were using older brunch packages, but those have remained stable up until you just reported issues. We try to keep the churn on our js side to a minimum since folks run into issues even on seemingly stable point releases npm package wise. Thanks for the PRs, and remember to be kind :)
