### ISSUE TITLE
App is forced to restart after calling File.cd!

### ISSUE THREAD

**Issue by pytong** [phoenixframework/phoenix#2337]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): v1.3.0-rc.2
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: OS X El Capitan Version 10.11.6

### Bug
App is forced to restart after calling `File.cd!`
I have a small app that demonstrates this issue https://github.com/pytong/phoenix_restart_issue

Steps to reproduce:
1. GET http://localhost:4000/change_folder (this API calls `File.cd!`)
2. GET http://localhost:4000

### Expected behavior
App should continue to work without requiring a restart.

### Actual behavior
An exception was raised:
`[error] #PID<0.656.0> running PhoenixRestartIssue.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (RuntimeError) you must restart your server after changing the following config or lib files:

  * /Users/puiyee/dev/phoenix_restart_issue/mix.exs`

**Comment by josevalim** [comment]
Hi @pytong! Phoenix uses Mix to compile your project and Phoenix expects you to be in the root of the current directory. When you change directory, then it can no longer compile it. So if you want to change directory, I would advise you to remove the CodeReloader from your plug in the endpoint.

However, I would strongly advise to not call `File.cd!` because that's a global configuration. Imagine that in one action you call `File.cd!("/foo")` and in the other `File.cd!("/bar")`. If they are being accessed at the same time, one is going to win over the other, breaking at least one of them.
