### ISSUE TITLE
phx.gen with --web outputs incorrect router snippet and warning

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix#2421]
### Environment
* Phoenix version (mix deps): 1.3.0

When running generator with --web, e.g.
`mix phx.gen.html Products Product products code:string:unique`
`mix phx.gen.json Products Product products code:string:unique --web Api`

### Actual behavior
First an unnecessary info about the --web option is printed:
`The following files conflict with new files to be generated:`
`  * lib/myapp/products/product.ex`
`See the --web option to namespace similarly named resources`
`Proceed with interactive overwrite? [Yn] `
then a wrong snippet is generated
`Add the resource to your Api :api scope in lib/myapp_web/router.ex:`
`    scope "/api", MyAppWeb.Api do`

which leads to
`== Compilation error in file lib/myapp_web/controllers/api/product_controller.ex ==`
`** (CompileError) lib/myapp_web/controllers/api/product_controller.ex:18: undefined function api_product_path/3`

### Expected behavior
No message about --web is pronted when already using this option

The snippet code should be
`scope "/api", MyAppWeb.Api, as: :api do`

**Comment by chrismccord** [comment]
The behavior is correct here since you are trying to generate an entire context resource overtop of an existing one. We don't support generating only the web related files which would allow you to have a second `Api` controller, view, etc. Today, you need to write those additional web files yourself after bootstrapping the first one. The router snippet will be fixed in #2425. Thanks!
