### ISSUE TITLE
Do not set compile time dependencies on the router

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2530]
Since controllers and views import the router, they add a compile time dependency on the router which often triggers large recompilations ([source](https://elixirforum.com/t/8-elixirconf-2017-phoenix-after-100000-lines-renan-ranelli/8808/6?u=josevalim)).

We should consider aliasing the router helpers, which removes the compile time dependency and may make the code clearer.

It may also "solve" the issue folks have with resource generators, where they generate code and that code does not immediately compile. This would move the compile time error to a warning, which may be a positive or a negative thing.

Thoughts?

**Comment by wojtekmach** [comment]
What you're proposing basically comes down to just a change in the generated code like below, right?

```diff
--- a/lib/example_web.ex
+++ b/lib/example_web.ex
@@ -21,7 +21,7 @@ defmodule ExampleWeb do
     quote do
-      import ExampleWeb.Router.Helpers
+      alias ExampleWeb.Router.Helpers, as: R
       import ExampleWeb.Gettext
     end
   end
--- a/lib/example_web/controllers/post_controller.ex
+++ b/lib/example_web/controllers/post_controller.ex
@@ -19,7 +19,7 @@ defmodule ExampleWeb.PostController do
       {:ok, post} ->
         conn
         |> put_flash(:info, "Post created successfully.")
-        |> redirect(to: post_path(conn, :show, post))
+        |> redirect(to: R.post_path(conn, :show, post))
       {:error, %Ecto.Changeset{} = changeset} ->
         render(conn, "new.html", changeset: changeset)
     end
```

The experience for running html generator when forgetting to update router is a bit different.

Instead of:

```
== Compilation error in file lib/example_web/controllers/post_controller.ex ==
** (CompileError) lib/example_web/controllers/post_controller.ex:22: undefined function post_path/3
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

we get a wall of text (https://gist.github.com/wojtekmach/6f29643772d8db2dcf8331d2e0362408) but it includes helpful warnings which are arguably more useful:

```
warning: function ExampleWeb.Router.Helpers.post_path/3 is undefined or private. Did you mean one of:

      * page_path/2
      * page_path/3

Found at 2 locations:
  lib/example_web/controllers/post_controller.ex:22
  lib/example_web/controllers/post_controller.ex:46
```

I think it's a minor change that has some serious benefits for large projects :+1:

**Comment by josevalim** [comment]
@wojtekmach that's pretty much it, yeah. We will also need to do similar changes in the view. We will likely call the alias `Routes` but @chrismccord haven't agreed on a name yet.

**Comment by LostKobrakai** [comment]
This would also solve the potential for mismatch in route-function names when using multiple routers (like e.g. for subdomains)

**Comment by shulhi** [comment]
On one hand we get better compilation speed, but on the other hand having undefined function as a warning instead of an error seems backward. Coming from static language background, I prefer to have compilation errors than warnings that are definitely will cause error when those functions are called.

**Comment by davydog187** [comment]
FWIW, we made this change on our app and it didn't help break the inter-dependent compilation units in views.

**Comment by josevalim** [comment]
@davydog187 can you pinpoint what is still causing it then in your apps?

**Comment by davydog187** [comment]
@josevalim any suggestions for how to trace this down?

**Comment by josevalim** [comment]
@davydog187 the release announcements for Elixir v1.6 includes some new examples of using `mix xref` that should help here.
