### ISSUE TITLE
Fallback Controller not generated in new 1.3.0 phoenix app with mix phx.gen.html

### ISSUE THREAD

**Issue by jrissler** [phoenixframework/phoenix#2606]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v7.10.0
* NPM version (npm -v): 5.5.1
* Operating system: macOS Sierra

### Expected behavior
- expect action_fallback to be included in generated controllers + default fallback controller to be generated when using mix phx.gen.html (it was however generated with mix phx.gen.json).
- Is this by design?

### Actual behavior
- I thought it would be generated with mix phx.gen.html also, but it was not.

**Comment by josevalim** [comment]
Yup, by design, it is for phx.gen.json only but you can also add it to your html stuff if you want to!

**Comment by jrissler** [comment]
Awesome - thanks!

**Comment by danielfoxp2** [comment]
@josevalim is there some place where we can find the "why" on this decision? I ask because reading the release post or the docs it was not clear that the fallback generators would be only for json API. I struggled a bit thinking it was something wrong that I probably did untill give up and search on google.

I think that it would be awesome to have this to `phx.gen.html` too.

Thanks.

**Comment by chrismccord** [comment]
It's less natural to streamline html error cases to a fallback controller because often times you want to handle the same domain error cases uniquely. across controllers. For example, when you fail to save an entity, you'll show a flash message and render a specific template, which would be different across different controllers. That's not to say you can't or would never use a fallback controller for HTML, but it's much less of a goto for html.

**Comment by chrismccord** [comment]
To be clear, you can have as many fallback controllers as you want, but their main use is less applicable to html requests.
