### ISSUE TITLE
Outdated/Deprecated Dependencies

### ISSUE THREAD

**Issue by shingtaklam1324** [phoenixframework/phoenix#2684]
### Environment

* Elixir version (elixir -v): `1.5.2`
* Phoenix version (mix deps): `1.3.0`
* NodeJS version (node -v): `v9.3.0`
* NPM version (npm -v): `5.5.1`
* Operating system: Elementary OS 0.4.1, Built on "Ubuntu 16.04.2 LTS"

### Expected behavior

No error messages when running `mix deps.compile`

### Actual behavior

```
===> Compiling ranch
===> Compiling poolboy
warning: String.strip/1 is deprecated, use String.trim/1
  /home/shingtaklam1324/Programming/Elixir/hello_phoenix/deps/poison/mix.exs:4

===> Compiling cowlib
src/cow_multipart.erl:392: Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1

===> Compiling cowboy
==> ecto
```

**Comment by josevalim** [comment]
Those are fine. The poison one is not an issue because String.strip will be supported until Elixir 2.0 which is not coming any time soon. The second is not an issue because we don't use that functionality from Cowboy, we have our own.

You can issue `mix deps.update poison cowlib`  to see if there are more recent versions but that is mostly on the dependencies than on us.
