### ISSUE TITLE
Template parsing generates iodata that contains several levels of nested empty strings.

### ISSUE THREAD

**Issue by idyll** [phoenixframework/phoenix#2691]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): master
* NodeJS version (node -v): 9.3.0
* NPM version (npm -v): 5.6.0
* Operating system: macOS 10.13.3b

### Expected behavior

The iodata produced by views/templates should contain as many levels of empty strings in nested lists. Ideally, we should forgo adding them

### Actual behavior

A flash message or another call inside the template which returns `nil` (and possibly other circumstances) results in iodata being produced that look like:

```[[["" | ""]  | ""]  | "... template content..." ]```

### Why does it matter?

I think Cowboy is using the iodata to select frames to send with H2 and this results in extra work and possibly empty frames.

**Comment by josevalim** [comment]
Thanks! I would say this needs to be fixed on Cowboy since it shouldn't choke on a valid iodata but I would say we should still do our best to avoid those if we can. Pinging @michalmuskala since he has a PR on Phoenix.HTML which may impact this.

**Comment by idyll** [comment]
This is what triggers the Safari bug that I previously reported as https://github.com/phoenixframework/phoenix/issues/2686 . It sends the empty frames I think and Safari eventually hangs.

It may not make sense to fix this, but if it's easy I think we should.

**Comment by chrismccord** [comment]
This would be handled on the Phoenix.HTM.Engine side and double ping to @michalmuskala since his recent work was undecided on whether the added complexity justified the PR. Given the cowboy/H2 issues with empty frames I think we can certainly justify the work in the PR or similar work to fix this in the meantime. Worst-case scenario we end up with less iodata :)

**Comment by michalmuskala** [comment]
Hmm... Yeah, this might be an issue in how cowboy 2 handles the data it receives - the docs say it should accept any iodata. On OTP 20, the `erlang.iodata_to_iovec` function would be useful in situations like that since it encodes iodata to a flat list of binaries.

I think The PR should actually improve things since it should flatten the data a bit and the only way to produce an empty string in there would be if the user actually outputs an empty string in the template.

**Comment by idyll** [comment]
I've looked the the PR to phoenix_html @michalmuskala and it does fix the issue in Safari. 

During testing I did have a strange issue where the HTML for a page was wrong - some content was repeated - so it may need some additional testing.

**Comment by chrismccord** [comment]
Since this fix is on the phoenix_html side and resolves the safari issues I'm going close and the convo can continue over on phoenxi_html. Thanks!
