### ISSUE TITLE
Phoenix instrumenters and http status code inside phoenix_controller_call

### ISSUE THREAD

**Issue by kpanic** [phoenixframework/phoenix#2712]
hi everyone,

### Environment

* Elixir version (elixir -v): Elixir 1.6.0-rc.0 (182c730) (compiled with OTP 19)
* Phoenix version (mix deps): phoenix 1.3.0
* Operating system: linux

### Description

When trying to use the instrumenters feature, if I create an instrumenter like:

```elixir
defmodule Instrumenter.Example.My do
  def phoenix_controller_call(:start, _compile, conn) do
    conn
  end

  def phoenix_controller_call(:stop, _time_diff, %{conn: conn}) do
    # conn.status is always `nil` at this stage in the case of
    # phoenix_controller_call
    # However for phoenix_controller_render the conn.status will be there
    IO.inspect(conn.status, label: "http_status from the instrumenter")
    conn
  end
end
```
and I add it to the endpoint configuration with the `instrumenters: [Instrumenter.Example.My]` configuration.
when an http endpoint is hit then the `phoenix_controller_call/3` functions are invoked correctly, however `conn.status` will be always `nil` in the `:stop` stage. Is this intended?

This does not  happen when using `phoenix_controller_render/3`
Thanks!

**Comment by chrismccord** [comment]
This seems like a bug. Let me take a look. Thanks!

**Comment by chrismccord** [comment]
I see the confusion here, but in this case what is happening is by design. The instrumenter passes the return value from the `:start` callback to the last arg of the `:stop` callback as a means of passing information between the two, but the `conn` in this case is the *original* connection, not the plug connection after the controller has finished executing. Our instrumentation today doesn't support receiving the value of the executed block being instrumented, so you'll need to use something like `Plug.Conn.registered_before_send` to receive e the status of the conn.

**Comment by kpanic** [comment]
I imagined that, however I wanted to double check. 
In my project I "worked around" by using pattern matching `phoenix_controller_render/3` which contains the http status in the conn struct when we are at `:stop` "stage"

Good to know about `Plug.Conn.registered_before_send`!

Also FYI I thought (initially) that the `phoenix_controller_call/3` would invoke fully a controller's function, that's what confused me indeed.
Do you think it would be worth to improve the phoenix documentation?

Thanks a lot!
