### ISSUE TITLE
phx.gen.html does not generate template code for assocs

### ISSUE THREAD

**Issue by krystofbe** [phoenixframework/phoenix#2764]
Hi there!

I really love the `mix phx.gen.html `command. 

I've got a question concerning the generation of references. I can use references like `mix phx.gen.html Account User users name:string company_id:references:company` but in the generated templates for (new, show, edit, ...) there is no possibility to edit the referenced schemas with a combo box. There's simply no code generated for referenced schemas in the templates/controllers.

Is there a reason for this behaviour? Is this simply not done yet or has there been a decision to not include code for assocs?

### Environment

Elixir 1.6.1 (compiled with OTP 19)
phoenix 1.3.0

**Comment by josevalim** [comment]
In this case we go with the safest approach because we can't really choose how you want to expose the relationship. If we expose all existing associateed records, that can be a data leak. Sometimes the associated entry is set entirely in the controller and not by the user. There is no single answer.
