### ISSUE TITLE
Add static_push to Endpoint.Supervisor/Router.Helpers

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#2777]

**Comment by Gazler** [comment]
Today to use server push, a user must do something like:

```elixir
defmodule SomeController do

  def index(conn, _) do
     conn
     |> push(static_path("foo.png"))
     |> push(static_path("bar.png"))
     |> render("foo.html")
  end

end
```

Then in the template:

```elixir
<img src="<%=static_path(@conn, "foo.png") %>" />
<img src="<%=static_path(@conn, "bar.png") %>" />
```

It would be nice if the user could simply do:

```elixir
<img src="<%=static_push(@conn, "foo.png") %>" />
<img src="<%=static_push(@conn, "bar.png") %>" />
```

As a naive implementation, we could do something like:

```elixir
      def static_path(%Conn{} = conn, path) do
        path = static_path(conn, path)
        Plug.Conn.push(conn, path)
        path
      end
```

This will work for the Cowboy adapter because the push function causes a side-effect and does not change `conn` in any way, however this may not work for other adapters in the future that may do something on `conn`, such as build up the assets to be pushed and then send them prior to sending the response.

Perhaps we should gather all the assets when `static_push/2` is called and then call `Plug.Conn.push/3` at the end of the controller pipeline?

**Comment by josevalim** [comment]
I would go with the naive implementation. It is clean, elegant, and who knows when we will be using another HTTP2 server directly with Phoenix.

**Comment by chrismccord** [comment]
Agree. This is the way to go for now. If we end up needing to change the conn state then this feature couldn't be supported under those scenarios anyway in the template. In such a future case, user's would have to forgo the convenience, which is fine.

**Comment by Gazler** [comment]
Closing in favour of https://github.com/phoenixframework/phoenix/pull/2801
