### ISSUE TITLE
Allow different error codes during websocket connection

### ISSUE THREAD

**Issue by Shayon** [phoenixframework/phoenix#2847]
At the moment, the only response available when there is an error during the socket connection is a `403` as seen [here](https://github.com/phoenixframework/phoenix/blob/v1.3/lib/phoenix/transports/websocket.ex#L93). 

Instead of only returning a `403`, different error codes should be supported.  For example, in the [hexdocs for channels](https://hexdocs.pm/phoenix/channels.html) the sample code does authorization in the `connect/2` callback.  If incorrect authorization is provided then a `401` should be returned, not a `403`.

**Comment by josevalim** [comment]
Hi @Shayon.

The reason we don't allow custom status codes is because sockets are meant to be transport agnostic. Therefore, if we add status code, we will be coupling them to websockets and making them more limited on other platforms.

Also note the code in the guide is performing authentication, not authorization.

Thank you!

**Comment by jeremy-marcus** [comment]
@josevalim if the code in the guide is performing authentication then the proper response should be 401 unauthorized. 403 forbidden is the proper response for authorization.

**Comment by chrismccord** [comment]
There is no way to read the http status code from the `WebSocket` API, so allowing this would not help folks

**Comment by jeffutter** [comment]
Hi there, sorry to post on a closed issue. However, I'm sort of running into this issue as well, possibly with a different use case.

We're using `connect/3` to validate/verify a JWT:

```
  def connect(params, socket, _connect_info) do
    with {:ok, bearer_token} <- Map.fetch(params, "Authorization"),
         {:ok, jwt} <- Huddle.Auth.verify_token(bearer_token) do
      socket =
        socket
        |> assign(:user_id, jwt.claims["sub"])
        |> assign(:jwt, jwt.token)

      {:ok, socket}
    else
      _ ->
        :error
    end
  end
```

When our clients (iOS/Android) have expired or otherwise invalid JWTs they end up seeing a `403 Invalid HTTP upgrade`. All our other endpoints return a `401` for an invalid JWT, which the clients interpret as "time to use a refresh token or re-login".

Since this is a HTTP GET request, there should be some way to return a `401` right? Since the socket wires up to the endpoint before the router, I don't know any way to do the auth _before_ `connect` like we would normally do with a `Plug` pipeline.

Is there some other way to go about authenticating before `connect/3` or is this maybe a reason to allow `connect` to return more specific errors? Such as an `{:error, code}` or `{:error, code, reason}` tuple?

**Comment by chrismccord** [comment]
The websocket spec does not allow arbitrary status codes as a result of the HTTP upgrade. Your best option is to do the auth via a channel where you can respond as needed.

**Comment by jeffutter** [comment]
Chris, thanks for the response.

I may be misinterpreting the spec here - or reading the wrong portion of it, but:

https://tools.ietf.org/html/rfc6455#section-4.2.2
> 4.  Opening Handshake
> 4.2.  Server-Side Requirements
> 4.2.2.  Sending the Server's Opening Handshake
> ...
> 2. The server can perform additional client authentication, for
>       example, by returning a 401 status code with the corresponding
>       |WWW-Authenticate| header field as described in [RFC2616].

I'm probably mistaken as to what part of the handshake or upgrade `connect/3` is involved in - it looks like most of the upgrade portion happens in `cowboy`.

Either way, I think we can get our clients to work around this by refreshing their JWT when they get a `403`
