### ISSUE TITLE
Proposal - Update form errors rendering semantics

### ISSUE THREAD

**Issue by Math3v** [phoenixframework/phoenix#2899]
### Environment

* Elixir version (elixir -v): Elixir 1.6.5 (compiled with OTP 20)
* Phoenix version (mix deps): Mix 1.6.5 (compiled with OTP 20)
* NodeJS version (node -v): v8.11.2
* NPM version (npm -v): 5.6.0
* Operating system: OSX

### Expected behavior
```
<%= if @changeset.errors? do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
```

### Actual behavior
```
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
```

### Description
Hello everyone, I'm definitely a fan!

I was reading the _Programming Phoenix >= 1.4 (beta)_ and noticed the `<% if @changeset.action do %>` check for rendering errors. First of all, I'd like to propose a more semantically correct (imho) version: `<% if @changeset.errors? do %>`. I know this is a part of the _Ecto_ wrapper, but I also think they shouldn't make changes like these, which brings me to another point;

I definitely agree with a notion of _Context_ for hiding complexity and implementation details. It is a simple and powerful concept for separating persistence mechanism. Long story short; there probably should be another abstraction around the _Changeset_ so that we don't have to propagate it all the way to the views. What do you guys think?

Regards,
Matej

**Comment by josevalim** [comment]
Hi @Math3v, discussions are best sent to the mailing list, where a large community can engage.

Also, the reason why we do `@changeset.action` is because `@changeset.action` shows that we attempted to do something with the repository and that it failed. The reason why we don't do `@changeset.errors` is because in some situations you won't have errors, and relying on `@changeset.action` can help you find those and then add the missing errors accordingly.

Finally, regarding the notion of Context and Changeset, the Changeset was **chosen** as the abstraction to be sent to between contexts and views. It is part of their contract. You can of course pick something else if you want to.

**Comment by Math3v** [comment]
@josevalim thank you for the explanation!

What do you think about `@changeset.dirty?` or `@changeset.pristine?`?

I just find it really weird (semantically) to check for the presence of `@changeset.action`.

Regards,
Matej
