### ISSUE TITLE
Proposal: allow external libraries to use :private field in %Phoenix.Socket{}

### ISSUE THREAD

**Issue by grych** [phoenixframework/phoenix#2967]
Would you allow external libraries to use `:private` field in `%Phoenix.Socket{}` struct?

### Background
In a [channel-based library extending Phoenix](/grych/drab), I need to store some internal, private values in `%Phoenix.Socket{}` struct. So far, I use `:assigns` for this, and I name my keys with double underscore (like `:__client_id`) to indicate them as a private data.

But because `:assigns` is meant to be used by the enduser, I don't like this solution. It would be clearer if I could use `:private` field to store my data. That would be analogically to the `:private` field in a `%Plug.Conn{}` struct, which is used by different entities, like `Plug.Session` or `Phoenix`.

### Current Behaviour
Phoenix overwrites the `:private` field with `channel.__socket__(:private)`

### Expected Behaviour
To merge existing data in the `:private` field with `channel.__socket__(:private)`

### Solution
Probably the only change would be [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel/server.ex#L36):

```elixir
    socket =
      %Socket{
        socket
        | topic: topic,
          channel: channel,
          join_ref: join_ref,
          assigns: Map.merge(socket.assigns, assigns),
          private: Map.merge(socket.private, channel.__socket__(:private))
      }
```

I can make a PR if you agree.

**Comment by chrismccord** [comment]
For your library that builds on top of channels, it is probably better to expose your own state structure in the drab callbacks instead of exposing the underlying socket. So the fact that it is a channel underneath can be an implementation detail. The only examples I see in the readme use `poke`, so poke could accept your own structure, then you are free to load it up with whatever data you require. Plug private works really well because there is a long pipeline of transformations that decoupled code shares, but for stateful channels, it's not the case. Does that make sense?

**Comment by grych** [comment]
Thanks Chris for the explanation!

Drab callbacks could accept my own structure, the only issue is that the private data I am speaking about are coming from the client as a token and params in `connect` callback. As far as I know, I have to return `socket` from connect? So the only legit way I've found is to put them into `.assigns` field.

Also, I like reusing stuff, and the `socket` is a perfect fit for my purposes, as it plays the role of `conn` in the stateful world. `{controller, action, conn}` for stateless, `{commander, handler, socket}` for stateful Drab.

I will rethink all the stuff, maybe I could get the private data later, like while joining? But shouldn't I return socket from `join` callback as well?
