### ISSUE TITLE
Generated FallbackController blindly relies on Ecto

### ISSUE THREAD

**Issue by IslandUsurper** [phoenixframework/phoenix#2968]
### Environment

* Elixir version (elixir -v): Elixir 1.6.5
* Phoenix version (mix deps): phoenix 1.3.3
* Operating system: Linux

### Expected behavior
When using `--no-ecto` with `mix phx.new`, other generators shouldn't write code that depends on Ecto.

### Actual behavior
Calling `mix phx.gen.json`, even with `--no-schema`, writes the following in FallbackController:
```elixir
  def call(conn, {:error, %Ecto.Changeset{} = changeset}) do
    conn
    |> put_status(:unprocessable_entity)
    |> render(NoectotestWeb.ChangesetView, "error.json", changeset: changeset)
  end
```
Now it doesn't compile because Ecto isn't a dep of the app.

Ecto's very useful, so most users will be using it. But I think it's reasonable for the generators to check that Ecto is available before trying to use it, especially if `--no-schema` is being used.

**Comment by chrismccord** [comment]
All of our generator code today is geared towards Ecto inclusion, for example the generated controller code for `phx.gen.html` also assumes `%Ecto.Changeset{}` is returned from the stubbed context calls. Since passing `--no-schema` to any of these tasks gives you an incomplete implantation, some munging of the files will be necessary. In the case of the fallback controller, I think conditionally generating the Ecto.Changeset clause is worth it since this file isn't often touched right away. I would happily accept a PR which adds it. Thanks!
