### ISSUE TITLE
Translate Japanese

### ISSUE THREAD

**Issue by aimerald** [phoenixframework/phoenix#3076]
Hi! I am Aimerald from Japan.
I would like to translate the guide of this Repos to Japanese.
I want to publish it when I can translate it. Can I get permission?

**Comment by k-cross** [comment]
Hi @aimerald, just do it and submit a PR. It's awesome to see interest spreading across the globe!

**Comment by chrismccord** [comment]
@aimerald That sounds like a great effort! Note: as the guides are licensed under Phoenix's general license, you are free to use and modify them, so long as you respect the copyright under the license (https://github.com/phoenixframework/phoenix/blob/master/LICENSE.md)

Also note, we won't be able to accept the guide translations as a PR, since we don't have folks on the team to maintain them, but by all means translate the guides and make them available to the Japanese community at large ❤️❤️❤️🐥🔥🇯🇵
