### ISSUE TITLE
Ensure phx.gen.cert is umbrella-aware

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#3085]
https://elixirforum.com/t/phoenix-1-4-0-rc-0-released/17182/11?u=chrismccord

**Comment by voltone** [comment]
Actually, I guess the Mix task needs to know which child app to generate a certificate for, since the umbrella doesn't have its own `priv` directory. It does mean that if you have two Phoenix child apps, e.g. one web UI and one API, they are each going to need their own cert. For dev mode that's probably acceptable, and for production the certificate is probably going to be injected through some other means anyway.

**Comment by voltone** [comment]
In the above PR I fail the task at the umbrella level, like other `gen` tasks.

I still don't know how to ensure that the message displayed to the user references the correct Endpoint module. I wrote a function that finds all modules implementing the Endpoint behaviour, but that requires a `Mix.Task.run("compile", [])`, and besides it seems a bit... unconventional.

**Comment by chrismccord** [comment]
Thanks! I took care of the error message by exposing a private function we had on the Phoenix generator side. Thank you!!
