### ISSUE TITLE
Send all config options to Cowboy's configuration for websockets

### ISSUE THREAD

**Issue by lachezar** [phoenixframework/phoenix#3163]
Cowboy2.2's websockets accept [4 configuration options](https://github.com/ninenines/cowboy/blob/2.4.0/src/cowboy_websocket.erl#L61):
* compress => boolean(),
* idle_timeout => timeout(),
* max_frame_size => non_neg_integer() | infinity,
* req_filter => fun((cowboy_req:req()) -> map())

The websocket handler for Cowboy 2 forwards only [the first 2](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy2_handler.ex#L24) of the before mentioned options to Cowboy.

Most likely this is due to the fact that `max_frame_size` was not part of Cowboy before version 2.2.

I would like to suggest allowing Phoenix to forward all options given to the [websocket configuration](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-options) to Cowboy, instead of actively filtering the options list before sending it to Cowboy.

I would like to hear more opinions before making a PR for this.

**Comment by josevalim** [comment]
Hi @lachezar, I would rather not to because, opposite to plug where we do expose the underlying webserver, we try to keep transports mostly agnostic. Furthermore, we can't pass a req filters to cowboy, because it is an anonymous functions, and an anonymous functions at the module body won't "survive" after compile. So we are really only talking about the `max_frame_size` option and if somebody needs to set it, then we will gladly accept a PR for this specific option. Thank you!
