### ISSUE TITLE
1.4 phoenix.js failed in webworker

### ISSUE THREAD

**Issue by ipassynk** [phoenixframework/phoenix#3168]
### Environment

phoenix 1.4 webworker

### Expected behavior
Able to use phoenix.js in webworker.  It worked in 1.3.4

### Actual behavior
Failed since webworker does not have window object.
```
!(function(e, t) {
  'object' == typeof exports && 'object' == typeof module
    ? (module.exports = t())
    : 'function' == typeof define && define.amd
    ? define([], t)
    : 'object' == typeof exports
    ? (exports.Phoenix = t())
    : (e.Phoenix = t());
})(window, function() {
````

**Comment by chrismccord** [comment]
how are you requiring the source? If you require the es6 modules directly than our built phoenix.js, does it work? Thanks!

**Comment by jpanderson-outreach** [comment]
I copied down `1.4.0` phoenix JS and threw it in my project, because I lack the expertise to require ES6 modules directly in our build system. This allowed it to work. However, setting the `main` in package.json to a build that doesn't work in all cases seems dangerous and confusing for people trying to get this to work. Would it be possible to end up with a more system-agnostic `priv/static/phoenix.js` file and/or set `main` to be `phoenix.js` and let consumers minify and bundle on their own terms?

**Comment by ipassynk** [comment]
This is how it works in 1.3.4 and the same imports fail in 1.4 due to the fact that webworker does not have window object by design.

```
import { Socket as PhoenixSocket } from 'phoenix';
import { createAbsintheSocketLink } from '@absinthe/socket-apollo-link';
import * as AbsintheSocket from '@absinthe/socket';
```

**Comment by xfumihiro** [comment]
@chrismccord can you release this fix as a minor patch?

**Comment by hauleth** [comment]
@chrismccord maybe `phoenix` NPM package should be versioned independently form the Phoenix itself. Instead it should use protocol version as a version. It could simplify bug fixes releases like this one.
