### ISSUE TITLE
phoenix.js should close channel when there is a duplicate join without waiting for the server

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#3171]
Otherwise we can have race conditions in the client as two channels are running at the same time.

**Comment by josevalim** [comment]
Alternatively, we should return the existing channel. See this technique being employed here: https://github.com/poanetwork/blockscout/pull/1191

**Comment by chrismccord** [comment]
Returning the existing channel would be problematic because the caller would continue on with their bindings (channel.on), and also their channel.join, leading to double bindings, and pushes where they would expect otherwise.

**Comment by feliperenan** [comment]
We could avoid duplicated joins checking if already there is one channel joined consulting its topic name. I saw that `phoenix.js` avoids duplicated connections using an instance variable `joinedOnce`.

https://github.com/phoenixframework/phoenix/blob/fdfa225845a6e6d28072db2a4b0ddafb7ccb3c93/assets/js/phoenix.js#L425

But it only works if the front-end tries to join twice using the same Channel instance. Since `socket.channel('channel-name')` creates a new one, the front end is going to connect twice in the channel when this new instance using `.join()` function.

I think in something like that:

```JS
  join(timeout = this.timeout){
    existentChannel = this.socket.channels.find(channel => channel.topic === this.topic)

    if(this.joinedOnce || existentChannel) {
      throw new Error(`tried to join multiple times. 'join' can only be called a single time per channel instance`)
    } else {
      this.joinedOnce = true
      this.rejoin(timeout)
      return this.joinPush
    }
  }
```

Does it make sense?

**Comment by dballona** [comment]
Hey all! From my understanding, there are two scenarios which would lead to this:

1 - a duplicate creation of a channel on the front-end (race condition where the server takes longer to create the link and the front-end creates two channels which would cause duplicate events)
2 - the double join scenario as @feliperenan stated above. 

A way to solve the former would probably be introducing the same logic at the `Channel` class constructor and extract the `this.socket.channels.find(channel => channel.topic === this.topic)` logic to a "private" method.

Is this a reasonable approach @josevalim @chrismccord?

**Comment by dballona** [comment]
I think this version might be better... instead of having the logic within the channel itself, I moved it to the socket. This prevents from instantiating two different channels on the same socket with the same topic, which would lead to duplicate events. I hope this helps : )
