### ISSUE TITLE
No longer pass the topic on every channel wire message

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#3200]
The `join_ref` is enough. This means we can no longer support V1 on the socket. For V2, we can simply pass the topic as nil for now. And the topic will be made part of the payload on join.

Idea by @chrismccord.

**Comment by josevalim** [comment]
It should be completely backwards compatible. All the server will do is to stop using the "topic" information on every message. Then, if a client wants to optimize and not send it, that is totally fine. But if the client sends it, that's ok too.

I think to avoid confusion, we should do this as two separate commits. One that changes only the server, to show that it is completely backwards compatible, and then we optimize the client to send less data.

**Comment by michalmuskala** [comment]
Oh, you meant the client won't be sending this message. That is fine. I thought it was about the server not sending it - that's a different story.

**Comment by josevalim** [comment]
This blocks on #3171 (as the topic is currently used to detect duplicate messages on the server). Or, on the other hand, this can be used to allow duplicate joins on the same channel.

**Comment by dballona** [comment]
we could make #3171 rely on the `joinRef` instead for detecting duplicate joins. If appropriate, I can try to propose a solution for that.

**Comment by josevalim** [comment]
On the client the joinRef is guaranteed to be unique. So the client should
only check for duplicate topics indeed.

The joinRef only makes sense to be checked on the server, just for sanity
check purposes in case the client has a very severe bug.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by dballona** [comment]
just to make sure I understand it. considering only the client side piece:

- for #3171, instead of relying on the topic to detect channel uniqueness as I am proposing on #3295, we can rely on `joinRef` instead;
- then for this issue here, in the `Push` class instead of passing the topic every time, we can just remove the topic pass, as `joinRef` will be enough.

Does this sound accurate? If so, I can adjust the client-side for both #3171 and this (in separate PRs/commits, of course!). Then, for the back-end piece, I am not so sure if I am confident that I can help, but I might try something out : )

Thanks!

**Comment by josevalim** [comment]
#3171 and #3295 are about the client, this change is (mostly) about the server. For all purposes, you can consider them to be unrelated. :) Nothing should be changed on the client for now.

**Comment by josevalim** [comment]
This unfortunately means we would no longer support V1 serializers.
