### ISSUE TITLE
Drop SQLite from the list of supported databases

### ISSUE THREAD

**Issue by mitakas** [phoenixframework/phoenix#3218]
Drop SQLite (and MongoDB) from the list of supported databases in `guides/ecto.md`.

### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): v6.15.1
* NPM version (npm -v): 3.10.10
* Operating system: Ubuntu 16.04.5 LTS

### Expected behavior
Being able to use SQLite with Phoenix 1.4.

### Actual behavior
Support for SQLite (and MongoDB) was removed in 2016 (see issue #1843 and commit 60351e6). Ecto 3 (see #3100 and commit 5e84b20) is the default database wrapper and the adapter for SQLite isn't compatible with Ecto 3 (see the [Ecto documentation](https://github.com/elixir-ecto/ecto/blame/v3.0.3/README.md#L77) and elixir-sqlite/sqlite_ecto2#224) yet.

**Comment by mpranjic** [comment]
Phoenix 1.4 should work with Ecto 2, and `elixir-sqlite/sqlite_ecto2` should work with Ecto 2.
Haven't personally tried, but nothing implies not being able to use it.
Perhaps a note to `guides/ecto.md` about version requirements, but in my opinion Ecto documentation is clear about that, and because `guides/ecto.md` doesn't point to any specific libraries, you should check out `Ecto` anyway.

Phoenix is not bound to Ecto 3 in any way, except through mix tasks that generate ecto-related code.
SQLite [is not supported](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html#module-options) generator adapter, so you have to manually add libraries to `mix.exs` in which case you simply use Ecto 2.

**Comment by theodowling** [comment]
I was able to compile phoenix 1.4 using `sqlite_ecto2` and Ecto 2.

Putting details here for anyone else trying to do the same:

I started by generating a new Phoenix Project using Postgresql. I then updated to use sqlite3 instead.

Firstly I followed instructions as per https://github.com/elixir-sqlite/sqlite_ecto2:
```elixir
# In your config/config.exs file
config :my_app, Repo,
  adapter: Sqlite.Ecto,
  database: "ecto_simple.sqlite3"

# In your application code
defmodule Repo do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Sqlite.Ecto
end
```

Lastly I managed to get it compiling using the following combination of dependencies:

```elixir
defp deps do
  [
    {:phoenix, "~> 1.4.0"},
    {:phoenix_pubsub, "~> 1.1"},
    {:phoenix_ecto, "~> 3.2"},
    {:ecto, "~> 2.2.9"},
    {:sqlite_ecto2, "~> 2.2"},
    {:poison, "~> 3.1"},
    {:phoenix_html, "~> 2.11"},
    {:phoenix_live_reload, "~> 1.2", only: :dev},
    ...
]
```

**Comment by ConnorRigby** [comment]
Hello, I'm the maintainer of the [SQLite adapter](https://github.com/elixir-sqlite/sqlite_ecto2) and can confirm it _does_ still work in Phoenix, but does not support Ecto 3 yet

**Comment by cnmade** [comment]
Looks like https://github.com/elixir-sqlite/ecto_sqlite3  ecto support sqlite3 again.
Shall we bring sqlite back with phoenix framework?

**Comment by cw789** [comment]
@cnmade That was already done in `master` → https://github.com/phoenixframework/phoenix/pull/4268
