### ISSUE TITLE
Named params should include non alphanumeric chars within identifier

### ISSUE THREAD

**Issue by koudelka** [phoenixframework/phoenix#325]
I'm working on an app where there is no content type negotiation, I'm specifying file extensions manually in the router, like so:

`get  "/script/:id.js", ScriptController, :script`

In the corresponding action, the `id` parameter will come through with `.js` appended to it. Is that intended behavior, or should the `.js` be removed?

**Comment by dvcrn** [comment]
I think we should provide a option to terminate identifiers. URL fragments like `/search/:latitude,:longitude` are currently not possible because it assumes the comma is part of the identifier. 

Same if I had something like `/api/something/:id.:type`. I know that I can do the content type matching based on header, but when you expose an API, sometimes you want to make things a bit easier for your end users. 

In general, I can think of a ton of use cases where I don't just want a `/foo/bar/` kind of url
