### ISSUE TITLE
Render tag in eex file crashes VM

### ISSUE THREAD

**Issue by KamilZielinski** [phoenixframework/phoenix#3259]
### Environment

* Elixir version (elixir -v): 1.7.3, OTP 21
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): v8.10.0 (but not using)
* NPM version (npm -v): 6.6.0 (but not using)
* Operating system: Ubuntu 18.04.1

I just created a project, removed webpack watch, set Postgres connection and run the app to check if it works. Then I replaced default HTML with some page from bought bootstrap theme in `templates/layout/app.html.eex`. I wanted to exclude some html into `templates/page/index.html.eex`, but I forgot to remove render tag `<%= render @view_module, @view_template, assigns %>`, so I had it in both files. I run the server, visited `http://localhost:4000` and the app took 10GB of RAM in 4-5s (GC couldn't clean it) - then VM crashed, stucked for 2 minutes and produced `erl_crash.dump` with size of 4.8GB.
I can't share the code tho due to theme licences and I couldn't reproduce it with phoenix hello world app just by putting this tag in `index.html.eex` file. Memory usage was growing but GC was cleaning that quickly and then my browser showed me error page and VM was still alive.

```
eheap_alloc: Cannot allocate 4723591984 bytes of memory (of type "heap").

Crash dump is being written to: erl_crash.dump...done
```

### Expected behavior
- Error shown if this can't work

### Actual behavior
- Memory grows and (in my case) crashes whole VM

**Comment by chrismccord** [comment]
This is an infinite loop caused by your `render @view_module, @view_template, assigns` calling itself. This is not an issue with Phoenix and we can't do much to prevent a code path calling an infinite stack of functions. The VM did the best it could before memory was exhausted, then it crashed. Hope that helps. Thanks!

**Comment by KamilZielinski** [comment]
The thing that bothers me here is missing any warning. In this case I just copy-pasted render tag which I didn't notice and I would find out that there is something wrong when my production dies. No hint so far, only few GBs of dump.

Is there any case that such process would require that much memory like processing few hundred MB of HTML? What if default heap limit was set for such process and it would get killed?

**Comment by OvermindDL1** [comment]
> What if default heap limit was set for such process and it would get killed if it takes too much resources?

@KamilLelonek By default there is not max heap size set for a process, however you can add a plug that just calls something like `:erlang.process_flag(:max_heap_size, 100000)` and it will set the max heap size to 100000 words (a word is 32-bits on 32-bit systems and 64-bits on 64-bit systems, adjust as wanted), and if a process tries to use memory (remember the gc) and is unable to acquire it without growing its own heap then the process will be summarily killed.  I've not actually used this flag yet but it's been in for a few years now.

Do note, I don't think that includes the external binary store, so if a process allocates lots of >64-word(byte?) binaries then those won't be counted, but Phoenix EEX templates don't really do that (static binaries and iolists).  Instead of passing in a word to the argument of the flag call you can pass in a map of like `%{size: 0, kill: true, error_logger: true}` (the values shown are the defaults), where if `kill` is true then the process is killed when the limit is reached, and if error_logger is true then it's logged to the system erlang `logger` (if a key does not exist in the map it uses the default as shown above).

> Is there any case that such process would require that much memory like processing few hundred MB of HTML?

All depends on your own code and the data you process.  :-)

**Comment by KamilLelonek** [comment]
@OvermindDL1 you mentioned wrong Kamil :)

**Comment by OvermindDL1** [comment]
> @OvermindDL1 you mentioned wrong Kamil :)

Vwoop!  Bad github autocomplete!  ^.^;

**Comment by KamilZielinski** [comment]
@OvermindDL1 Thanks for your input :+1:  I'll try to work on limiting memory for such process and share some results if that worked for me :)
Anyway, some warning would be cool feature in such case. I'll see if there is possibility to do it :)

**Comment by OvermindDL1** [comment]
> Anyway, some warning would be cool feature in such case. I'll see if there is possibility to do it :)

You could make a plug that registers a memory limit that won't kill it but reports to logger, and have a logger (erlang logger that is*) listener for that message and then do something with it.  Have to be quick about it because if memory is running out you may not have a ton of time.  ^.^

Or kill it and log it both.  I'm curious how well that flag works, I've not messed with it yet.  This would be a great conversation thread on the Elixir Forums though!!
