### ISSUE TITLE
Conflicting unmatchable route does not generate a warning

### ISSUE THREAD

**Issue by mitchellhenke** [phoenixframework/phoenix#3261]
### Environment

* Elixir version (elixir -v): 1.8.0
* Phoenix version (mix deps): 1.4.0
* Operating system: macOS 10.13.6

### Expected behavior

If I were to have the routes:

```elixir
    get "/:id", PageController, :parameter
    get "/hello", PageController, :no_parameter
```

I would expect to receive a warning that my `/hello` route will never match because `/:id` always will.

### Actual behavior

No warning happens when compiling the application or running `mix phx.routes`

https://github.com/phoenixframework/phoenix/issues/2460 is related

**Comment by chrismccord** [comment]
This has always been an issue and would be difficult for us to detect because as of right now we rely on compiler warnings to detect collisions. Since the dynamic `/:id` will generate a different clause than `"/hello"`, we can't yet detect these kinds of collisions. I would be open to a PR exploring fixing this, but this is not something I plan to tackle in the near future. If you're interesting in poking at this, let me know. Thanks!

**Comment by chrismccord** [comment]
Actually these clauses should conflict. I’ll dig into this when I get some time. Thanks!

**Comment by mitchellhenke** [comment]
@jeregrine and I spent some time poking around it, and it seemed like the match functions that get generated won't generate the function clause warning due to the params .

If the function clause warning is not feasible, would it be reasonable to try to do some kind check on all the routes in a scope after the routes have been compiled, and output `IO.warn` for any unmatchable ones?

**Comment by josevalim** [comment]
Unfortunately there isn't much we can do here. Those checks are emitted by the Erlang compiler. We could do them, but they would be expensive (both in time to implement and in running them). Maybe one day the Erlang compiler will be able to warn on those too, but at the moment, I would say this isn't something *we* can act on. Thanks for the report!
