### ISSUE TITLE
Support secret rotation

### ISSUE THREAD

**Issue by fishcakez** [phoenixframework/phoenix#3312]
It should be possible to support key rotation without impacting user experience. This requires being able to change the primary `:secret_key_base`, which can be done right now with a plug. However previous secrets could still be active for a certain period of time to support reading data signed with the prior keys.

For example it is possible to dynamically set the `:secret_key_base` using a plug to assign the value but this only supports changing the primary key but does not allow to continue using prior but still active ones. If there are 2 or more hosts this could lead to multiple data invalidations because the secret won't be changed atomically on all hosts.

If secret rotation is employed it is likely that a different library is being used to handle reading the secrets. It would be nice to configure phoenix to call the library's function to read the secrets directly to avoid having to handle secret rotation manually.

**Comment by fishcakez** [comment]
As followup to clarify would need a preferred key, and list of fallback keys.

**Comment by OvermindDL1** [comment]
I'm curious, is the secret_key_base used from the application environment every time?  If so it would be pretty trivial to update it by just generating and putting the new one on a timer or so.

**Comment by achempion** [comment]
Is it possible to solve your issue by using server-based session storage?

**Comment by GriffinMB** [comment]
@achempion `secret_key_base` is not just used for sessions. 

@OvermindDL1 - hot-updating the secret would be trivial, but then you would be unable to verify encrypted and signed messages that are consumed after the swap. Typically, you'd want some amount of overlap in secret keys to prevent unnecessary message/session/etc validation failure.

Also, this is something that may need/want Plug support first, since it also uses the `secret_key_base` for session and CSRF functionality, and it's general enough behavior that other web frameworks are likely to find it important and useful. Either way, I'm happy to help on this.

**Comment by josevalim** [comment]
Moving to Plug as I believe the discussion needs to happen there first.
