### ISSUE TITLE
Improvements to source display in error pages?

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix#3357]
I like the fact that the Phoenix error page includes a source display area which I can direct to different stack frames by clicking radio buttons. However, I think this feature could be improved by a couple of small additions.

First, I'd like to have a scrollbar (e.g., on the right edge), so that I can look at the rest of the code in the file. Second, I'd like to be able to stretch the textarea (e.g., by grabbing the lower right-hand corner).

**Comment by sandeshsoni** [comment]
If this is a valid issue, I would like to contribute.

looks like a couple of CSS tweaks.

**Comment by chrismccord** [comment]
Please send a PR! This would be on the plug side since it's controlled by the Plug.Debugger. Thanks!

**Comment by sandeshsoni** [comment]
@RichMorin 

There is a left section and a right section.
Attached screenshot.

You mentioned you would like to see the rest of code in the file by textarea/scrollbar.

plz refer stretch on left-section.
currently, only few lines of file are displayed for error message.

Question for you.
Do you expect the whole file should be displayed when file selected from RHS?
the file should should be displayed from error line and when scrolled and stretch text area, show the rest of file?
I am confirming if I understood the suggested feature.


### Left Section
<img width="595" alt="Screenshot 2019-04-09 21 05 07" src="https://user-images.githubusercontent.com/3761745/55814249-c5a1e480-5b0b-11e9-9ddf-8993376f3cc6.png">

### Right section
<img width="693" alt="Screenshot 2019-04-09 21 08 02" src="https://user-images.githubusercontent.com/3761745/55814401-0e599d80-5b0c-11e9-82da-4da821e38861.png">

**Comment by RichMorin** [comment]
Your proposed change to the left section looks like what I had in mind.
However, I wouldn't object to having a way to scroll or stretch the
right section, in case someone wants to view the information that is
currently being cut off on the right edge.  Alternatively, what about
moving that information underneath the current left hand lines?

*  elixir - lib/enum.ex:1940
   Enum."-reduce/3-lists^foldl/2-0-"/3
...

FWIW, I've never been able to make much sense of the right hand text,
but I assume that other folks can...

> currently, only few lines of file are displayed for error message.
> ...
> Do you expect the whole file should be displayed when file selected from RHS?
> the file should should be displayed from error line and when scrolled and
> stretch text area, show the rest of file?

The LHS should look very much like it does now, with a few minor changes:

- There should be a stretching icon in the lower right-hand corner.
- There should be a scroll bar on the right hand edge.
- The initial number of lines shown could be increased (eg, doubled).

So, it would still show only a small number of lines surrounding the
point where the error was detected.  However, the user would be able
to scroll and/or stretch the display to see more context.

Incidentally, some highlighting should be present on the error line,
so that the user can easily spot it even if things are moved around.

Thanks for your diligence and effort!

-r

**Comment by sandeshsoni** [comment]
@RichMorin ref attached gif. I hope this is the expected behaviour.
I am trying to implement this.

## changes
- [x] increase surrounding error lines from 5 to 10. [possible]
- [x] enable resize like text-area. [possible]
- [ ] Initially display only 5 surrounding lines like existing behaviour. other lines on scroll.

## No change required on RHS as when clicked any file on RHS, the details are displayed on LHS block.




![errorMsgOptimize](https://user-images.githubusercontent.com/3761745/55842149-dc6a2a80-5b4f-11e9-9ec1-99c3ca0dec51.gif)

**Comment by RichMorin** [comment]
Looks very promising to me; now it's up to Chris...

-r

**Comment by sandeshsoni** [comment]
Hi @RichMorin 
I was able to change to display 20 lines instead of 10lines.
Resize button is also possible.

but I could not achieve the expected CSS effect i.e display just 10 lines (5lines around error line). when stretch, display few more lines of code. The error block will begin from the top and will look strange.
I dont think it would be a good idea to use javascript to scroll in middle so I skipped it.

If you have suggestion, then do share.
I have pushed the code for reference here https://github.com/sandeshsoni/plug/commit/6b6d2f18196fc4cb11d1aaf1f3434e0f95b78e4c

If you see a solution, feel free to comment.

<img width="550" alt="Screenshot 2019-04-11 15 57 03" src="https://user-images.githubusercontent.com/3761745/55951386-bee2b100-5c74-11e9-99cb-cbe2ba04d348.png">
