### ISSUE TITLE
"backport" heroku.md to 1.4 branch

### ISSUE THREAD

**Issue by petermm** [phoenixframework/phoenix#3360]
people are stumbling on the published https://hexdocs.pm/phoenix/heroku.html (eg https://elixirforum.com/t/heroku-deployment-woes/20215/18) as it doesn't include all the updates/fixes in the master branch: https://github.com/phoenixframework/phoenix/blob/master/guides/deployment/heroku.md

**Comment by edwinthinks** [comment]
I believe there are few remedies for the elixir buildpack using 1.5.0 still by default:

1) Release the latest elixir buildpack as mentioned in this [issue](https://github.com/HashNuke/heroku-buildpack-elixir/issues/145) 

2) Change the guide from saying `heroku create --buildpacks hashnuke/elixir` to `heroku create --buildpacks https://github.com/HashNuke/heroku-buildpack-elixir.git`. This let your heroku build know to use that latest version on master /w default set to 1.5.3.

3) Publishing the documentation that is currently on master (I believe this happens when a release is made?) will at least in part include instructions to specify the elixir buildpack version.

Thats my 2 cents & thoughts. Hope we get some clarity soon =)

**Comment by chrismccord** [comment]
Closed in v1.4. Thanks!
