### ISSUE TITLE
Channel has `onClose` but does not have an `onJoin` or `onOpen` (js socket client)

### ISSUE THREAD

**Issue by futpib** [phoenixframework/phoenix#3379]
### Environment

* Phoenix npm package: phoenix@1.4.3

The rest of the environment info is probably irrelevant (but provided).

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): v11.14.0
* NPM version (npm -v): 6.9.0
* Operating system: Linux

### Expected behavior

Channel has both `onClose` and `onJoin` (or `onOpen`).

### Actual behavior

There is no such counterpart to channel `onClose`.

### Workaround

`channel.join().receive("ok", () => { ... })`

**Comment by josevalim** [comment]
Hi @futpib, this is actually a feature request, so could you please expand on why would you need a onJoin? We need onClose because it can happen asynchronously, but you always have control of when the join happens, so why would we need a callback?

**Comment by futpib** [comment]
> you always have control of when the join happens

I din't think you have control in case of a rejoin from `errored` state.

I would also generally argue that every state transition should be observable with callbacks or events, to keep the UI updated if nothing else.

**Comment by chrismccord** [comment]
Your channel.join's receive callback is the onJoin callback. Is there a reason you need more?:

```javascript
channel.join()
  .receive("ok", () => // my "onJoin" stuff)
```

**Comment by futpib** [comment]
I don't necessarily need it, but it would make for a more coherent API.

**Comment by chrismccord** [comment]
The api accommodates the full life-cycle events - join, error, and graceful close states, so an additional onJoin would dup where join functionality lives, so it's better to keep it in a single place api wise. Thanks!

**Comment by futpib** [comment]
> it's better to keep it in a single place

But it's the opposite of keeping it in a single place: some state transitions are observed through `onClose` and `onError`, and another one through `receive`.

**Comment by chrismccord** [comment]
`onClose` and `onError` events happen after you join. When you join, you handle join success/error/timeout in the receive chain. So for joins, `onJoin` is never out-of-band. It is always handle in your receive chain because you need to handle the failure modes of join error and join timeout. If we added an `onJoin` callback, then you may have two code-paths handling join behavior, living separately, and you would still need to handle the join error and join timeout cases, so it makes sense to handle it all in the receive chain of `myChanne.join()`
