### ISSUE TITLE
Linked Process Dying Does Not Return 500

### ISSUE THREAD

**Issue by Ishjot** [phoenixframework/phoenix#3395]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```
* Phoenix version (mix deps):
```
* phoenix 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (phoenix) 5d9a0e2c
```
* NodeJS version (node -v): n/a
* NPM version (npm -v): n/a
* Operating system: MacOS

### Expected behavior
An exit in a controller process should return a 500 to the client.

### Actual behavior
If the exit is in the controller process directly, a 500 is returned.
```elixir
  # Returns a 500 correctly.
  def exit(conn, _req) do
    exit(:normal)
    send_resp(conn, 200, "test return")
  end
```

If the exit is in a linked process, a 500 is NOT returned. Instead, the controller process dies and the client experiences a timeout.
```elixir
  # Does not return a 500.
  def exit(conn, _req) do
    spawn_link(fn -> exit(:normal) end)
    send_resp(conn, 200, "test return")
  end
```

**Comment by dmorneau** [comment]
Are you sure the spawned process isn't dying *after* the request handler sent the response? You can check by inserting a small sleep between the `spawn_link` and `send_resp`.

**Comment by josevalim** [comment]
We need more information here because an `exit(:normal)` **does not** cause links to crash. Can you provide a minimal test case that reproduces the issue? Thanks!

**Comment by Ishjot** [comment]
Hi @dmorneau , I added a sleep between the two, and the result is the same. No response from the server, and the client just times out.

```elixir
  def exit(conn, _req) do
    spawn_link(fn -> exit(:foobar) end)
    Process.sleep(500)
    send_resp(conn, 200, "test return")
  end
```
```bash
> curl localhost:4001/clear
curl: (52) Empty reply from server
```

@josevalim the above is an example of a minimal test case that reproduces the error, with an exit code that is not `:normal`. Let me know if I can provide any other info, thanks! 😄

**Comment by josevalim** [comment]
Thanks @Ishjot. Btw, is that a Plug or a Controller action? If a Plug, where is it being invoked?

**Comment by Ishjot** [comment]
A controller action.

**Comment by achempion** [comment]
The controller does not return anything because (as I perceive) it does not implement the trap exit flag for a process. If the linked process exits the parent process exits too.

http://erlang.org/doc/man/erlang.html#process_flag-2

You can check in with iex shell:
```elixir
Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> spawn_link(fn -> exit(:normal) end)
#PID<0.140.0>

iex(2)> spawn_link(fn -> exit(:not_normal) end)
** (EXIT from #PID<0.138.0>) shell process exited with reason: :not_normal

Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

The question is: should we implement trap exits for a such case? 

I think a programmer should be aware of language features and not link processes to the controller directly. Right now I can't come up with a case when it should be useful.

P.S. iex doesn't crash because it reinitialises itself in such cases, see https://github.com/elixir-lang/elixir/blob/87ccbafcedb58fe1113da6bfa036f6f7f963515d/lib/iex/lib/iex/server.ex#L179 (`defp handle_take_over` function)

**Comment by achempion** [comment]
I've checked the case with `:normal` exit on v1.4.9 and it doesn't return 500 / error page. It behaves like nothing happened.

**Comment by Ishjot** [comment]
@achempion I think my concern is that a crash in the controller process directly _does_ return a 500, but, a crash in a linked process, which causes the controller process itself to crash, _does not_ return a 500.

Both of these cases should return a 500 in my opinion because a crash of the controller process indicates some sort of issue on the server with the request, which makes `500 Internal Server Error` an appropriate response.

**Comment by chrismccord** [comment]
This is an issue on the cowboy side where someone would need to write a cowboy specific trap exit option/middleware. Today, you have a couple reasonable options in your phoenix project:

1. `Process.flag(:trap_exit, true)` in the cases you are linking for async work that may fail
2. Start your spawned process under a supervisor instead of linking

Thanks!
