### ISSUE TITLE
hibernate_after in Phoenix.Channel requires Elixir 1.8

### ISSUE THREAD

**Issue by Chrisso** [phoenixframework/phoenix#3403]
The `:hibernate_after` option in `Phoenix.Channel` introduced in Phoenix 1.4.4 with https://github.com/phoenixframework/phoenix/commit/d1991fa1d27a908e373a8835e26ce129a9bdbbb1#diff-cfa0128824823c13a720654d72db9564L358 is supported from Elixir v1.8 upwards. Thus dialyzer complains when using Phoenix 1.4.4 with Elixir 1.7.x

```
The function call will not succeed.

GenServer.start_link(Phoenix.Channel.Server, _ :: any(), [{:hibernate_after, 15000}, ...])

breaks the contract
(module(), any(), options()) :: on_start()
```

On the other hand `mix.exs`  states that these Elixir versions should be fine: `elixir: "~> 1.5.1 or ~> 1.6"`.

Options for a fix that come to mind:
* raise Elixir version requirement to 1.8
* do not use `:hibernate_after`
* silence dialyzer

### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.4
* Operating system: Debian Stable

**Comment by josevalim** [comment]
I think this is a classic example of where types are being strict when they have no business in doing so. The GenServer options is a keyword list on purpose. We also don't check the keys on purpose. Exactly because we want to allow the API to grow, and to provide new options, and allow libraries to use those options without having to bump the Elixir version. The behaviour is, for all purposes, correct on all Elixir and Erlang/OTP versions.

This is an issue that only appears to dialyzer users, so I would recommend dialyzer users to either silence the warning in their projects or update to v1.8.

Thanks for the report!
