### ISSUE TITLE
Support a new headers key in Transport.connect_info/2

### ISSUE THREAD

**Issue by Shayon** [phoenixframework/phoenix#3427]
At the moment `Transport.connect_info/2` only supports the `x-headers` key for retrieving header information.  This is not especially useful for folks following [RFC-6648](https://tools.ietf.org/html/rfc6648) which deprecates the use of the `x-` prefix for unstandardized parameters.

I would like to enable folks, like myself, who have custom headers without the `x-` prefix.  My suggestion would be to add an additional supported key to `Transport.connect_info/2`, say `:headers`, that will not filter headers for those only beginning with `x-`.

https://github.com/phoenixframework/phoenix/blob/3bfb9f6e900c9a2e31cb95736e2cb5bdad329b61/lib/phoenix/socket/transport.ex#L333-L351

**Comment by chrismccord** [comment]
I would prefer to wait on this one. The issue exposing headers is it leaves users easily vulnerable if they access cookies. I'm willing to revisit this in the future wrt RFC6648, but the pragmatic approach in the meantime is for you to use x-headers. Thanks!

**Comment by Shayon** [comment]
Hey @chrismccord, is there a specific name for the vulnerability you are referring to? Or maybe could you give me a slightly longer description? I'd like to understand the danger here better.

**Comment by chrismccord** [comment]
https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by OvermindDL1** [comment]
Isn't that what the Origin header fixes though?  Checking the origin header then makes the cookie reasonably safe to access (outside of secondary programs reading the browser cookie store directly, of which the current protections do not help against).  At the moment even the origin header is not checkable, which in itself does not seem terribly secure?  In addition, for some services you *want* the cookie and still allow unbounded access, such as for public access services, this is not possible without otherwise forcing the user to supply some kind of temporary access key to the other service for each and every user, which then has to be either supplied every time or stored in some method (which may not be necessary otherwise).

**Comment by Logician** [comment]
@chrismccord are you aware that websockets are also used outside of the web, for APIs between clients and servers, to take advantage of HTTPS generally getting past firewalls better. Not being able to access headers for these use-cases is made unnecessarily difficult, nor is there any documentation for suggestions on how to adopt potentially standard practices for them or how to tap into the existing setup of sessions in phoenix. 

Also as the commenter above pointed out, the Origin should already cover the concern? It seems like the server engineers are being punished by prevented from exploiting cookies from other sites, but malicious server engineers could just not use elixir then? From my point of view a server engineer should be able to implement a security model of their choosing. Caveat: this second paragraph may be me not totally understanding the header filter solution in phoenix.
