### ISSUE TITLE
/config/*.secret.exs not added to .gitignore upon project creation

### ISSUE THREAD

**Issue by bigbassroller** [phoenixframework/phoenix#3492]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

* Phoenix version (mix deps):
phoenix 1.4.9 (Hex package) (mix)
locked at 1.4.9 (phoenix) 746d098e

* NodeJS version (node -v):
v11.11.0

* NPM version (npm -v):
6.7.0
* Operating system:

### Expected behavior
`/config/*.secret.exs` automatically added to `.gitignore` when creating a new project with `mix phx.new`. Otherwise someone might blindly `git add --all` their creds 😬

### Actual behavior
`/config/*.secret.exs` is not added automatically to `.gitignore`

I can submit a PR with changes if you would like.

**Comment by dealloc** [comment]
As I understand it, the *.secret.exs files no longer contain the actual secret, but instead code to retrieve it from the system environment variables.
For example, my database credentials are generated to be retrieved like this:
```elixir
database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """
```
which does not contain any sensitive information at all.
I personally like this approach since it means we don't have a file that needs to be correctly configured for the app to work, but can't be placed in git

**Comment by josevalim** [comment]
Yes, exactly what @dealloc said. The files are now safe for source control versioning.
