### ISSUE TITLE
Memory leak in stateChangeCallbacks 

### ISSUE THREAD

**Issue by sqal** [phoenixframework/phoenix#3517]
### Environment

* Phoenix JS library v1.4.9

### Steps to reproduce

- Go to https://codesandbox.io/s/jolly-curie-furb6 
- Click Add Channel button few times and then remove channel
- Open devtools and check console logs

### Expected behavior

When removing a channel through `socket.remove(channel)`, socket should properly clean up any lifecycle events added by the removed channel.

### Actual behavior

```
channels count 1
Callbacks count
- open: 1
- close: 0
- error: 1
- message: 0

channels count 2
Callbacks count

- open: 2
- close: 0
- error: 2
- message: 0

channels count 1
Callbacks count

- open: 2
- close: 0
- error: 2
- message: 0

channels count 0
Callbacks count

- open: 2
- close: 0
- error: 2
- message: 0

```

As you can see the number of callbacks in open and close arrays doesn't decrease after channel is removed. This happens because in line [#L379](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L380) and [#L379](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L380) these 2 callbacks are added to the socket using anonymous function but they're not  cleaned up when removing a channel.

**Comment by snewcomer** [comment]
@chrismccord I'm having a little trouble figuring out the best solution here.  

Effectively, `stateChangeCallbacks` is an array with no identification of **who** the callback belongs to.  Given some of these methods on the Socket like `onOpen/onClose` are public APIs, I'm not sure how we can solve this without making breaking changes to them.  The solution being passing the channel as an arguments as well to something like [this](https://github.com/phoenixframework/phoenix/blob/ba55f7ea969f6af5470a71e34a987f2cea848f85/assets/js/phoenix.js#L869)....to key the callback so we can find it and remove it at some point during the app lifecycle.

Another option that would not be breaking is we internally maintain keyed callbacks whether it has a reference **channel** or not.  The public Socket API can call `onClose(callback)` and we will generate a random key - `stateChangeCallbacks.push({ randomKey: callback })` whereas internally we can key by owner - `stateChangeCallbacks.push({ channel: callback })`. Internally we can find the callback with the keyed **channel** and splice it out of `stateChangeCallbacks`.  So `socket.remove(channel)` or `channel.leave()` or some of the methods in the `Channel` constructor are properly managed.  Whereas the public API may be unable to properly manage this state.  However, this seems as desired since, say `socket.onOpen(() => {...})` may be called with [reference](https://github.com/phoenixframework/phoenix/blob/ba55f7ea969f6af5470a71e34a987f2cea848f85/assets/js/phoenix.js#L380) to a channel or [generally](https://github.com/phoenixframework/phoenix/blob/ba55f7ea969f6af5470a71e34a987f2cea848f85/assets/js/phoenix.js#L863).  (Is this last statement true?)

I'm not sure your preference or if you have other solutions in mind.  I think the second one seems reasonable...
