### ISSUE TITLE
Headers cannot be retrieved in connect_info when using sockets

### ISSUE THREAD

**Issue by adrienmo** [phoenixframework/phoenix#3524]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: Mac OS X

### Expected behavior

HTTP Headers can be retrieved when establishing a socket connection: e.g. :`user-agent` `authorization`

### Actual behavior

Only headers starting with X can be retrieved: https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-shared-configuration

`socket "/ws", MyApp.MySocket, websocket: [connect_info: [:x_headers]]`

Headers starting with X are now deprecated, so we should be able to retrieve any headers of the HTTP connection https://tools.ietf.org/html/rfc6648

**Comment by chrismccord** [comment]
This is intentional but we will re-examine as time goes on. Thanks!

**Comment by adrienmo** [comment]
Why is it intentional ? Is there another better way to do this?

**Comment by steffenix** [comment]
What's about X headers being deprecated? If we shouldn't use it how can I pass headers to the socket?

**Comment by LightningK0ala** [comment]
AFAIK the reason they're not being passed is because [https://elixirforum.com/t/accessing-cookies-in-phoenix-socket-connect/4731/4](transports are agnostic)? I'm actually looking for the ability to use cookies for authenticating the websocket because it seems to me that CSWSH is mitigated by :check_origin defaulting to true? Even without SameOrigin (which is sufficiently supported by now?).
