### ISSUE TITLE
Generator doesn't respect custom elixir_paths

### ISSUE THREAD

**Issue by imanhodjaev** [phoenixframework/phoenix#3555]
Hey,

I have an umbrella application and renamed `lib` directories to `src` also updated all `elixir_paths` to reflect this change.

Now when the following command called it created `lib` directory under context application

```sh
$ mix phx.gen.context Accounts User ...
```

### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* Operating system: macOS

### Expected behavior

It should respect `elixir_paths` from mix config.

### Actual behavior

Creates `lib` directory instead of configured `elixir_paths`

Thanks.

**Comment by chrismccord** [comment]
As this is a very far edge-case, I'm going to wait until we hear more requests for a generator option to accommodate this use case. As it sits, this is the first request since inception, so not likely something we'll move on soon. You're welcome to send a PR for evaluation, but I can't guarantee we'll move forward with it. If the changes are minor we may be able to justify. Thanks!

**Comment by imanhodjaev** [comment]
Thanks for quick reply! I disagree this is an edge case because becomes very obvious once you rename default `lib` path to something else.

**Comment by chrismccord** [comment]
yes, but very very few people are renaming the default elixirc_paths to exclude lib, so it's an edge case in that regard that a tiny fraction will ever have an issue.
