### ISSUE TITLE
DataCase.errors_on crashes for validates_inclusion failure with enumerables without String.Chars

### ISSUE THREAD

**Issue by lpil** [phoenixframework/phoenix#3587]
A fairly recent Ecto change made it so `validates_inclusion` has the enumerable of valid options in in the error message. 

Prior to this change all error fields would implement the `String.Chars` protocol, but now it may not as not all enumerables do (i.e. MapSet in the stdlib). This breaks the generated `DataCase.errors_on` function. 

A fix was added in Ecto that converts all enumerables to lists but has been reverted as it expands ranges which can generate very large error messages. Jose says this is now to be fixed within Phoenix.

- Inclusion PR: https://github.com/elixir-ecto/ecto/pull/2984
- DataCase.errors_on: https://github.com/phoenixframework/phoenix/blob/c6dd582ea0a8df321977ebf459afedaffc997689/installer/templates/phx_ecto/data_case.ex#L49
- Fix PR: https://github.com/elixir-ecto/ecto/issues/2991
- Revert: https://github.com/elixir-ecto/ecto/issues/3144

This problem may be present in other functions too such as form helper functions.

**Comment by wojtekmach** [comment]
This is no longer an issue per se because as of #3204 we no longer call `to_string` on _all_ fields, only on the ones that are interpolated. Here's how errors_on looks like in Phoenix v1.4.10:

https://github.com/phoenixframework/phoenix/blob/v1.4.10/installer/templates/phx_ecto/data_case.ex#L46:L52:

```elixir
  def errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {message, opts} ->
      Regex.replace(~r"%{(\w+)}", message, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end
```

Thus I think this can be closes. cc @josevalim 

However, for existing Phoenix apps that are were using previously generated errors_on and friends the error still exists.

**Comment by josevalim** [comment]
Ah, @wojtekmach is correct. It has been fixed in latest generators. Thanks both!

**Comment by lpil** [comment]
Wonderful, thanks everyone!
