### ISSUE TITLE
`Phoenix.ConnTest.get/3` should pass params as string values to controller

### ISSUE THREAD

**Issue by nathanl** [phoenixframework/phoenix#3605]
### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): v12.1.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOS Mojave

### Expected behavior

`Phoenix.ConnTest.get("/foo", %{count: 5})` should result in the controller receiving the `count` param as a string value, reflecting the behavior of `curl http://localhost:4000/foo?count=5`.

### Actual behavior

`Phoenix.ConnTest.get("/foo", %{count: 5})` results in the controller receiving the `count` param as an integer value. It does not appear to be possible for a real `HTTP GET` to do this.

### Impact

Controller code can be written which treats a param as an integer, and even though this will fail in real usage, the tests make it appear to work. When the bug in the application code is discovered and fixed, all tests have to be updated to explicitly pass the param as a string, like `Phoenix.ConnTest.get("/foo", %{count: "5"})`

### Details and Demo

https://github.com/nathanl/param_test

**Comment by mcrumm** [comment]
This would be a welcome change, IMHO. I've personally experienced similar pain, when params were written in a test as a map with atom keys.

The params were passed into the Controller through `get/2`, merged with another map of atom keys, and finally passed to an Ecto Schema's `changeset/2` function.  This will work _just fine_ in a test, but will immediately error when the Changeset encounters a map with mixed keys outside of the test environment.

**Comment by josevalim** [comment]
A PR that traverses the map would be welcome. I am almost sure we already traverse stuff to stringify the keys, so stringifying the values would be helpful too.

**Comment by mcrumm** [comment]
@josevalim you're of course correct. I dug into the relevant code in Plug, and I must have been thinking about something else, because keys are most definitely converted.

This is likely to be a little more involved that just to stringify the values in the params enum. The same traversal occurs for GET as for POST, and that's fine unless the content type means the body is something non-stringy (high technical term, that), like `application/json`.

Furthermore, the mere presence of additional params sets an (undefined) content-type to `multipart/mixed`, which, for a GET request, really doesn't make sense.

Happy to open an issue/PR on Plug!

**Comment by josevalim** [comment]
> Happy to open an issue/PR on Plug!

Please do!

**Comment by chrismccord** [comment]
@mcrumm Not sure where we landed on this one. Can you own it? Thanks!
