### ISSUE TITLE
Production logger is not reliable

### ISSUE THREAD

**Issue by liamwhite** [phoenixframework/phoenix#3642]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.11 (Hex package) (mix)
* NodeJS version (node -v): v12.13.1
* NPM version (npm -v): 6.12.1
* Operating system: Linux amd64

### Expected behavior
It is possible to crash [my app](https://github.com/derpibooru/philomena)'s endpoint by visiting certain URLs with invalid parameters, like passing strings where integer ids are intended to be passed. This is fine and expected.

When the endpoint crashes, the error should be logged in the console. This occurs in development mode and when running in production mode locally.

### Actual behavior
In production, errors are not reliably logged to the application console. In order to get consistent log output, some errors have to be manually rescued, inspected, and reraised. Sometimes, they are logged, which makes it all the more baffling.

```elixir
  rescue
    e ->
      IO.inspect(e, limit: :infinity)
      IO.inspect(__STACKTRACE__, limit: :infinity)
      reraise e, __STACKTRACE__
```
After the reraise process, the error is not logged. The type of error doesn't seem to matter.
```
iex(philomena@127.0.0.1)1> %Ecto.Query.CastError{
  message: "/home/philomena/philomena/lib/philomena_web/controllers/conversation_controller.ex:17: value `\"foo\"` in `where` cannot be cast to type :id in query:\n\nfrom c0 in Philomena.Conversations.Conversation,\n  join_lateral: f1 in fragment(\"SELECT COUNT(*) FROM messages m WHERE m.conversation_id = ?\", c0.id),\n  on: true,\n  where: c0.from_id == ^380748 and c0.to_id == ^\"foo\" and not(c0.from_hidden) or c0.to_id == ^380748 and c0.from_id == ^\"foo\" and not(c0.to_hidden),\n  select: count(\"*\")\n",
  type: :id,
  value: "foo"
}
[
  {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1948]},
  {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3,
   [file: 'lib/enum.ex', line: 1440]}
]
```
(Empty afterwards, error is never logged by Phoenix)

[Code in question](https://github.com/derpibooru/philomena/blob/a3b3a38fef199fcd491494b7b4c5595f09200317/lib/philomena_web/controllers/conversation_controller.ex#L13-L19)

The logger is not entering discard mode. No warnings are presented that suggest this, and manual verification confirms it isn't discarding anything:
```
iex(philomena@127.0.0.1)2> :erlang.whereis(Logger)
#PID<0.2374.0>
iex(philomena@127.0.0.1)3> pid = v(2)
#PID<0.2374.0>
iex(philomena@127.0.0.1)4> Process.info(pid, :message_queue_len)
{:message_queue_len, 0}
iex(philomena@127.0.0.1)5> :sys.get_state(pid)
[
  {Logger.Backends.Console, false,
   %Logger.Backends.Console{
     buffer: [],
     buffer_size: 0,
     colors: %{
       debug: :cyan,
       enabled: false,
       error: :red,
       info: :normal,
       warn: :yellow
     },
     device: :user,
     format: [:time, " ", :metadata, "[", :level, "] ", :message, "\n"],
     level: nil,
     max_buffer: 32,
     metadata: [:request_id],
     output: nil,
     ref: nil
   }},
  {Logger.Config, false,
   {{:counters, {:atomics, #Reference<0.4013483561.627703810.116488>}}, :log,
    500, 30000}}
]
iex(philomena@127.0.0.1)6> require Logger
Logger
iex(philomena@127.0.0.1)7> Logger.warn("warn")
01:11:52.420 [warn] warn
:ok
```

At this point I am at a total loss as to how these errors are not being logged, and I have to conclude that it is a bug in the framework.

**Comment by chrismccord** [comment]
This is expected behavior in production as exceptions which implement the `Plug.Status` protocol are translated to HTTP responses, which is the case for `Ecto.Query.CastError`. Hope that helps. Thanks!

**Comment by liamwhite** [comment]
Could you inform me as to why they are not logged?

**Comment by tylersamples** [comment]
@liamwhite I believe I just encountered this as well. I don't think it's a Phoenix bug though. After a bunch of debugging I noticed that `Logger.Config`'s counter wasn't resetting (found it via:)
```
iex> {_, _, {{_, logger_counter}, _, _, _}} = Logger |> Process.whereis() |> :sys.get_state() |> List.last()
iex> :counters.get(logger_counter, 1)
0
```
If I would call `Logger.flush()` via IEX things would start logging again and this is the only time I would get the warn message about discarded messages. I tracked the leak of `Logger.Config` back to `Plug.ErrorHandler` where it calls `:erlang.raise/3`. My logger wasn't set for `handle_sasl_reports: true` so that message would get dropped but still incremented the `Logger.Config`'s counter. If the error would happen so many times in a row with no `Logger.info()`'s being called, it'd eventually get the counter above 500 (default discard threshold) and nothing would show up in logs. In my case I enabled `handle_sasl_reports: true` on logger and that works for me. I believe if you have single `Logger.info()` inside your `handle_errors/2` you can avoid this problem or `plug(Plug.Logger)` inside your `endpoint.ex`. It just has to print something before that counter gets maxed out. For anyone curious, I was trying to avoid logging 404 error messages, which is what ended up occurring so many times in a row it triggered this issue.

I did end up finding a comment from Jose that seems to indicate this can happen: https://github.com/elixir-lang/elixir/issues/9028#issuecomment-490449278. 

Hope that helps!
