### ISSUE TITLE
XML escaping is not used in RSS format EEx templates

### ISSUE THREAD

**Issue by liamwhite** [phoenixframework/phoenix#3647]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4
* Phoenix version (mix deps): phoenix 1.4.11
* NodeJS version (node -v): v12.14.0
* NPM version (npm -v): 6.13.4
* Operating system: Linux

### Expected behavior
[The following code](https://github.com/derpibooru/philomena/commit/4ac63f9f4ecada20853021b7204f4602c78d08d5), when used in an RSS format template, should escape its value:
```eex
<title>#<%= image.id %> - <%= image.tag_list_cache %></title>
```

### Actual behavior
Markup is passed through unchanged. If one specifies `image.tag_list_cache` to contain the string `:<`, it will render as
```rss
<title>#1 - :<</title>
```

**Comment by chrismccord** [comment]
The phoenix template engine is chosen based on the extension, so you get html escaping for *.html.eex templates because there is a Phoenix EEx html engine being used. Your `.rss.eex` template will use the regular built-in eex engine, which does no escaping. If you want the exact behavior of the HTML engine for rss, you can register the Phoenix html engine to pick up the rss extension in your `config/config.exs`:

      config :phoenix, :format_encoders,
        html: Phoenix.HTML.Engine,
        rss: Phoenix.HTML.Engine
