### ISSUE TITLE
mix phx.digest does not update static files

### ISSUE THREAD

**Issue by dopatraman** [phoenixframework/phoenix#3662]
### Environment

Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.0-dev (553b2b2) (compiled with Erlang/OTP 22)

* Phoenix version (mix deps):
```
phoenix 1.4.8 (Hex package) (mix)
  locked at 1.4.8 (phoenix) c72dc3ad
  ok
```
* NodeJS version (node -v): v 9.5.0
* NPM version (npm -v): 5.6.0
* Operating system: Ubuntu 18

### Expected behavior
`mix phx.digest` should update my static CSS files with the latest changes.

### Actual behavior
When I run `mix phx.digest`, my app.css file in priv/static does not have any of my changes. The timestamp on the file matches the time of the command.

**Comment by achempion** [comment]
Hi, Prakash.

`mix phx.digest` only generates digest on files you already have. It wouldn't trigger your node pipeline.

As en example, try to create any file under `priv/static` directory and run `mix phx.digest` after. You'll see a new file with its hash at the end of the name. That is what digest command does.

In order to provide files to digest you need to copy them to `priv/static` directory or specify input path for the digest command.

In your case, most likely you use `webpack` which will build you such files and will copy them to `priv/static` directory.

**Comment by dopatraman** [comment]
Interesting... thank you for explaining. Let me see if that works.

**Comment by dopatraman** [comment]
Worked. Thank you.
