### ISSUE TITLE
CRUD delete button not working

### ISSUE THREAD

**Issue by Dema323** [phoenixframework/phoenix#3854]
The Delete button worked at the beginning of my project. But somewhere along the line it stopped working. I saw some post that this might be because of Brunch but im not using this dependency.
Thanks for your time.

### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps):  1.4.17
* NodeJS version (node -v): 13.7.0
* NPM version (npm -v): 6.13.6
* Operating system: Windows

### Expected behavior
Using the CRUD generated from phoenix when pressing delete, getting a confirmation window and being able to delete the user.

### Actual behavior
When pressing delete going to the /show page.
[https://www.youtube.com/watch?v=NFdmKSOLyJ4](url)

**Comment by Gazler** [comment]
The delete button functionality is provided by the phoenix_html library, so please make sure you have the JavaScript included:

https://github.com/phoenixframework/phoenix_html/blob/v2.14.2/priv/static/phoenix_html.js

Since this isn't a Phoenix bug, I'm going to close this. Consider using one of the resources in https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#using-the-issue-tracker for additional help if required.
