### ISSUE TITLE
Docs: Rendering Templates outdated?

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix#3865]
### Environment
`{:phoenix, "~> 1.5.0"}`

### Expected behavior
Based on:
https://hexdocs.pm/phoenix/views.html#rendering-templates

`lib/hello_web/templates/layout/app.html.eex` contains `<title>Hello · Phoenix Framework</title>`.

### Actual behavior
`lib/hello_web/templates/layout/app.html.eex` contains:
```
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>
```
and it doesn't seem to be used anywhere.

**Comment by i-n-g-m-a-r** [comment]
I did use `mix phx.new myproject --live --no-ecto`, maybe that's why.
I searched for `app.html.eex` to find out what it's for, probably I should just delete it.

**Comment by halimnadergrace** [comment]
App.eex

**Comment by i-n-g-m-a-r** [comment]
I just created a "regular" controller and view resulting in a:
`Phoenix.Template.UndefinedError at GET /my-page-without-liveview`
```
Could not render "app.html" for MyProjectWeb.LayoutView
```
So I put `app.html.eex` back in `./templates/layout/` and suddenly it's contained in `root.html.leex`.
I didn't mention any app.html or LayoutView anywhere, these "things" appeared out of nowhere.
I don't understand why these "magical defaults" are hidden from me.
Anyway, I guess `app.html.eex` was waiting for me to create a controller/view.

**Comment by kelvinst** [comment]
Well, going back to the actual reason for the issue: Phoenix's guides are structured as a step by step tutorial, so you should not expect to take one step from the middle of it and fit on your own specific case, which is totally different as it is a live app, `app.html.eex` included.

About the layout confusion, it is a convention on Phoenix that all controllers apply to a default layout, if you want a view with no layout use `put_layout false` on your controller: https://hexdocs.pm/phoenix/Phoenix.Controller.html?#put_layout/2

**Comment by i-n-g-m-a-r** [comment]
Thanks Kelvin for your comment, I am aware of the convention.
I don't think it's a nice convention though to have hidden defaults and aliases imported by macros.
The zen of Python still hangs above my bed, even though I switched almost completely over to Elixir.
Anyway, I will close the issue, the next time I search for app.html.eex I will find the answer here.

**Comment by kelvinst** [comment]
Your point makes sense actually, IMO the convention should at least be explicit, as for example putting a `put_layout {MyAppWeb.LayoutView, "app.html"}` in the generated `MyAppWeb` module and set `:put_default_views` default value to `true`, instead of the actual convention of assuming there will be a given `MyAppWeb.LayoutView`, I will open a separate issue to discuss that too, as I agree that it would be better to be explicit about it.

**Comment by rokob** [comment]
Just for posterity because I could not for the life of me figure out where the app.html default was coming from, I finally found https://github.com/phoenixframework/phoenix/blob/v1.6.6/lib/phoenix/controller.ex#L170-L173

It would be helpful to do something here in the docs or be more explicit in the generated code. Also, this is the default using `mix phx.new whatever` so it isn't actually a special case. Following along in the step by step guide the first time you hear about the app layout is just a one liner that says luckily the application layout handles showing the flash messages. But nothing about why/how that is getting used.

**Comment by BishopOfTurkey** [comment]
> Your point makes sense actually, IMO the convention should at least be explicit, as for example putting a `put_layout {MyAppWeb.LayoutView, "app.html"}` in the generated `MyAppWeb` module and set `:put_default_views` default value to `true`, instead of the actual convention of assuming there will be a given `MyAppWeb.LayoutView`, I will open a separate issue to discuss that too, as I agree that it would be better to be explicit about it.

@kelvinst Did an issue end up being raised? Also had to do some digging while following the guide.
