### ISSUE TITLE
LiveViewTest fails with tests generated by mix phx.gen.live

### ISSUE THREAD

**Issue by abstractcoder** [phoenixframework/phoenix#3947]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 12.16.2
* NPM version (npm -v): 6.14.4
* Operating system: Mac OS 
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

```
** (ArgumentError) could not find non-disabled input, select or textarea with name "shopper[favorites]" within:
~snip~
         <select id="shopper_favorites" multiple="" name="shopper[favorites][]"><option value="option1">Option 1</option><option value="option2">Option 2</option></select>
~snip~
     code: |> render_change() =~ "can&apos;t be blank"
     stacktrace:
       (phoenix_live_view) lib/phoenix_live_view/test/live_view_test.ex:873: Phoenix.LiveViewTest.call/2
       test/test_app_web/live/shopper_live_test.exs:64: (test)
```
### Expected behavior

The tests generated by `mix phx.gen.live` fail when the schema contains columns with an array type or a date type. In the array case the selector that LiveViewTest is looking for `shopper[favorites]` is different than the selector being generated by the multiple_select  `shopper[favorites][]`

**Comment by josevalim** [comment]
Thanks @abstractcoder! I have moved the issue to the Phoenix repo. The fix should hopefully be straight-forward, we just need to check if the type is an array and generate a slightly different selector. :)

For completeness, can you please provide the full command that you ran?

**Comment by abstractcoder** [comment]
Sure thing, here is the generation command I ran.

```
mix phx.gen.live Shoppers Shopper shoppers favorites:array:string birth_date:date
```

Both the array and the date selectors will fail in the generated tests.

**Comment by feliperenan** [comment]
Hi 👋 

I would like to work on this issue if that is fine for you both 🙌 . As far as I get, all we need to do is to check the attribute type here:

https://github.com/phoenixframework/phoenix/blob/c8883af5582a38496e4b7e45e05d3a4d759a6caa/priv/templates/phx.gen.live/live_test.exs#L23

and change the assertion in case it is an array. However I wonder how this assert should be since it can be array, map, array of map, etc.. 🤔.

I saw that controllers tests don't add this assertion at all:

https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.html/controller_test.exs#L13

Maybe we could do the same here for other types other than normal attributes 🤔 

What do you think?

**Comment by josevalim** [comment]
@feliperenan please go ahead! Since this is an "array", it may be that we don't show it at all in the ShowLive. if that's the case, then the best is indeed to not assert it here either, like we do for controller tests.

**Comment by feliperenan** [comment]
@josevalim After going deeper to this issue I realized we have three issues here, so I will try to share my findings here before opening the PR.

####  1) Wrong assertion when a field is an array:

```Elixir
    test "lists all shoppers", %{conn: conn, shopper: shopper} do
      {:ok, _index_live, html} = live(conn, Routes.shopper_index_path(conn, :index))

      assert html =~ "Listing Shoppers"
      assert html =~ shopper.favorites
    end
```

This can be solved by removing the second assertion as said above. BTW, I noticed that if we ensure that `schema.string_attr` only returns a string we don't need any extra condition there and, as far as I get, we can do that just removing this line:

https://github.com/phoenixframework/phoenix/blob/c8883af5582a38496e4b7e45e05d3a4d759a6caa/lib/mix/phoenix/schema.ex#L295

That make sense to me since `{:array, :string}` is not a string but an array of strings.

####  2) Wrong name selector when field is an array:

```Elixir
# favorites was supposed to be an empty array
@invalid_attrs %{birth_date: nil, favorites: nil}

test "updates shopper in listing", %{conn: conn, shopper: shopper} do
  # ...
  assert index_live
         |> form("#shopper-form", shopper: @invalid_attrs)
         |> render_change() =~ "can&apos;t be blank"
  # ...
end
```

This test breaks as described in the issue since it tries to find `"shopper[favorites]"` instead of `"shopper[favorites][]"`.

This can be solved if we ensure that fields that is a list will have an empty list instead of `nil` with something like this:

* change from:
https://github.com/phoenixframework/phoenix/blob/c8883af5582a38496e4b7e45e05d3a4d759a6caa/priv/templates/phx.gen.live/live_test.exs#L9

* to:
```Elixir
  @invalid_attrs <%= inspect for {key, value} <- schema.params.create, into: %{}, do: if is_list(value), do: {key, []}, else: {key, nil} %>
```

####  2) Wrong selector when field is date

Since the generator uses `date_select/3`:

```Elixir
  # form_component.html.eex
  <%= date_select f, :birth_date %>
```

The HTML generated for this date will be three selects with the respective names: `shopper[birth_date][day]`, `shopper[birth_date][month]` and `shopper[birth_date][year]`. Therefore, the date inside the fixtures should be a map `%{month: 04, day: 17, year: 2020}` instead of a date: `~D[2010-04-17]`.

But, if we would need to ensure that `@invalid_attrs` will also send this map format instead of nil otherwise those tests will still fail for the same reason:

```
  1) test Show updates shopper within modal (NewProjectWeb.ShopperLiveTest)
     test/new_project_web/live/shopper_live_test.exs:84
     ** (ArgumentError) could not find non-disabled input, select or textarea with name "shopper[birth_date]" within:
     ...
```

The easiest solution for this one would be generating the form with `date_input/3` instead. So we wouldn't need to change the date format in the test generator and, `@invalid_attrs` could have date as nil.

Please, let me know if that make sense to you. You might have a better idea for solving these three issues 🙌

**Comment by josevalim** [comment]
Agreed on all fronts. However, if we change to use date_input/3, I would change it on all generators and for all datetime inputs. :)

**Comment by josevalim** [comment]
Closing in favor of PR. :)

**Comment by CodyPerakslis** [comment]
Hello,

I had the same array issue with phoenix v1.5.8 and phoenix_live_view v0.15.1.

Using this thread, I was able to resolve the issue of nil invalid_attrs, empty valid_attrs, missing asserts with arrays, and different render strings. I am attaching a diff with my changes. 

I was only able to use array values that are hardcoded in to `lib/$APP_web/live/$TYPE_live/form_component.html.leex`.

Here is the diff:

```
@@ -5,9 +5,9 @@ defmodule QuotableWeb.PostLiveTest do

   alias Quotable.Quotes

-  @create_attrs %{body: "some body", category: [], context: "some context", speaker: []}
-  @update_attrs %{body: "some updated body", category: [], context: "some updated context", speaker: []}
-  @invalid_attrs %{body: nil, category: nil, context: nil, speaker: nil}
+  @create_attrs %{body: "some body", category: ["option1"], context: "some context", speaker: ["option1"]}
+  @update_attrs %{body: "some updated body", category: ["option2"], context: "some updated context", speaker: ["option2"]}
+  @invalid_attrs %{body: nil, category: [], context: nil, speaker: []}

   defp fixture(:post) do
     {:ok, post} = Quotes.create_post(@create_attrs)
@@ -39,7 +39,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert index_live
              |> form("#post-form", post: @invalid_attrs)
-             |> render_change() =~ "can&apos;t be blank"
+             |> render_change() =~ "can&#39;t be blank"

       {:ok, _, html} =
         index_live
@@ -49,6 +49,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert html =~ "Post created successfully"
       assert html =~ "some body"
+      assert html =~ "option1"
     end

     test "updates post in listing", %{conn: conn, post: post} do
@@ -61,7 +62,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert index_live
              |> form("#post-form", post: @invalid_attrs)
-             |> render_change() =~ "can&apos;t be blank"
+             |> render_change() =~ "can&#39;t be blank"

       {:ok, _, html} =
         index_live
@@ -71,6 +72,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert html =~ "Post updated successfully"
       assert html =~ "some updated body"
+      assert html =~ "option2"
     end

     test "deletes post in listing", %{conn: conn, post: post} do
@@ -101,7 +103,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert show_live
              |> form("#post-form", post: @invalid_attrs)
-             |> render_change() =~ "can&apos;t be blank"
+             |> render_change() =~ "can&#39;t be blank"

       {:ok, _, html} =
         show_live
@@ -111,6 +113,7 @@ defmodule QuotableWeb.PostLiveTest do

       assert html =~ "Post updated successfully"
       assert html =~ "some updated body"
+      assert html =~ "option2"
     end
   end
 end
```

Please let me know if I am way off somewhere. If not, I hope this helps.
