### ISSUE TITLE
Invalid Endpoint.url() when using dynamic listening port 

### ISSUE THREAD

**Issue by dominicletz** [phoenixframework/phoenix#4186]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Node.js version (node -v): v12.16.1
* NPM version (npm -v): v6.14.7
* Operating system: Ubuntu 18.04.5 LTS

### Expected behavior
When using a dynamic port calling `WebApp.Endpoint.url()` should still return a valid url. 

```
config :ddrive, WebApp.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 0]
```

`WebApp.Endpoint.url()` should return e.g. `"http://localhost:46815"`

### Actual behavior
`WebApp.Endpoint.url()` does always return "http://localhost:0"

I can use `ranch:get_port(WebApp.Endpoint.HTTP)` to get the correct dynamically allocated port e.g. `46815` and confirm that the site is actually running there. But  `WebApp.Endpoint.url()` always returns the wrong url.

**Comment by dominicletz** [comment]
My current ugly workaround on my desktop webapp is this:

```elixir
defmodule WebApp.Endpoint do
  def url do
    url = Phoenix.Config.cache(__MODULE__, :__phoenix_url__, &Phoenix.Endpoint.Supervisor.url/1)
    String.replace(url, ":0", ":#{:ranch.get_port(WebApp.Endpoint.HTTP)}")
  end

  use Phoenix.Endpoint, otp_app: :ddrive
```

e.g. I'm overwriting the default endpoint.url() call with my ugly patched one to inject the right url

**Comment by josevalim** [comment]
We don't really support dynamic ports at the moment.

It is also worth nothing there are two distinct configurations:

1. Which URL to listen on (http/https)
2. Which URL to show to your users

If you don't configure 2, we will use 1 by default. The fix is to add this config:

    url: [host: "localhost", port: 80]

If someone wants to submit a pull request that actually supports dynamic ports efficiently, we will gladly take a look at, but not in our plans. Thanks!
