### ISSUE TITLE
Starting a new project fails without Python 2 installed

### ISSUE THREAD

**Issue by robotmay** [phoenixframework/phoenix#4308]
### Environment

* Elixir version (elixir -v): 1.11.4
* Phoenix version (mix deps): 1.5.8
* Node.js version (node -v): 15.11.0
* NPM version (npm -v): 7.6.0
* Operating system: Ubuntu 20.10

### Expected behavior

Starting a new project should boot first time

### Actual behavior

Fails to build the assets because `node-sass` has a hard dependency on Python 2, which isn't installed by default on newer Ubuntu versions (and likely other distros). This is likely because `node-sass` is actually deprecated in favour of the Dart variety packaged under `sass`, and I presume no longer updated.

I swapped the dependency locally to `sass` and it seems to compile and build fine :+1:

**Comment by sdenier** [comment]
Just a follow-up since I had a slightly different take.

- upgraded from Node 14 to Node 16 and ran into the above issue.
- Tried to install sass instead but then ran into `error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?` 
- it appears neither sass/node-sass are ready for Node 16 so rollback to Node 14 LTS https://stackoverflow.com/a/67303155

Hopefully these problems will disappear soon with #4310

**Comment by robotmay** [comment]
Ah I see what you mean now :+1: In that case it might be worth documenting this dependency somewhere on the new project generator in case others run into this issue, until the sass dependency is removed.
