### ISSUE TITLE
Add phx.gen.socket SocketModule

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4376]
They have been removed from phx.new. It should generate the socket file and a .js file if assets exist. Channel and presence guides need to be updated.

**Comment by josevalim** [comment]
At the end, this needs to be added to endpoint:

```
socket "/socket", <%= @web_namespace %>.UserSocket,
    websocket: true,
    longpoll: false
```

**Comment by philss** [comment]
I can take this one :)

**Comment by chrismccord** [comment]
We may also consider adding this functionality to `phx.gen.channel` which already exists and it can create the `UserSocket` (or flag for socket module name) if it doesn't exist w/ instructions for the endpoint? This approach gets bonus points too because we could add the first channel definition to the created socket module matching the channel module. Thoughts?

**Comment by philss** [comment]
@chrismccord good point! I added a suggestion when the default `UserSocket` file does not exist. I liked the idea to create the socket file matching the channel name, but for each channel we would create a new socket file, right? I can change the task if you think this is preferable. Please let me know! :)

**Comment by josevalim** [comment]
Closing this in favor of PR!
