### ISSUE TITLE
Phoenix.Token documentation recommends passing the token in the clear via uri

### ISSUE THREAD

**Issue by treeman** [phoenixframework/phoenix#4391]
I wanted to use `Phoenix.Token` to authenticate my channel and saw that [the documentation](https://hexdocs.pm/phoenix/Phoenix.Token.html) recommends passing the token as an uri parameter.

Isn't this unsafe and can be vulnerable to man-in-the-middle attacks? Perhaps it would be better to steer people towards passing authentication over headers?

See [this answer](https://github.com/NFIBrokerage/slipstream/issues/39#issuecomment-887477072) in the Slipstream repo that prompted me to open this ticket, which contains example code for passing the token using x-headers.

**Comment by chrismccord** [comment]
This is not any different, unsafe, or "in the clear" wrt to man-in-middle than headers. You should be using TLS to have a secure connection to prevent leaking tokens, and headers are sent just as in the clear as tokens if we're talking purely HTTP vs HTTPS traffic. The proxy concern is also no different since the request headers and parameters are both traveling thru the proxy. The concern about logging sensitive parameters is valid, but you can just as easily log headers so care must always be taken when talking about your greater logging strategies and offloading these things to an external vendor. Phoenix includes the `filter_parameters` configuration to avoid leaking parameters when we instrument/log throughout the framework:

```
  When logging parameters, Phoenix can filter out sensitive parameters
  such as passwords and tokens. Parameters to be filtered can be
  added via the `:filter_parameters` option:

      config :phoenix, :filter_parameters, ["password", "secret"]

```

The last point for consideration is the `WebSocket` JavaScript API does not allow setting headers, so query parameters are your only option. If you have a non-js client that can set headers, then absolutely feel free to use the `connect_info` option to pass the headers to the transport :) Thanks!

**Comment by treeman** [comment]
Alright, then all is good. Sorry for taking your time, and thanks!
