### ISSUE TITLE
Server won't start until I restart the computer

### ISSUE THREAD

**Issue by mathieuprog** [phoenixframework/phoenix#4410]
### Environment

* Elixir version (elixir -v):
> Erlang/OTP 22 [erts-10.7] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
> Elixir 1.11.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 
> phoenix 1.5.9
* Node.js version (node -v): 
> v12.16.1
* Operating system:
> Windows 10

----------------

When running
> mix phx.server

I have the log

> Generated my_app app

and then... nothing. No further log as usual and server isn't started. No error messages.

I need to restart my computer frequently (works after restart). I didn't notice any other program misbehaving.
How should I debug this problem?

**Comment by cadebward** [comment]
@mathieuprog I've noticed this happens when I've misconfigured something. For example, it happened a few months ago when I was setting up the libcluster library. When it wasn't configured correctly, it would block my server from starting completely. Another spot to check is that you have `server: true` set for your endpoint config.

Check if you've made some changes recently that might effect this. Rolling back some recent changes and testing `mix phx.server` would be a good way to debug. If you still need help, maybe posting some code from your config or `application.ex` file would help.

**Comment by dvic** [comment]
>  For example, it happened a few months ago when I was setting up the libcluster library. When it wasn't configured correctly, it would block my server from starting completely.

This happened to me as wel when I configure the `epmd`strategy in dev while `epmd` is not running (it either crashed or did not start). Simply running `epmd` in your command line makes the app start up again.

**Comment by mathieuprog** [comment]
For argon2 to compile on windows I am used to launch this command:
> cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\vsdevcmd" -arch=x64

It has worked for over a year without a problem, but suddenly it seems it might cause the issue now.

I'm going to wait a few more days to confirm that before I close this issue.
I can compile argon2 after running this command, but then I can close/re-open the command line tool and run the phoenix server in the normal environment.

**Comment by cw789** [comment]
If you really had hit an "using Erlang NIF (argon2) on Windows" issue.
I've tried to sum up the important things about this topic for Exqlite → [Exqlite - Windows users](https://hexdocs.pm/exqlite/windows.html).

By the way your command above seems to be fine, so I have no clue where your issue lays down.
But if you find out anything new, I would be interested.

PS: The Elixir windows users would probably benefit if we would make the "Windows users" guide for using NIFs more visible community wide.
It would probably fit anywhere to https://github.com/elixir-lang/elixir_make?
