### ISSUE TITLE
Fix Gigalixir deployment guide

### ISSUE THREAD

**Issue by filiptelak** [phoenixframework/phoenix#4474]
### Environment

* Elixir version 1.12.2:
* Phoenix version 1.6.0-rc.0:

### Expected behavior
Successfully deploying app to Gigalixir following the guide [Deploying on Gigalixir](https://hexdocs.pm/phoenix/1.6.0-rc.0/gigalixir.html#content)

### Actual behavior
`echo 'hook_post_compile="mix assets.deploy && rm -f _build/esbuild"' >> elixir_buildpack.config` specifies the wrong buildpack
![Screen Shot 2021-09-10 at 3 21 18 PM](https://user-images.githubusercontent.com/72954601/132911148-5b9f169d-2f3b-40b6-b7fc-e71727e52f94.png)

Additionally, I discovered that if you have NPM packages installed using an `assets/package.json` file, you must add a `deploy` script to it. 
![Screen Shot 2021-09-10 at 4 14 07 PM](https://user-images.githubusercontent.com/72954601/132912369-6aaf06a0-df07-482b-9b6a-583763ee2288.png)

I used the following script:
```
{
  ...
  "scripts": {
    "deploy": "cd ..; mix assets.deploy; cd assets;"
  }
  ...
}
```

I wonder if there's a better way to write this deployment script? Regardless, my P/R fixes these issues.

**Comment by josevalim** [comment]
@jesseshieh what are your thoughts here? Phoenix v1.6.0 no longer requires NPM and I think Gigalixir uses the static buildpack by default. Is this correct? If so, should we be telling users to never run `mix assets.deploy` on Gigalixir?

**Comment by jesseshieh** [comment]
Oh interesting. When I tested Phoenix 1.6 myself, it deployed fine using the hook instructions you added. I'll try and test this again, but does this error happen on the default generated app, or only if you add extra dependencies?

**Comment by filiptelak** [comment]
@jesseshieh it only happens when adding extra dependencies. Otherwise, it works fine.

**Comment by jesseshieh** [comment]
Gotcha. Let me spend some time on this and try to reproduce it and get a better understanding of what's happening.

**Comment by jesseshieh** [comment]
I was able to reproduce this by [adding alpinejs](https://github.com/gigalixir/gigalixir-getting-started/compare/js/phx-1-6...js/phx-1-6-assets?expand=1) following https://github.com/josevalim/phx_esbuild_demo/pull/3. 

I think the basic issue here is that there are now [two paths](https://github.com/phoenixframework/phoenix/blob/7dc93ab6119e3a7978029738b52de9f593c068ba/guides/asset_management.md#third-party-js-packages) for managing third-party dependencies. You can vendorize or use `npm install`.

If you vendorized, then you probably won't have an `assets/package.json` and the static buildpack won't be run. Gigalixir only runs the static buildpack if it detects an `assets/package.json`. NPM won't be installed, `npm install` won't be run, and everything should work great with the post compile hook.

If you use `npm install` however, `npm install` needs to be run *before* `mix assets.deploy`.  This explains why running `mix assets.deploy` in the elixir buildpack throws an error in the original post above.

I think perhaps the proper solution is to modify the elixir buildpack to run `mix assets.deploy` only if there is no `assets/package.json` found. Then modify the static buildpack to run `mix assets.deploy` instead of `npm run deploy` if it detects Phoenix 1.6.

A potentially easier solution, following @filiptelak's pull request, would be to have users generate an "empty" package.json file like this to conform to the old "standard" of running `npm install` and then `npm run deploy`. Then no buildpack changes are necessary.
```
{
  "scripts": {
    "deploy": "cd ..; mix assets.deploy; cd assets;"
  }
}
```

It might even possibly make sense to add this "empty" package.json file to the phoenix generators for the sake of backward compatibility? =)

**Comment by nevakrien** [comment]
> @jesseshieh what are your thoughts here? Phoenix v1.6.0 no longer requires NPM and I think Gigalixir uses the static buildpack by default. Is this correct? If so, should we be telling users to never run `mix assets.deploy` on Gigalixir?

I am a beginer just downloaded phinix on the newst stable version and I tried to push the project to this service and it was mad at me so... idk it would help
