### ISSUE TITLE
multiple issues when rewrite url

### ISSUE THREAD

**Issue by 6aKa** [phoenixframework/phoenix#4527]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): v1.6.0
* Operating system: MasOS

### Problem
Create new empty phoenix project.
Add `url: [path: "/admin"]` in Endpoint configuration.
In Endpoint module fix urls for socket and `Plug.Static`
In Router module change all `scope "/"` to `scope "/admin`

### Expected behavior
LiveReload just work
LiveDashboard just work
console output `[info] Access Test.Endpoint at http://localhost:4000/admin`

### Actual behavior
`http://localhost:4000/admin/phoenix/live_reload/frame` - not found, live reload not wokring
Wrong URL for `LiveDashboard` `http://localhost:4000/admin/admin/dashboard`
`[info] Access Test.Endpoint at http://localhost:4000` - console output without `path`

**Comment by josevalim** [comment]
Hi @6aKa, `url: [path: "/admin"]` only works if you put it behind a proxy/nginx/apache so that it automatically strip and handle the "/admin" for you. The goal of setting the path is to say that: "hey, you don't know this, but you are under a /admin route, and therefore you should add such prefix to all of your paths". It is not going to work if you are running and directly accessing the app yourself.
