### ISSUE TITLE
Add an umbrella app to extra_application within another app without defining dep should display error.

### ISSUE THREAD

**Issue by mjcloutier** [phoenixframework/phoenix#4575]
I added a phoenix app within an umbrella to extra_application within another phoenix app within umbrella, and the dep was removed and not defined. Due to having many un-staged changes pending it was difficult to find at fist glance. When starting the umbrella app, the project would hang and only display the message:

`:alarm_handler: {:set, {:system_memory_high_watermark, []}}`

It would be great to have an error message for this scenario as it becomes difficult to diagnose when it fails silent and hangs indefinite.

### Environment

* Elixir version (1.11.4):
* Phoenix version (1.5.9):
* Operating system: MacOS Monterey 12.0.1

### Expected behavior

If you add an app within an umbrella project to extra_applications, not as a dep, and forget it is there, the application should display an error or warning when starting mix phx.server.

### Actual behavior

If you add an app within an umbrella project to extra_applications, not as a dep and forget it is there, the application will fail silently when running mix phx.server. It shows no errors and will not compile.

**Comment by josevalim** [comment]
I have looked into this and it seems the code actually worked. :) You can depend on other Phoenix applications, and adding it to extra_applications is not a problem, the issue is that it won't be configured to serve anything, so you have all of the services in your Phoenix application, but the HTTP endpoints are not started.

Given this can be a legit use case (i.e. you can depend on another app but not have it serve anything), I believe we should not do anything here. Thanks!
