### ISSUE TITLE
High memory usage cowboy_clear:connection_process/4

### ISSUE THREAD

**Issue by phanmn** [phoenixframework/phoenix#4613]
### Environment

* erlang: 24.1
* elixir: 1.12.3
* Cowboy: 2.9.0
* plug_cowboy: 2.5.2
* phoenix: 1.6.2
* OS: macOS Monterey

### Expected behavior
No high memory usage

### Actual behavior
<img width="843" alt="Screen Shot 2021-11-26 at 00 52 38" src="https://user-images.githubusercontent.com/3765536/143511696-3d7496cd-16da-485a-abab-76e63d3c6f7b.png">

Need to run manually `Process.list |> Enum.each(&:erlang.garbage_collect/1)` to fix the issue

Please help, thanks!

**Comment by josevalim** [comment]
You are likely handling large payloads in your channels. If you can identify what channels are the root cause, then you can force the socket for those particular channels to garbage collect by sending them a message. See the docs here:

https://hexdocs.pm/phoenix/Phoenix.Socket.html#module-garbage-collection

For more assistance, I recommend the [ElixirForum](http://www.elixirforum.com) or StackOverflow, where a wider community will be able to help you.

**Comment by josevalim** [comment]
I just pushed another option that should be more stable, check this out: https://github.com/phoenixframework/phoenix/commit/bd567cd8dee1793c72a8e8746f2d1be4a69ae885

It requires Erlang/OTP 24 and Phoenix master. :)

**Comment by phanmn** [comment]
Thank you so much!
