### ISSUE TITLE
Returning custom WS close code with Phoenix Socket/Channels

### ISSUE THREAD

**Issue by svsool** [phoenixframework/phoenix#4822]
Hi,

Is it possible to return custom WS close code mentioned [here](https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_websocket/) as part of the termination reason from anywhere in the app?

![image](https://user-images.githubusercontent.com/1452141/167604340-45e735e7-e49f-4fe3-b839-eaa5c58d04a7.png)

The reason where it could be useful is for our clients to react in a specific way (f.ex. stop retries) when close event with certain close code is returned, it seems that web implementation of web sockets [does not allow to catch http status code](https://stackoverflow.com/questions/21762596/how-to-read-status-code-from-rejected-websocket-opening-handshake-with-javascrip/50685387#50685387) which currently can be configured via `:error_handler`, only WS close code.

![image](https://user-images.githubusercontent.com/1452141/167603584-fa9d8262-792a-4a34-a5a6-ca42cf298a74.png)

Considering [specification](https://www.rfc-editor.org/rfc/rfc6455#section-7.4.2) we could for example consider utilizing 4xxx codes.

Thank you!

**Comment by chrismccord** [comment]
I don't believe the close code is relevant to the initial WebSocket upgrade (101 Switching Protocols), so in that respect it won't help you if that's what you are after. Since channel transports are agnostic to the protocol, we don't expose close codes directly. You can however push any event you would like after connect, and use that to drive client behavior. Thanks!
