### ISSUE TITLE
Using persistent_term for routes

### ISSUE THREAD

**Issue by Fudoshiki** [phoenixframework/phoenix#5126]
### Environment

* Phoenix version (mix deps): main
* Operating system:

### Expected behavior

I added `upgrade_dispatch()` to `start` **def** in `MyApp.Application`

```elixir

def start(_type, _args) do
  upgrade_dispatch()
 
  ...

  Supervisor.start_link(children, opts)
end

# Store the routes in persistent_term. This may give a performance improvement
 # when there are a large number of routes
 # See https://ninenines.eu/docs/en/cowboy/2.9/guide/routing
 defp upgrade_dispatch do
    dispatch = :cowboy_router.compile([{:_, [{:_, Phoenix.Endpoint.Cowboy2Adapter, {MyAppWeb.Endpoint, []}}]}])
    :persistent_term.put(:my_app_dispatch, dispatch)
 end
```

### Actual behavior

It doesn't work now coz `Cowboy2Handler` was deleted by https://github.com/phoenixframework/phoenix/commit/623ea995ddfd60e8d912b0af137351ee1a32f913

**Comment by Gazler** [comment]
This is kind of reaching into private APIs since the handler modules are `@moduledoc false`, so not entirely supported from the Plug/Phoenix side, but you should be able to change it to:

`Plug.Cowboy.Handler` instead of `Phoenix.Endpoint.Cowboy2Adapter` which is what is used here https://github.com/elixir-plug/plug_cowboy/blob/a20571d1ab0a57fca902b92c45ed58ee82c55a09/lib/plug/cowboy.ex#L352

The change was present in this commit https://github.com/phoenixframework/phoenix/commit/06b314e8845ba98670df5da33d0157642e2ed42e#diff-d939a953683e8fcff02626d9d2e4f3a473107a977eddf6bf043117a2eded463f
