### ISSUE TITLE
mix tasks phx.gen.live/html generate broken heex templates when given map type attributes

### ISSUE THREAD

**Issue by codeanpeace** [phoenixframework/phoenix#5235]
Suggestion for a small improvement, skip over map data type attributes from jsonb columns that currently cause the mix tasks `phx.gen.live` and `phx.gen.html` to generate broken heex templates. For `phx.gen.live`, visiting the show and index pages results in the error "protocol Phoenix.HTML.Safe not implemented for %{...} of type Map." And here's a related [old stackoverflow question](https://stackoverflow.com/questions/35549618/mix-phoenix-gen-html-with-map-field-type) on this. 
current: `<%= for {k, _} <- schema.attrs do %> `

proposed: `<%= for {k, v} when not is_map(v) <- schema.attrs do %>` see: [draft PR](https://github.com/phoenixframework/phoenix/pull/5234/files)

**Comment by Gazler** [comment]
I think this issue is a symptom of the general lack of support for maps (and lists probably) by the generator. Fixing this issue will fix the error, but users will still be stuck with the default form as they will be unable to submit the map field.

It might be worth looking at enhancing the generators to support map and array data types for forms as well as viewing the data in the index and show templates.

**Comment by codeanpeace** [comment]
👋 There was a bit [more discussion in the draft PR](https://github.com/phoenixframework/phoenix/pull/5234) where that came up, but I haven't taken another look since well before the generators were updated to support streams.

Off the top of my head, enhancing the generated forms to handle map and array data types will likely require casting of some sort.

**Comment by Gazler** [comment]
I think it is very unlikely that we'll capture the correct behaviour for the user from the generators here. I propose instead that we don't show form fields or validations for the `map` and `list` types. We can still include them in the JSON generators.
