### ISSUE TITLE
Support arbitrary module name capitalization

### ISSUE THREAD

**Issue by ammmir** [phoenixframework/phoenix#536]
I'd like to use a module name capitalized as "ABfoo" instead of "Abfoo". If you create a new project and rename all the generated "Abfoo" to "ABfoo" Phoenix fails to start:

```
15:18:17.838 [error] beam/beam_load.c(1250): Error loading module 'Elixir.Abfoo.Router':
  module name in object code is Elixir.ABfoo.Router

15:18:17.840 [error] Loading of /private/tmp/abfoo/_build/dev/lib/abfoo/ebin/Elixir.Abfoo.Router.beam failed: :badfile
```

**Comment by joshuaclayton** [comment]
@chrismccord I just ran into a similar error with a dependency, specifically https://github.com/elixytics/ua_inspector:

```
mix ua_inspector.download.databases                                                          ☺ 2.2.2

23:10:05.536 [error] Loading of /Users/joshuaclayton/dev/personal/redirect_to/_build/dev/lib/ua_inspector/ebin/Elixir.Mix.Tasks.UAInspector.Download.Databases.beam failed: :badfile


23:10:05.536 [error] beam/beam_load.c(1278): Error loading module 'Elixir.Mix.Tasks.UAInspector.Download.Databases':
  module name in object code is Elixir.Mix.Tasks.UaInspector.Download.Databases

** (UndefinedFunctionError) undefined function: Mix.Tasks.UAInspector.Download.Databases.run/1 (module Mix.Tasks.UAInspector.Download.Databases is not available)
    Mix.Tasks.UAInspector.Download.Databases.run([])
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

Having configured based on their readme, is there anything else I could do to get this to work?

**Comment by chrismccord** [comment]
@joshuaclayton what happens if you edit your `/deps/ua_inspector` repo and change this line
https://github.com/elixytics/ua_inspector/blob/master/mix.exs#L8
to `app:           :u_a_inspector`, then `mix deps.compile ua_inspector` ?

**Comment by joshuaclayton** [comment]
@chrismccord appreciate the quick response! I've made the update but am seeing a new error:

```
mix ua_inspector.download.databases                                                          ☹ 2.2.2
Unchecked dependencies for environment dev:
* ua_inspector (Hex package)
  could not find an app file at _build/dev/lib/ua_inspector/ebin/ua_inspector.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

I'm admittedly new to Elixir, but I'd also tried to update the deps `app` in `ROOT/mix.exs` to reflect the new name:

```
{:ua_inspector, "~> 0.9", app: :u_a_inspector},
```

It didn't have any impact on the output, and I've confirmed that it's generating `u_a_inspector.app` in the appropriate directory.

Would it help if I create a new repo to reproduce?

**Comment by josevalim** [comment]
Phoenix does not impose any naming rules. If you are having conflicts like above, is because you are defining a module named "ABC" and calling it as "ABc" or something of sorts. As long as you are consistent, you should be fine.

Regarding ua_inspector, Mix does impose names for its tasks, which Elixir version are you using?

**Comment by joshuaclayton** [comment]
@josevalim I'm on 1.1.1 for Elixir+Mix. I'm able to recreate on this repo: https://github.com/joshuaclayton/ua-inspector-phoenix-debug

**Comment by mneudert** [comment]
@joshuaclayton To chime in on the problem regarding UAInspector:

The problem you encountered was created initially after Elixir 1.0.2 (elixir-lang/elixir#2891 I think) changed the way of resolving task names with underscores. However my hack around this was too hacky and depended on (case sensitive!) two beam files:

- Mix.Tasks.UAInspector.Download
- Mix.Tasks.UaInspector.Download

This worked perfectly fine on my system.

But as brought to my attention in elixytics/ua_inspector#2 it obviously breaks when using a case insensitive file system. Like Windows or (most?) MacOS installations.

This has since been fixed and should not be a problem anymore :)
