### ISSUE TITLE
Problem using `warn_on_verify` on a catch-all route

### ISSUE THREAD

**Issue by jsonmaur** [phoenixframework/phoenix#5451]
### Environment

* Elixir version: 1.14.3
* Phoenix version: 1.7.2
* Operating system: macOS 13.3.1

### Expected behavior

I may be using `warn_on_verify` wrong, but from what I understand, it should log a warning for any verified route URLs that would be handled by that particular route. So I _should_ be able to define a "catch-all" route to act as a custom 404 handler like so:

```elixir
scope "/", MyAppWeb do
  pipe_through :browser

  get "/", PageController, :home
  get "/*path", PageController, :not_found, warn_on_verify: true
end
```

The routes match as expected and the custom 404 page is displayed. Creating a link to `~p"/"` should not log any warnings, since it would be handled by the first route and never make it to the second.

### Actual behavior

The following warning is logged when creating a link to `~p"/"`:

```
warning: no route path for MyAppWeb.Router matches "/"
```

**Comment by phoebe100** [comment]
I think your expected behavior is correct.

The current implementation in lib/phoenix/router.ex ignores the "top to bottom" order in your router. The reason is the usage of Enum.group_by/3 during the creation of the "__verify_route__/1" functions.
As a result, the macro creates the most general __verify_route__/1 function on first position resulting in the mentioned warning for all routes.
