### ISSUE TITLE
Session fixation attacks and the ‘remember me’ cookie

### ISSUE THREAD

**Issue by jbcaprell** [phoenixframework/phoenix#5466]
Hey, guys! My day job is in maintaining a bunch of WordPress sites—I’m basically just a hobbyist here—but I wanted to flag this in case it was a problem.

For any given project utilizing `phx.gen.auth`, when a user logs in (and out), the session is erased to avoid [session fixation attacks](https://owasp.org/www-community/attacks/Session_fixation), which happens here:

https://github.com/phoenixframework/phoenix/blob/3f671d7aee310465a57ff5c626f7ca1e44897589/priv/templates/phx.gen.auth/auth.ex#L62-L66

https://github.com/phoenixframework/phoenix/blob/3f671d7aee310465a57ff5c626f7ca1e44897589/priv/templates/phx.gen.auth/auth.ex#L28-L37

… but that doesn’t happen when a user is authenticated via an exisiting ‘remember me’ cookie; the token in the signed cookie is put directly into the existing session via `put_token_in_session/2` without calling `renew_session/1`:
https://github.com/phoenixframework/phoenix/blob/3f671d7aee310465a57ff5c626f7ca1e44897589/priv/templates/phx.gen.auth/auth.ex#L97-L109

Honestly, I don’t know enough about session fixation attacks to know if this is a problem or not. If it is, it seems like it could be solved by just calling `renew_session/1` inside of `put_token_in_session/2`, rather than outside of it. Maybe the cookie being signed is enough?

**Comment by josevalim** [comment]
Thanks for the report. Session fixation attacks happen when using a non-cookie based session. For example, if you have a "sid=dhsklahjdjkslajdklsa" that identifies a database token, I ask you to join the website with that "sid", then you login, and now I have your account thanks to the sid.

With cookie based sessions, the cookie changes automatically every time you login. The renew: true is basically a no-op for cookie sessions but it is there in case you swap it out. Therefore, you don't have to renew cookies at all. :)

**Comment by phoebe100** [comment]
>  Therefore, you don't have to renew cookies at all

That's true as long as the session is stored in a cookie - as you explained very well.

But as soon as you change the phoenix default (cookie-based session) and use cookies containing a session-ID (e.g. by using a Redis store or the built-in Plug.Session.ETS), the current remember-me-token-handling generated by phx.gen.auth will give you an exploitable backdoor due to session fixation possibility - as @jbcaprell suspected

I doubt that most users are aware of that and will adjust the generated code as soon as they change their session store.

With that in mind, I would recommend to treat the login by remember-me-token as the same act of privilege escalation as standard login and hence, do in **both** cases the precaution step of session renewal.
