### ISSUE TITLE
ConnCase tests with different root path verified-routes warnings

### ISSUE THREAD

**Issue by Somebody25** [phoenixframework/phoenix#5476]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Operating system: Docker/Devcontainer

I have an application that has to run on a different sub path because it is behind a reverse proxy. I added the subpath to the configuration of the endpoint in `config.exs` , the `plug` in `endpoint.ex` and added a `scope` to the `router.ex`. The application does work on the subpath.

Suppose I have the subpath `/v2` and an api endpoint `/api/stuff` that I can reach with `http://localhost:4000/v2/api/stuff`

I try to add ConnCase tests to the application but run into an issue of verified-routes. 

### Expected behavior
The ~p sigil correctly resolves the path. Either `~p"/api/stuff"` is resolved to `/v2/api/stuff` and doesn't produce a warning or `~p"/v2/api/stuff` does not add another `/v2`.

### Actual behavior
If I use a route like `~p"/api/stuff"` the test execute but I get the verified-routes warning `warning: no route path for MyApp.Router matches "/api/stuff"`. If I add the sub path to the sigil `~p"/v2/api/stuff"` the warning is gone but the test fails because it is resolved to `/v2/v2/api/stuff`.

See discussion here: https://elixirforum.com/t/conncase-tests-with-different-root-path-verified-routes-warnings/56163

**Comment by phoebe100** [comment]
Currently, when setting the :path option in your Endpoint configuration,	I would recommend to overwrite it in your test config with "/"

In my opinion, setting the :path option value to	a value other than "/" is useful only when running Phoenix behind a reverse proxy with URL rewrite rules. But when testing controllers and calling the helpers from ConnTest (e.g. get/3, post/3) your requests never reach your (external) reverse proxy, so	your URLs are not rewritten and the tests are expected	to fail.

For me,	verified-routes works as I expect it to	work. It verifies, that you call routes as specified in	your router within phoenix (see mix phx.routes). The only aspect I could imagine as beneficial would be to change the ConnTest helpers, so that they "mock" the URL rewriting by stripping of the value from :path option whenever get/3, post/3 etc. are called. That would free you from overwriting the :path option in your test config.

**Comment by Somebody25** [comment]
Overriding the :path in the Endpoint configuration for the test config did work, thank you! The sigil then needs to include the subpath as set in the controller.
