### ISSUE TITLE
Endpoint path: option prepanded to links but not the actual paths, causing links pointing to non-existent urls

### ISSUE THREAD

**Issue by biserz** [phoenixframework/phoenix#5497]
### Environment

* Elixir version (elixir -v): 1.15
* Phoenix version (mix deps): 1.7.6
* Operating system: macOS 12.3

### Actual behavior

Hello! I'm trying to configure a Phoenix project to run on a domain subdirectory (eg. example.com/app) via Nginx. I'm trying to leverage the `path` option for my Endpoint that I found here in the docs (https://hexdocs.pm/phoenix/Phoenix.Endpoint.html) but I'm facing the following problem - when I add a value for `path`, the value gets added to the generated links, but not to the actual routes which cases all links to point to non-existent addresses.

I've created a sample app to illustrate that. This is my `path` config: https://github.com/biserz/path_test/blob/master/config/dev.exs#L22

That config updates all links to start with `/app` but then these links point nowhere as the actual routes do not have the `app` namespace:

![image](https://github.com/phoenixframework/phoenix/assets/6217781/3cd69314-7ca8-4fb0-9956-0765f7e375fc)

where the link leads to:
![image](https://github.com/phoenixframework/phoenix/assets/6217781/ceccfa16-c675-4eac-b4ab-ab8cde2d1541)

### Expected behavior

Expecting that **all** app routes will be mounted on the path configured through the `path` option

**Comment by phoebe100** [comment]
No issue here.

Your nginx acting as a reverse proxy should strip off the "/app" path prefix and forward the rest of the path to your phoenix application.
I think you are in dev environment and/or missed to set up your nginx reverse proxy properly.

The mentioned **path** config is just a nice tool to let your clients call your nginx endpoint.

"Routes" in phoenix are phoenix internal routes, since phoenix does not care whether you run in with or without a reverse proxy in front.
