### ISSUE TITLE
Templates used by phx.gen.auth do not use gettext

### ISSUE THREAD

**Issue by akirion** [phoenixframework/phoenix#5544]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Operating system: Windows 10

### Actual behavior

Template files used by phx.gen.auth, like priv/templates/phx.gen.auth/login_live.ex, use plain text.

### Expected behavior

Encapsulate text in gettext calls to make them translatable.

**Comment by josevalim** [comment]
Correct. We discussed this extensively and we decided that:

1. Most apps work on a single language
2. Most users will customize the generated pages anyway

Therefore we opted-in to keep it simpler and users can add gettext as needed. :)

**Comment by francois08** [comment]
@josevalim We have a `--no-gettext` option. If the user doesn't specify this option, we can infer that the user wants i18n. Can we then detect the use of gettext and have i18n for emails if enabled?

**Comment by BartOtten** [comment]
This was mentioned in a forum post at the forum and too be honest I am surprised by the rejection. Maybe one year later we should revise?

> The reason we don't do it by default is that then everyone would have to remove it

Core Components use Gettext. So this seems either inconsistent or outdated.

1. If Gettext is used throughout the application, it's inconsistent, surprising and a little irritating it's not in Auth.
2. Most apps work on a single language as having a multi language app is hard. If people would get it for 100% correct for free, every app would be multi language. That's an argument to make it as easy as possible.
3. True, but not all as Auth is simply not a core business page so as long as it works I am fine with the default.

**Comment by josevalim** [comment]
Hi @BartOtten, sorry for the delay.

It is worth noting that only the new app generator is gettext ready, none of the "within-the-app" generators use gettext, for similar reasons I mentioned above: they are all seen as a starting point and you will most likely do several changes to them anyway.

> Also the no-gettext flag can be used not to have them in the first place, so with inclusion in Auth and the flag it's all or nothing instead of some or nothing. Isn't it?

Which means that, if we were to add gettext to the "within-the-app" generators, now we need to have two versions of them: one with gettext, another without, which will quickly add in complexity, or make the generators more complex with conditional rendering.

> > Most apps work on a single language as having a multi language app is hard. If people would get it for 100% correct for free, every app would be multi language. That's an argument to make it as easy as possible.

I would agree with this argument in a vacuum but the truth is that we can't add i18n to an application without trade-offs and, in my experience, adding gettext is nowhere close to the hardest part of multi-language apps. I'd love if that's the case but managing the translation themselves takes the cake. :)

**Comment by josevalim** [comment]
Hi @BartOtten, sorry for the delay.

It is worth noting that only the new app generator is gettext ready, none of the "within-the-app" generators use gettext. Because, once again, the huge majority of web applications work with a single language/locale. If you are only working with a single language, you are just making everything visually cluttered by most users by writing `<button>{{ __("Register") }}</button>` instead of `<button>Register</button>` (e.g. if using English) or `<button>登録</button>` (e.g. if using Japanese). And don't get me started on applications that use Gettext in English and they have a single .po file in another language. It is just unnecessary friction to everyone.

> Most apps work on a single language as having a multi language app is hard. If people would get it for 100% correct for free, every app would be multi language. That's an argument to make it as easy as possible.

I don't think this argument holds in the real world. Adding gettext is nowhere close to the hardest part of multi-language apps. The true complexity lies in the surrounding infrastructure: a system for content managers, support staff who can communicate in each supported language, processes for managing regional-specific content and cultural considerations, etc. Even seemingly simple elements like date formats, currency displays, and right-to-left text support require careful consideration.

Btw, remember you can just ask your editor copilot to change the HEEx files to include Gettext too and it worked flawlessly when I tried it. I hope it is a good example of how this is one of the most straight-forward parts of the process.
