### ISSUE TITLE
phoenix 1.7.9 core_components focus_first erases first text input value in a form

### ISSUE THREAD

**Issue by blset** [phoenixframework/phoenix#5607]
line 614 of core_components

```
  def show_modal(js \\ %JS{}, id) when is_binary(id) do
    js
    |> JS.show(to: "##{id}")
    |> JS.show(
      to: "##{id}-bg",
      transition: {"transition-all transform ease-out duration-300", "opacity-0", "opacity-100"}
    )
    |> show("##{id}-container")
    |> JS.add_class("overflow-hidden", to: "body")
    |> JS.focus_first(to: "##{id}-content")
  end

```

the last `JS.focus_first` erases the value of the first text input in a form inside a modal
that would be displayed with show_modal

```
<.modal id="example">

<.form for={@form}>
<.input field={@form[:name]} /> <!-- existing value erased by focus -->
<.input field={@form[:address]} /> <!-- existing value correctly displayed -->

</.form

</.modal>



```

**Comment by chrismccord** [comment]
If you can share a minimal example app that reproduces this issue I can take a closer look, but I don't believe there is anything inherent to core_componetns and the use of focus_first that causes this. This sounds like you have some eform state that you are failing to maintain on the server on form change. Thanks!

**Comment by blset** [comment]
here is a minimal example, hope this helps
best regards


```
mix phx.new bido
mix phx.gen.live Tables Table tables longueur:integer largeur:integer

```
in router add
 ```
    live "/tables", TableLive.Index, :index
    live "/tables/new", TableLive.Index, :new
    live "/tables/:id/edit", TableLive.Index, :edit

    live "/tables/:id", TableLive.Show, :show
    live "/tables/:id/show/edit", TableLive.Show, :edit


```

then 
```

mix phx.server

```

create one table to go to some show page

in  tables_live/show.ex add
```

  @impl true
  def handle_event("exprepare", %{"cid" => cid}, socket) do
    {:noreply, assign(socket, record: %{"largeur" => cid, "longueur" => 40})}
  end

```
and in mount add

```
|> assign(:record, %{})
```

in tables_live/show.html.heex add
```
<a
  href="#"
  phx-click={
    JS.push("exprepare", value: %{cid: 12})
    |> show_modal("exmodal")
  }
>
  exemple 
</a>

<.modal id="exmodal">
  <.form for={@record} :let={f}>
    <.input field={f[:longueur]} label="Longueur />
    <.input field={f[:largeur]}  label="Largeur/>
  </.form>
</.modal>
```

Now when you click the example link

the first input field Largeur is empty where the focus is

![sc1](https://github.com/phoenixframework/phoenix/assets/567550/f514c588-7a68-4771-9082-4387af34ab5b)


now switch order of the two input fields in show.html.heex, the first field is consistently empty, and you see there was a value in Largeur
![sc2](https://github.com/phoenixframework/phoenix/assets/567550/9632e22b-19b5-43d1-ba12-6db5d7720075)


Now comment ou line 623 in core_component.ex in show_modal
 #|> JS.focus_first(to: "##{id}-content")

everything is ok   


![sc3](https://github.com/phoenixframework/phoenix/assets/567550/00d20ca7-4809-4f62-8c84-b4fd2cce8cb0)

**Comment by 03juan** [comment]
This is by design.

The client JS code is showing the modal and focusing the first input.
Then the LiveView process sends the updated input value, but the dom manipulation doesn't merge values for focused inputs.

In your case the input remains blank because the initial form renders with an empty map, otherwise it'll remain whatever the input's `value` attribute was before the updated assigns.

See https://github.com/phoenixframework/phoenix_live_view/blob/5ad3b749a64881d81f66d5cbbcfb53e19a31babb/assets/js/phoenix_live_view/dom.js#L370
```javascript
  mergeFocusedInput(target, source){
    // skip selects because FF will reset highlighted index for any setAttribute
    if(!(target instanceof HTMLSelectElement)){ DOM.mergeAttrs(target, source, {exclude: ["value"]}) }
    if(source.readOnly){
      target.setAttribute("readonly", true)
    } else {
      target.removeAttribute("readonly")
    }
  },
```

See this minimal gist:
https://gist.github.com/03juan/14d34ccca60b8cd800ae315e6377f840

**Comment by blset** [comment]
okay but on clicking the link in the example I provided,
before calling JS.show_modal, so before triggering the focus first,
 the assign was already populated with values 

so this is  counter intuitive 


or is this race conditions ?

**Comment by 03juan** [comment]
> the assign was already populated with values

Do you mean because of the ordering?
> <a
>   href="#"
>   phx-click={
>     JS.push("exprepare", value: %{cid: 12})
>     |> show_modal("exmodal")
>   }
> >
>   exemple 
> </a>

It's kind of a race condition.

Even though you're pushing the value to the server then showing the modal, the JS will execute on the client first and then LV will receive the async websocket message to morph the dom. There's inherent latency there, even in your local dev machine.

At this point the first input is already focused and showing whatever the pre-morph input's `value` attribute was, so the value from the server doesn't get set on the input because of `mergeFocusedInput()`.

Check out my updated gist, I added some extra links to test ordering.

**Comment by blset** [comment]
ok it's clear now  thanks
should the doc say something about that ?

**Comment by 03juan** [comment]
That's up to the maintainers but feel free to open a PR in the live_view repo 🙂
