### ISSUE TITLE
default root layout's html content width issue.

### ISSUE THREAD

**Issue by Dinesh563** [phoenixframework/phoenix#5656]
### Environment

* Elixir version (elixir -v): 1.15.0
* Phoenix version (mix deps): 1.7.10
* Operating system: Ubuntu 20.04.6 LTS (Intel® Core™ i7-10750H CPU @ 2.60GHz × 12 )

### Actual behavior
On Generating new phoenix project with `mix phx.new` the default root layout body element's width is not up to the full screen.
which generates a small gap between the right wall of the screen and the html content.
Note: i have not touched or written any css.

![Screenshot from 2023-12-04 07-38-04-copy](https://github.com/phoenixframework/phoenix/assets/64189091/a3c2a3ea-e3a9-4f39-9d10-61364c255694)

### Expected behavior
The default root layout's html must have width set to full screen.There should not be any gap between html content and the right screen.

**Comment by rhcarvalho** [comment]
Hi @Dinesh563! :wave: 

The current behavior was introduced in 7ab3d911e2989ef67782bd72938316ac862473c6 (later amended by 3085b13e402395138596f3648a11dd6a7899c0d5) in response to #5101.

I agree the reserved space can look strange, particularly for pages that would otherwise have no scrollbars and I have removed that in some projects. But I think any changes to the current root template would need to take the original issue it was trying to solve into account, and at least test that a proposed patch doesn't accidentally re-introduce the problem.

Since the template is just a template, we can also change it in our projects if the design asks for it, and deal with the consequences ourselves (we all might have different trade-offs at hand, for example not be using modals at all).

**Comment by josevalim** [comment]
I would probably just remove the class altogether. :)

**Comment by SteffenDE** [comment]
I'd also vote for just removing it. If people don't like the reflow, they can add the appropriate scrollbar-gutter setting themselves and decide on their own if they want, `stable` or maybe `stable both-edges`.

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

**Comment by Dinesh563** [comment]
cool!, removed the class :) .
https://github.com/phoenixframework/phoenix/pull/5662
