### ISSUE TITLE
Unable to set cookie signing_salt via environment variable

### ISSUE THREAD

**Issue by Jaza** [phoenixframework/phoenix#5810]
### Environment

* Elixir version (elixir -v): 1.16.2
* Phoenix version (mix deps): 1.7.12
* Operating system: Ubuntu 22.04

### Steps to reproduce

In `config/runtime.exs` , add:

    signing_salt =
      System.get_env("SIGNING_SALT") ||
        raise """
        environment variable SIGNING_SALT is missing.
        You can generate one by calling: mix phx.gen.secret
        """

    config :myapp, MyappWeb.Endpoint,
      ...,
      signing_salt: signing_salt

And in `lib/myapp_web/endpoint.ex` , change `@session_options` to not have `signing_salt` hard-coded:

    @session_options [
        store: :cookie,
        key: "_myapp_key",
        signing_salt: Application.get_env(:myapp, :signing_salt),
        same_site: "Lax"
      ]

Then run `mix phx.server` (with or without a `SIGNING_SALT` environment variable set).

### Actual behavior

I get:

    Compiling 1 file (.ex)
        warning: Application.get_env/2 is discouraged in the module body, use Application.compile_env/3 instead
        │
     10 │     signing_salt: Application.get_env(:myapp, :signing_salt),
        │                               ~
        │
        └─ lib/myapp_web/endpoint.ex:10:31: MyappWeb.Endpoint (module)

    == Compilation error in file lib/myapp_web/endpoint.ex ==
    ** (ArgumentError) cookie store expects :signing_salt as option
        (plug 1.15.3) lib/plug/session/cookie.ex:190: Plug.Session.COOKIE.check_signing_salt/1
        (plug 1.15.3) lib/plug/session/cookie.ex:220: Plug.Session.COOKIE.build_opts/1
        (plug 1.15.3) lib/plug/session/cookie.ex:74: Plug.Session.COOKIE.init/1
        (phoenix 1.7.12) lib/phoenix/socket/transport.ex:283: Phoenix.Socket.Transport.init_session/1
        (phoenix 1.7.12) lib/phoenix/socket/transport.ex:264: anonymous fn/1 in Phoenix.Socket.Transport.load_config/1
        (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (phoenix 1.7.12) lib/phoenix/socket/transport.ex:259: Phoenix.Socket.Transport.load_config/1
        (phoenix 1.7.12) lib/phoenix/endpoint.ex:696: Phoenix.Endpoint.socket_paths/4

### Expected behavior

Phoenix runs without errors.

**Comment by Jaza** [comment]
Related support question: https://elixirforum.com/t/setting-session-option-at-runtime-for-endpoint/42402

**Comment by Jaza** [comment]
Related issue: https://github.com/phoenixframework/phoenix/issues/4465

**Comment by Jaza** [comment]
Also note: I'm able to do this in `config/runtime.exs` without any problem:

    lv_signing_salt =
      System.get_env("LV_SIGNING_SALT") ||
        raise """
        environment variable LV_SIGNING_SALT is missing.
        You can generate one by calling: mix phx.gen.secret
        """

    config :myapp, MyappWeb.Endpoint,
      live_view: [signing_salt: lv_signing_salt],
      ...

Would be great if something similar were possible for the cookie `signing_salt` value.

**Comment by Jaza** [comment]
Forgive me if I'm just being stupid, I'm brand new to Elixir / Phoenix (my background is mainly in Python).

**Comment by phoebe100** [comment]
**Analysis**
- The error 'cookie store expects :signing_salt as option' is raised whenever your signing_salt is nil.
- As you can see from the logs (it says 'Compilation error'), the value is required at **compile time**
- However, Plug.Session.COOKIE allows to specify a MFA returning a binary
- Currently, Phoenix has no easy option to define the signing_salt by system environment at runtime like it can be done for secret_key_base, but there exists a workaround

**Workaround**
- instead of `signing_salt: Application.get_env(:myapp, :signing_salt),` you could do something like below in your endpoint.ex:
```
  defmodule AppEnv do
    def signing_salt() do
      # assuming you have 'config :myapp, signing_salt: signing_salt in your runtime.exs' 
      Application.get_env(:myapp, :signing_salt)
    end
  end

  @session_options [
    store: :cookie,
    key: "_myapp_key",
    signing_salt: {AppEnv, :signing_salt, []},
    same_site: "Lax"
  ]
```
**Conclusion**
- no Phoenix issue here
- if you want to see first class runtime environment support for signing_salt similar to what Phoenix does for secret_key_base, then this would be a feature request

**Comment by josevalim** [comment]
As @phoebe100 explained, the session is initialized at compile-time today, which explains why you can't set the signing salt value at runtime, as the code has already been compiled. You can either use a tuple, as shown above, or initialize the plug at runtime.

However, I am not sure if there is anything to gain here. There is no benefit in having the signing salt as a secret because the signing salt is always used in conjunction with the secret_key_base which should be secret, large, and random.

**Comment by Jaza** [comment]
@phoebe100 thanks for the workaround, that seems to do the trick for me. (And thanks for introducing me to "MFA", that's the first I've heard that Erlang / Elixir terminology, seems like it's roughly analogous to a callback function in other languages). If you say that "first class runtime environment support for signing_salt" is a feature request, not a bug, I'll accept that, considering that it's nonetheless possible to make it a runtime environment variable using your workaround. (Although perhaps this workaround should be documented more clearly).

@josevalim yes, I read the related threads from a few years ago, I accept that there's no benefit to having the signing salt as a secret, from a security point of view. However, in my opinion, the signing salt still falls in the category of "passwords / secret keys / tokens", and therefore it's still better to store it in an environment variable outside of the code, in the interest of following the 12-Factor App guidelines.

As I plan on having my Phoenix codebase be open source from day one, I'm particularly keen to not have any sort of keys / tokens ever make their way into version control (even if they're not particularly "secret" tokens). For example, I've already modified my app to fetch the database credentials from a `DATABASE_URL` environment variable for dev / test (not just for prod), [per this guide](https://bitcrowd.dev/two-small-adjustments-of-phoenix-application-configuration/).
