### ISSUE TITLE
Wrong version of phoenix liveview dependency picked

### ISSUE THREAD

**Issue by epinault** [phoenixframework/phoenix#5996]
### Environment

Elixir version (elixir -v): 1.17.3
Phoenix version (mix deps): 1.7.14
Operating system: OSX 13.7.1

### Actual behavior

so I created a new app ealier today. It seemed to have picked the 1.0.0-rc version... 

then I reran 10 min ago and I got this message too

```
Checksum mismatch between registry and the cached package for phoenix_live_view 1.0.0-rc.8

Registry checksum: 640a394899e9f3540abbbbfc3005ec7f38fbabb366f283ad84657165744bec00
Package checksum:  2808fdca29e1d3865304d2893829888a0b205fc8e556eb177a655ad60530b327

This may happen when the previously cached package got re-published, but it may also indicate a security issue so verify the new package.

Re-fetching...
```

what I am noticing is that the generated app came with the component using Phoenix.Component.used_input? which does not exist in prior version.

What I am wondering is why did this get an rc version ? I am using stable phoenix and I was not expecting to get an RC version unless I ask for it.

### Expected behavior

Pick the default stable liveview version. not an RC 1.0 version

**Comment by epinault** [comment]
morevover it seems there is a typo. Trying to upgrade an older project I see

```
And because no versions of phoenix_live_view match ~> 1.0.0, the lock requires phoenix_live_view ~> 0.19 or ~> 1.1-0.
```

**Comment by SteffenDE** [comment]
There was an issue with the formatter in the initial rc.8 release. To address this, Chris pushed a hotfix (allowed within the first hour of a new release on Hex). It seems you were very quick and initially downloaded the version without the fix, which explains the checksum mismatch.

Could you provide more details on how to reproduce the lock mismatch?

> What I am wondering is why did this get an RC version? I am using stable Phoenix, and I wasn’t expecting to receive an RC version unless I explicitly requested it.

Currently, there is no "stable" version of LiveView by definition. While we label it as "RC" (release candidate) because it is feature-complete from our perspective, these RC versions are no less stable than previous 0.X releases. Additionally, the 1.0.0-rc series of LiveView has been included in the Phoenix generators for some time now. If we avoided using the 1.0 RCs, newly generated apps would include deprecated code, which we want to avoid (yes, I see the irony with the gettext deprecation). For more details about the used_input change, please refer to the LiveView changelog.

**Comment by chrismccord** [comment]
As Steffen said, there was a ~30 min window where I replaced the LV 1.0.0-rc.8 release because there was a bug in the HTML formatter, so what you saw was a warning from having previously fetched the old version, which is transient so no worries there. Thanks!
