### ISSUE TITLE
Install script - Minor errors

### ISSUE THREAD

**Issue by brkn** [phoenixframework/phoenix#6016]
I've noticed some minor errors at https://new.phoenixframework.org/yourappname

1. Printed message for db_option is incorrect

```sh
elif command -v mysql >/dev/null 2>&1; then
  echo_heading "MySQL is installed. Using Postgres for the Ecto adapter."
  db_option="--database mysql"
```

Can be corrected as

```diff
-   echo_heading "MySQL is installed. Using Postgres for the Ecto adapter."
+   echo_heading "MySQL is installed. Using MySQL for the Ecto adapter."
```

2. Minor spelling error at the top comment, _Elixri_

```diff
- # See latest Elixri install.sh version at:
+ # See latest Elixir install.sh version at:
# https://github.com/elixir-lang/elixir-lang.github.com/blob/main/install.sh
```

### Note

Couldn't find the repo containing the install script at the phoenix github org, apologies if this is not the correct place to report.

**Comment by SteffenDE** [comment]
Hey @brkn,

thank you for reporting! The install script is currently in the private repo of the site. We've been thinking about open sourcing it once we have reworked it a little bit more. Currently it's private due to licensing constraints related to the old design.

I adjusted the script and it will be live after the next deploy! (@chrismccord)
