### ISSUE TITLE
What happened to Phoenix.PubSub.subscribers/2?

### ISSUE THREAD

**Issue by adamkittelson** [phoenixframework/phoenix#671]
I'm upgrading to 0.10.0 and it appears that Phoenix.PubSub.subscribers/2 has gone away. I don't see anything in backwards incompatible changes about it.

I do see that there is a Phoenix.PubSub.Local.subscribers/2 but I gather that only returns subscribers to a topic on the local node, is that right?

Is there no longer a way to get at :pg2.get_members/1 for PubSub topics via Phoenix's API?

**Comment by josevalim** [comment]
It is impossible to retrieve subscribers with the current architecture which aims to reduce the amount of messages between nodes. Previously, if you had 10 subscriber for TOPIC on node B, if you published from A, it would send 10 messages. Now it sends only one.

Also, subscribers is hard to implement on many backends, like redis.

You can either keep your own pg2 group or just broadcast the message you are supposed to send and wait for a timeout period to get a reply (crashing otherwise).

**Comment by ijt** [comment]
The docs don't reflect this: http://www.phoenixframework.org/v0.10.0/docs/channels

**Comment by chrismccord** [comment]
please direct issues in the guides to https://github.com/lancehalvorsen/phoenix-guides <https://github.com/lancehalvorsen/phoenix-guides>

**Comment by ijt** [comment]
Got it.
