### ISSUE TITLE
Rendering Template Through Layout from ErrorView Raises Exception

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix#694]
When trying to render a template through a layout in the ErrorView in a 0.10.0 app, I get an "undefined function: nil.static_path/1" error. This is the line in `application.html.eex` that generates the error `static_path(@conn, "/css/app.css")`.

Steps to Reproduce:
- Create a web/templates/error directory and add a "not_found.html.eex" template like this one.
```html

<div class="jumbotron">
  <p>Sorry, the page you are looking for does not exist.</p>
</div>
````
- Change the "404.html" clause of `render/2` to render the template with the `:layout` option.

```elixir
def render("404.html", _assigns) do
  render(HelloPhoenix.ErrorView, "not_found.html", layout: {HelloPhoenix.LayoutView, "application.html"})
end
```

- Go to `http://localhost:4000/silly_path` in a browser and check the `iex` session to see this:

```console
[error] #PID<0.275.0> running HelloPhoenix.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /sdkflj
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: nil.static_path/1
        nil.static_path("/css/app.css")
        (hello_phoenix) web/templates/layout/application.html.eex:11: HelloPhoenix.LayoutView."application.html"/1
        (phoenix) lib/phoenix/view.ex:243: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:460: Phoenix.Controller.render/4
        (phoenix) lib/phoenix/endpoint/cowboy_handler.ex:50: Phoenix.Endpoint.CowboyHandler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:435: :cowboy_protocol.execute/4
```

Interestingly, the following implementation will render the `not_found.html.eex` template without error, but won't render it inside the layout.

```elixir
def render("404.html", _assigns) do
  render("not_found.html", layout: {HelloPhoenix.LayoutView, "application.html"})
end
```

P.S. Guess which guide I'm overhauling for v0.10.0. :)

**Comment by chrismccord** [comment]
`static_path` requires Either the Endpoint module or the conn (which is gets the endpoint from conn.private.phoenix_endpoint`. So in this case, if you want to render a template without the context of hte `conn`, you need to do: `  `static_path(MyApp.Endpoint, "/css/app.css")` - or -  pass the `assigns` down through (which contains the `@conn`) 

```elixir
def render("404.html", assigns) do
  render("not_found.html", Dict.merge(assigns, layout: {HelloPhoenix.LayoutView, "application.html"}))
end
```

**Comment by josevalim** [comment]
That is not gong to work because you are calling the local render. You would have to call `render(__MODULE__, template, options)` which is non-obvious. I will tackle this when I tackle #675.

**Comment by lancehalvorsen** [comment]
Thanks! For the record, this is the incantation that worked for me.

```elixir
def render("404.html", assigns) do
  render(__MODULE__, "not_found.html", Dict.merge(assigns, layout: {HelloPhoenix.LayoutView, "application.html"}))
end
```

I've updated the View Guide in the repo and on the site to include changes for 0.10.0, and I've included this as a temporary workaround.

**Comment by josevalim** [comment]
@lancehalvorsen I have thought about this and I think we should not support this feature nor give such feedback in the guide. :)

The reason is: the error pages are rendered when anything goes wrong and they should be devoid of logic as much as possible. So let's suppose the application layout has a part of the menu that shows if the user is signed in or not. If we are doing a query in the database on the layout for that or assuming part of the stack authenticated the user, our layout and therefore error page will now fail too.

Our best feedback is, keep the error pages simple. Avoid layouts, *specially* your application layout. If you need to share code, define "footer.html"/"header.html" views and call them.

Does it make sense?

**Comment by lancehalvorsen** [comment]
@josevalim  I certainly sympathize with the idea of simplifying the edge cases around this. But I also know that most product companies are going to want a good-looking, fully-branded error page. They are also going to want an error page that let's the user navigate away from the problem into the rest of the site. Designers are going to fight to have that navigation look as close to the regular site navigation as possible. That's beginning to sound like a layout. :)

If folks are using Phoenix as an api server for a front end application, we get to push the problem onto the front-end application.

If folks are using Phoenix to render html, I think it's on us. So what should we suggest to people?

We could ask them to create an error template that mimics the application layout without any of the edge cases. In other words, this would be one big template that is the superset of the layout and the error template minus anything problematic. This would work right now as the render function does fine without a layout from the ErrorView. The issue is that any changes to the application layout would have to be duplicated in this error template.

Otherwise, we could tell people to create an error layout which has the look and feel that they need without the problematic bits, but that's sort of the worst of both worlds.

If we want to officially suggest option one (the superset template), I'm completely fine with that.

Long answer! Sorry. Good thing my job here is long-form prose. ;)

**Comment by paulcsmith** [comment]
@lancehalvorsen I tend to agree with what Jose said. I think it would be very easy to run into errors on the error view because of the layout. I also think that most designers have a custom error page. This is just anecdotal, but we tend to always design a custom error page that may have a search box or possibly just the navigation and footer up top. It's doesn't have that much in common with the rest of the pages. As Jose suggested, someone could just render the "footer.html" and "header.html" if they really needed to.

**Comment by josevalim** [comment]
Right. We need to add a layout somehow. The main idea here is that you can emulate that using header/footer or by having a single template and pass everything else that needs to be customizable as an assign:

    def render("404.html", assigns) do
      render "error.html", message: "Not found"
    end

The best strategy is going to change depending on how much stuff you have. Does it make sense?

**Comment by lancehalvorsen** [comment]
Totally makes sense. I need to remember to fully wake up before responding to github issues. I completely missed the header/footer part on first reading. Derp.

**Comment by augnustin** [comment]
Hello,

I'm very aware this issue is very old, but I just faced the situation and it seems like the discussion is still accurate nowadays as no layout behavior is expected by default in error view rendering, AFAIK.

Wouldn't it make sense for phoenix to build static error pages at asset building time?

This would allow the usage of layout logic for DRYing code, but would prevent layout components like header and footer to rise sub errors and more generally prevent the dev to use any request logic in the page, as it won't be available at build time.

Cheers
