### ISSUE TITLE
Generate application skeleton from anywhere

### ISSUE THREAD

**Issue by scrogson** [phoenixframework/phoenix#718]
Currently you have to clone `phoenix`, `mix deps.get`, `mix compile`, `mix phoenix.new ~/code/my_app`, `cd ~/code/my_app`, `mix deps.get`, `mix compile`,  ... before you're ready.

It would be nice if you could simply generate a new phoenix application from anywhere `mix` is available. I believe this would require `phoenix` to be installed as an `mix archive` or something?

**Comment by chrismccord** [comment]
This is on the roadmap. If it's not already an open issue, this can be the todo

**Comment by josevalim** [comment]
Yeah, we need to make it an escript or an archive. The pros of the archive is that it is easier to install (at least for now) but we will need to guarantee all modules in the archive have an isolated namespace otherwise it would conflict with Phoenix modules. For example, someone with an archive for Phoenix 0.1.0 working on a Phoenix 0.2.0 could have modules coming from different places and crash (the task or the app).

Escripts are isolated but you would need to install it and make it part of your path. Plus, none of them support priv, so we would need to rethink the whole strategy there anyway and how we should version those things together.

**Comment by endel** [comment]
The PHP ecosystem have a [`composer create-project`](https://getcomposer.org/doc/03-cli.md#create-project) command. Maybe `mix` could have a feature like that.

**Comment by josevalim** [comment]
In maaaaaster!
