### ISSUE TITLE
URL parameters should be encoded using to_param

### ISSUE THREAD

**Issue by drewolson** [phoenixframework/phoenix#752]
After upgrading to phoenix 0.11.0, I have a path helper that isn't working.

```elixir
membership_path(@conn, :new, employee_id: @employee)
```

This now fails with the following error:

```bash
** (Protocol.UndefinedError) protocol Enumerable not implemented for %MyApp.Employee{...}
```

@josevalim and I discussed on IRC and I'm opening this issue at his request.

**Comment by chrismccord** [comment]
So I'm assuming we need to recursively walk the values and call to_param?

**Comment by josevalim** [comment]
I wanted to change Plug to receive a function here:

https://github.com/elixir-lang/plug/blob/master/lib/plug/conn/query.ex#L157

Which would be called here instead of `to_string/1` (to string is the default though):

https://github.com/elixir-lang/plug/blob/master/lib/plug/conn/query.ex#L193

Then we can just pass to_param as argument here:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router/helpers.ex#L95

**Comment by josevalim** [comment]
This is fixed in master.
