### ISSUE TITLE
MyApp.Test, :conn and friends

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#772]
Now that Phoenix is getting support for controller and channel testing it might be helpful to have something similar to `MyApp.Web`, but for tests. That way it's easy to extend them with new modules, functions, imports, etc.

```elixir
defmodule MyApp.CommentsControllerTest do
  use MyApp.Test, :conn # or :model, :channel
end
```

I imagine this file would be auto-generated and go in test/support somewhere.

**Comment by josevalim** [comment]
We are shipping with two now:

* https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/test/support/conn_case.ex
* https://github.com/phoenixframework/phoenix/blob/master/installer/templates/ecto/model_case.ex

It doesn't use the same schema as `MyApp.Web` though because it wouldn't work with ExUnit case templates. Also, I think it would be ok to define functions in a case template module but we don't want that for the stuff in web.

**Comment by paulcsmith** [comment]
Oh I see. I didn't realize that there were templates that were copied to test/support on application creation. I just saw the `Phoenix.ConnTest` stuff . That solves everything I was trying to get at with my proposal. Thanks for the info @josevalim!
