### ISSUE TITLE
Render all GenServer timeouts as 504

### ISSUE THREAD

**Issue by elliotcm** [phoenixframework/phoenix#809]
Hi all,

Following [this twitter conversation](https://twitter.com/elliotcm/status/591936265139785728) I'd like to request a feature for the automatic rendering of GenServer timeouts as 504 gateway timeouts.

I can catch these in the controller but it'd be nice to have a fully supported version, or even a way to handle controller-based modifications to error responses.  By the time errors hit ErrorView it's too late to set a return status.

The specific case where I'm encountering this is where I'm hooking up multiple Phoenix apps over the mesh, but would apply to any backend process that might end up distributed and thus vulnerable to netsplits.

**Comment by josevalim** [comment]
The biggest issue is that local GenServer calls can also timeout and they shouldn't map to 504. That's why some sort of flag or configuration does not make sense in my opinion.

I would rather explicitly handle the cases you want to eventually become a 504 instead of slipping something globally. If you still want to be global, then @chrismccord solution is the best. You could even do it in the router if you don't want it per controllers (although I would avoid for the reasons said above).

**Comment by chrismccord** [comment]
I think @josevalim is right. 504 is useful in some cases as becoming a gateway timeout, but not always. In the meantime, you can override call and wrap as needed. Hope that helps!

**Comment by elliotcm** [comment]
True.  Happy to leave this closed, though I am curious as to what circumstances would lead to an uncaught local call timing out that wouldn't be considered an upstream timeout.  What sort of thing did you have in mind?
