### ISSUE TITLE
ArgumentError cannot use Plug.MethodOverride without body parsing, be sure to parse body parameters with Plug.Parsers

### ISSUE THREAD

**Issue by jonhkr** [phoenixframework/phoenix#872]
I've found another error similar to the one I've reported these days.

I'm sending a request with the following headers:
```
Accept: */*
Connection: keep-alive
Content-Type: application/xml
Origin: chrome-extension: //rest-console-id
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
```
And the server is returning a `500` response with the error described in the title.

This happens because there is no `application/xml` parser defined, however this in my opinion is not a server error (`500`) therefore a `4xx` http status response should be returned.

I guess most servers would not even return an error in this case.

**Comment by jonhkr** [comment]
Sending a request with `Content-Type:text/plain;charset=UTF-8` produces the same error.

**Comment by scrogson** [comment]
@jonhkr looks like @josevalim fixed this on Plug `master` here https://github.com/elixir-lang/plug/commit/8e2c5a6bfb51342e17eec7dca194f8f4d042f3bc

This should be fixed in the next release.

In the mean time, you can add Plug master to your application with the `override: true` option.

Let us know if that addresses your issue.

**Comment by jonhkr** [comment]
I've just run a test and that commit solves the issue. Thank you very much, closing this issue.
