### ISSUE TITLE
Provide clearer brunch wording in new task

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#885]

**Comment by lancehalvorsen** [comment]
Words? Perhaps you need some words? :^) How about these for a start:

Responding with "n" here will not prevent brunch.io from being installed - only its dependencies.

To avoid using brunch.io entirely, please cancel this installation and try again with the "--no-brunch" flag.

**Comment by josevalim** [comment]
We have a couple options here:

1. We ask once if you want to install remote dependencies. It doesn't matter if it is mix or brunch.

2. We change the wording to use "download"/"fetch" rather than "install".

3. We can change the behaviour to ask to install brunch *and* its dependencies, which is what most people are expecting currently

I think we should at least go with 1. I can't think about someone wanting to install mix dependencies but not the brunch ones. It is also less questions.

**Comment by gjaldon** [comment]
I agree 1 looks like the best option. Maybe just add a message after the install that informs the user what has been included in their new Phoenix app like: 
```
You're new Phoenix app comes set-up with the following:
  - Ecto - a DSL for interacting with your db. We configured it for Postgres. Check out the guides at https://github.com/elixir-lang/ecto
  - Brunch - a build tool blah. Check out the guides at brunch-guides.com
```

That way, there's immediate feedback about what the user just did and the fact that Ecto/Brunch was installed isn't kept from them.

3 looks like the next best one, but then why treat brunch differently than how phoenix treats ecto? Having a `--no-brunch` option is consistent with the `--no-ecto` option.

**Comment by lancehalvorsen** [comment]
I think that option number 1 still allows for an inconsistent install if the user says no to installing dependencies at app creation time, then later runs `mix deps.get` in the app directory. That is, unless I'm misunderstanding something.

What if we ask about brunch at the beginning, before anything else happens?

$ mix phoenix.new some_new_app

Phoenix is uses brunch.io for asset management by default. Would you like to continue to use brunch.io and install its dependencies? [Yn]

(app installation goes here)

Install mix dependencies? [Yn]

If users say no to brunch in the beginning, simply act is if they passed `--no-brunch`. Otherwise, use brunch and install the dependencies automatically.

**Comment by chrismccord** [comment]
We started off with the third approach, but the question is where do we draw the line? Like @gjaldon said, we assume defaults so Ecto is included. Should we prompt for Ecto too? If not, why is it any different?

**Comment by nurugger07** [comment]
I agree with Lance. If you are going to ask, it should be an all or
nothing, especially if it's going to appear broken if the deps aren't added.

**Comment by nurugger07** [comment]
@chris Honestly, I was a little surprised when I saw that Ecto was
installed by default. I understand there is a flag to remove it but it
seems a vanilla new app should have minimum deps. There are many cases that
I don't want/need ecto.

**Comment by lancehalvorsen** [comment]
I do think that ecto and brunch are different. Ecto is a dependency within the Elixir ecosystem. Brunch requires a whole new ecosystem - node, npm, etc. I think some people are sensitive to that.

**Comment by lancehalvorsen** [comment]
@nurugger07 that wasn't an answer to your last comment, but to questions above.

**Comment by chrismccord** [comment]
> @chris Honestly, I was a little surprised when I saw that Ecto was
> installed by default. I understand there is a flag to remove it but it
> seems a vanilla new app should have minimum deps. There are many cases that
> I don't want/need ecto.

I agree with min deps, but it's our job to provide sane defaults to newcomers. As a seasoned Elixir programmer, you know very well the times you don't want or need ecto, and you know you can just pass a flag, so it's a few keystrokes for you every time you start a project. For a newcomer though, we remove the questions/uncertainty of "okay I have new project now, what about databases? What about css/js?" etc.

**Comment by nurugger07** [comment]
@lance understood. I usually opt for less dependencies regardless :) I
think the developers should determine their tools. That being said there
are people looking for a "Rails" solution. Just my 2 cents. That with a
dollar might get ya a cup of coffee :)

**Comment by nurugger07** [comment]
@chris I totally agree with you. I think this is more about making sure
devs don't go down a path that appears broken. I think the direction
Phoenix is heading is not only positive but necessary.

**Comment by kkirsche** [comment]
Personally, I like the option of using other JS pipelines other than brunch. I feel there is a big difference between mix and brunch also. I would argue with a tool like Mix or Bundler, there really aren't any solid alternatives but in the JS world I have multiple build pipelines: Grunt, Gulp, Brunch, etc.

I think that if brunch is going to be something which is included and prompts are given about it, I think it would be helpful to teach the user a bit more about Brunch in general. Personally, I was very frustrated with Brunch when it was getting installed and was always removing it after `phoenix.new` because, at least for me, I didn't find the documentation (of Phoenix or Brunch) to cover how Brunch integrates with Phoenix and it's initial capabilities / limitations.

Just my opinion though :smiley:

**Comment by josevalim** [comment]
Maybe we should have a guide explicitly about brunch integration?

**Comment by lancehalvorsen** [comment]
Yes, we can easily re-purpose the Static Asset Guide. We can also include more discussion of brunch and it's dependencies in the Up and Running Guide and the Mix Tasks Guide.
