### ISSUE TITLE
Generate lib/mix/tasks

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#909]
We should generate at minimum the empty directory in new projects, but I am also leaning towards an example task so users new to Elixir have a gentle introduction to how tasks can be written. Thoughts?

**Comment by lancehalvorsen** [comment]
I think the empty directory would be good, but I think an example task would be fantastic. I say that for the same reason that I think the generators are great. As you said, they give people a gentle introduction to topics they may be unfamiliar with.  :+1:

**Comment by gjaldon** [comment]
Sounds good to me! Better if the Mix task has practical value. How 'bout if we provide a starter seed task if they have Ecto installed? Increases the likelihood of new users touching it and developing it further while more experienced ones would still find it useful.

Not sure what type of task to generate for those that don't use Ecto though...  Maybe just a trivial task as example since they are likely more experienced when they do not use Phoenix defaults?

**Comment by josevalim** [comment]
I am torn because we have three ways of solving this problem:

1. Using a mix task in lib/mix/tasks
2. Using an alias in mix.exs (good only for quick examples)
3. Using scripts that you run with mix run scripts.exs

I have a hunch that 3 would be the simplest and easiest for the majority of cases. Unless you want to provide something structured.

So I would go with @gjaldon advice of providing a seeds.exs script inside priv/repo and add some documentation at the top saying "run this with `mix run seeds.exs`, if you pass arguments, as in `mix run seeds.exs foo` you can access them via `System.argv/0`".

This way, we provide a good example of how using scripts and nudge people to the proper direction.

Thoughts?

**Comment by ericmj** [comment]
I agree with @josevalim, mix tasks are overkill in the majority of cases.

**Comment by whatyouhide** [comment]
:+1: for @josevalim's proposal, nice and simple.

**Comment by chrismccord** [comment]
Starter seed task is what led me to create this issue as it was exactly what I was adding to one of my projects. I may be the minority, but I think a full mix task is preferable. I have not once used an exs file to be run with `mix run` in a real project. I'm not against it, but mix tasks give us a a couple things, namely moduledoc that is included in the built docs, obvious ways to run the intended task, composability b/w tasks. If I end up with a bunch of exs files it's not immediately clear how to run them, how they compose, where the documentation lives, etc. Have I settled on wrong conventions? Whatever is decided, we should include one defacto, obvious choice for this, so we can remove the paradox of choice of 1-3 from new users.

**Comment by josevalim** [comment]
@chrismccord the only thing mix tasks gives is a template for documentation. Everything else works with scripts too.

To me the rule is this: are we going to document the task and treat like proper code? If so, put it in lib. Otherwise, it is a script. I assume folks are not testing their seeds, so to me it is more of a script than something that goes into lib.

**Comment by chrismccord** [comment]
@josevalim Thanks. I think the "if you need to test it, then task, otherwise script" is a great answer that is easy to follow

**Comment by gjaldon** [comment]
> "if you need to test it, then task, otherwise script"

Nice simple rule. Would be great to communicate that somehow to Elixir/Phoenix users. We could add that to the comments for the starter seed script/task.

Looks like scripts are the way to go. Much easier for those new to Elixir to start with and use. Re the example task, maybe point users to one of the Phoenix tasks or cover it in the guides?

**Comment by HeroicEric** [comment]
Figuring out how to create a seed task is one of the first things I ran into when getting started with Phoenix (coming from Rails). I'm definitely :+1: for anything as long as it's documented and easy for new users to find.

**Comment by josevalim** [comment]
The seeds task is in.
