### ISSUE TITLE
Channel "join crashed" error should log the reason

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#966]
Today there is no indication of what the actual error is.

**Comment by ericmj** [comment]
:heart:

**Comment by josevalim** [comment]
Wait. Doesn't the GenServer log if join crashes? Why you are not seeing that log?

**Comment by josevalim** [comment]
No, it does not. However I think we should improve the reporting.

**Comment by ericmj** [comment]
@josevalim GenServer doesn't log init errors.

**Comment by ericmj** [comment]
@josevalim The reporting has been fixed in Phoenix, if you think we should always report GenServer.init errors lets open an issue on Elixir?

**Comment by josevalim** [comment]
Well, we should log more information in Phoenix for now anyway. Opening an issue for Elixir sounds like a good idea too.

**Comment by ericmj** [comment]
What extra information is needed, the exception and stacktrace should be enough to fix an issue?

Should we really log `init` errors though? /cc @fishcakez

**Comment by fishcakez** [comment]
If a `GenServer` fails in `init/1`, `start(_link)/3` returns an error and the caller can handle it, as in the fix here. The best example of this is a `Supervisor`, which will log an error report if it initiated the `start_link` on its own, so logs are generally already available for this.  In the `Supervisor` case, and really all others, it can not know if the child exited due to an error or an exit signal from another process so will want to log regardless! Also as `GenServer` uses `:proc_lib` an abnormal exit reason will send a "sasl" crash report. Logger already supports all these messages.

**Comment by chrismccord** [comment]
@josevalim I'm not sure what extra info we need in the exception format. Can you take a look when you get a chance?

**Comment by chrismccord** [comment]
@josevalim to loop you in, I belie

**Comment by chrismccord** [comment]
@josevalim to loop you in, I believe Eric and James decided the current behaviour is sufficient. Can you confirm?

**Comment by josevalim** [comment]
I can't check right now. Please leave it open, i will investigate when I can. :)
